### ISSUE TITLE
interdependencies

### ISSUE THREAD

**Issue by oberon2007** [fasheng/arch-deepin#101]
What makes customization of deepin extremely hard at the moment are the interdependencies of packages:
Customizing the **deepin-artwork-themes** package means that I need as a consequence a replacement for **dde-control-center** plus **dde-workspace** plus **startdde** because of the dependency chain.
I understand that it makes perfect sense for dde-control-center depending on deepin-artwork-themes but it would certainly make my life a lot easier if you could consider removing this from the depends-array...

**Comment by fasheng** [comment]
Dispatched for dde-control-center, dde-dock-applets and dde-workspace.

**Comment by oberon2007** [comment]
Dispatched? You mean removed? That would be awesome ;)

**Comment by oberon2007** [comment]
Ok, I see the changes now. Thank you so much for your cooperation! :)
