### ISSUE TITLE
nautilus-root

### ISSUE THREAD

**Issue by oberon2007** [fasheng/arch-deepin#102]
Is there any way to launch nautilus as root except from the terminal?
Adding a .desktop file in /usr/share/applications for gksu nautilus does not create an entry in the launcher.

**Comment by fasheng** [comment]
Really? It works for me
```
sudo cp org.gnome.Nautilus.desktop root-nautilus.desktop
```
Then you could find two `Files` icons in the launcher without  any more operations.

BTW you can put the `.desktop` file to `~/.local/share/applications` too.

**Comment by oberon2007** [comment]
Hm. Yes this creates a second entry, but I have the problem that no matter what I enter under Name= or Icon= , it uses the same icon as normal Nautilus and is calles "Files" ...

**Comment by fasheng** [comment]
I see, looks dde-launch don't monitor the modification of the desktop file content. How about re-login ?

**Comment by oberon2007** [comment]
Yes, thank you! Re-logging helps ;)
