### ISSUE TITLE
Deepin doesn't start

### ISSUE THREAD

**Issue by jannickfahlbusch** [fasheng/arch-deepin#103]
Since yesterday, deepin refuses to start.

This is the error i get, when i run `startdde` or `startx`:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x80 pc=0x5e8dd0]

goroutine 1 [running]:
github.com/BurntSushi/xgb/xproto.InternAtom(0x0, 0x30000, 0x9f3cd0, 0x3, 0x0)
	/usr/lib/go/src/github.com/BurntSushi/xgb/xproto/xproto.go:10975 +0x300
pkg.deepin.io/dde/startdde/display.getAtom(0x0, 0x9f3cd0, 0x3, 0xa61b00)
	/usr/src/packages/BUILD/startdde/src/startdde/gopath/src/pkg.deepin.io/dde/startdde/display/utils.go:39 +0x3f
pkg.deepin.io/dde/startdde/display.init()
	/usr/src/packages/BUILD/startdde/src/startdde/gopath/src/pkg.deepin.io/dde/startdde/display/detect_output.go:135 +0x15c
main.init()
	_/usr/src/packages/BUILD/startdde/src/startdde/_obj/_cgo_import.go:1 +0x47

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1696 +0x1
```

**Comment by fasheng** [comment]
I updated system just now, then run `startx /usr/bin/startdde` and everything works fine.

About the errors you paste, I guess it's the output of `startdde` in tty which is not the correct way to launch DDE, you should use `startx` or `xint` instead. And please upload `~/.xsession-errors` if failed again. :)

**Comment by SolarAquarion** [comment]
[.xsession-errors.txt](https://github.com/fasheng/arch-deepin/files/32431/default.xsession-errors.txt)

Here is the file for your needs

**Comment by fasheng** [comment]
@SolarAquarion So you installed the latest startdde 2.91.1.r17.ge972e6e-0 in arch-deepin:2015, right?

It looks like caused by dbus, how about run `dbus-launch --exit-with-session xinit` in tty?

**Comment by SolarAquarion** [comment]
I'll try that

**Comment by SolarAquarion** [comment]
[.xsession-errors.txt](https://github.com/fasheng/arch-deepin/files/33164/default.xsession-errors.txt)

still getting it

**Comment by fasheng** [comment]
Strange issue. Could you upload the updated package list in `/var/log/pacman.log` at the moment that the first time startdde launche failed?

**Comment by SolarAquarion** [comment]
[pacman.txt](https://github.com/fasheng/arch-deepin/files/34104/pacman.txt)

**Comment by fasheng** [comment]
thanks



2015年11月13日 下午11:57, 下午11:57，在 SolarAquarion <notifications@github.com> 已写:

**Comment by fasheng** [comment]
Please remove OBS repository from
`/etc/pacman.conf` and update packages like this:

```sh
sudo pacman -R dde-dock-applets
sudo pacman -Syyuu
```

If start Deepin failed again, just reopen this issue.
