### ISSUE TITLE
default_background

### ISSUE THREAD

**Issue by oberon2007** [fasheng/arch-deepin#107]
At the moment **/usr/share/backgrounds/default_background** is owned by **dde-workspace**.
Unfortunately as a consequence in order to customize the default background I have to build a custom dde-workspace just for that...
Would it maybe be possible to move that file to either **artwork-themes** or **gsettings** instead? I think those would be the logical places for that anyway...

**Comment by fasheng** [comment]
Yes, for 2015, dde-workspace will be removed and we just did what you said :)




2015年11月15日 上午4:19, 上午4:19，在 Bernhard Landauer <notifications@github.com> 已写:

**Comment by oberon2007** [comment]
ok. thanks! :)
