### ISSUE TITLE
Deepin Terminal missing ttf-dejavu dependency

### ISSUE THREAD

**Issue by fusion809** [fasheng/arch-deepin#109]
Hi,

I'm not sure whether I should report this issue here or not (as I understand `deepin-terminal` has been moved to the community repo) but it seems that the `deepin-terminal` package is missing the `ttf-dejavu` dependency. I say this because I tried to launch the Deepin Terminal within DDE and it failed, so I ran `deepin-terminal` from LXTerminal and it gave me an error message (sorry I didn't save it) that indicated that the DejaVu Sans Mono font couldn't be found, so I installed `ttf-dejavu` and this fixed my problem. 

Thanks for your time,
Brenton

**Comment by fasheng** [comment]
Thanks for the detailed report, @felixonmars will help us to solve it ;)

**Comment by felixonmars** [comment]
Fixed in deepin-terminal 1.1.0.20151104-1
