### ISSUE TITLE
request remove depends

### ISSUE THREAD

**Issue by oberon2007** [fasheng/arch-deepin#112]
@felixonmars @fasheng , would it be possible to remove **deepin-desktop-schemas** from the depends-array of **deepin-daemon**, **deepin-mutter** and **deepin-wm** ?
That will allow me to use a custom gsettings package. Maybe you would like to add it to group **deepin** instead?

**Comment by felixonmars** [comment]
Removing the dependency will actually break functionality if the user just happen to install the package. How about making your custom package provides `deepin-desktop-schemas` and use a meta-package to depend on all packages you need?

**Comment by oberon2007** [comment]
It works with the provides array, yes, thank you. I was not expecting pacman to be so clever during building an ISO to not install those other dependencies first :)
