### ISSUE TITLE
Deepin 2D ?

### ISSUE THREAD

**Issue by oberon2007** [fasheng/arch-deepin#114]
In the greeter I now have a choice between session "Deepin" and "Deepin 2D". What's the difference?

**Comment by felixonmars** [comment]
The former is using deepin-wm (Gala/Mutter) while the latter is using deepin-metacity, which has less graphics effects and should run more smoothly on older hardware.

**Comment by oberon2007** [comment]
Great, thanks! :)

**Comment by oberon2007** [comment]
Is there a way to set Deepin 2D as the default session?
``user-session=deepin`` in **lightdm.conf** seems to launch the regular session.
And when using **startx**, will **startdde** also always open the regular session?

**Comment by fasheng** [comment]
try '`startdde -wm /usr/bin/deepin-metacity ` in .xinitrc



2015年12月4日 上午6:47, 上午6:47，在 Bernhard Landauer <notifications@github.com> 已写:

**Comment by oberon2007** [comment]
Thank you. Will try that.
What about user-session in **lightdm.conf** ?

**Comment by felixonmars** [comment]
We have user-session `deepin-2D`, and also we have `/usr/bin/startdde-2D`.

**Comment by oberon2007** [comment]
great! thanks :)
