### ISSUE TITLE
Inconsistent icon of sublime text 3 in dock and alt-tab which launched from synapse

### ISSUE THREAD

**Issue by fasheng** [fasheng/arch-deepin#119]
**Steps to reproduce:**
1. install related packages `yaourt -S synapse sublime-text-dev`
2. launch sublime from synapse
3. see the icon of sublime in dock and alt-tab

**Actual results:**
The icon of sublime in dock and alt-tab is different.

**Expected results:**
The icon of sublime in dock and alt-tab is the same.

**Comment by felixonmars** [comment]
Looks like it's fixed with [community-testing]/deepin-dock 2.90.1.20151203-1
