### ISSUE TITLE
There is no account icon in the main page of control center

### ISSUE THREAD

**Issue by fasheng** [fasheng/arch-deepin#122]

**Comment by oberon2007** [comment]
Why have you removed the upstream label? Running Deepin official ISO just now. It has the same issue ;)

**Comment by fasheng** [comment]
Because most of the issues are caused by upstream(through it works well in official ISO), and I think each issue should not own too much labels, so just remove it :P

**Comment by fasheng** [comment]
@sbwtw Help ;)

**Comment by fasheng** [comment]
The same issue https://github.com/linuxdeepin/dde-control-center/issues/6

**Comment by sbwtw** [comment]
this bug not fix completely in upstream, its just fallback to default 
icon (/var/lib/AccountService/icons/default.png)

On 12/14/2015 05:19 PM, fasheng wrote:
>
> The same issue linuxdeepin/dde-control-center#6 
> <https://github.com/linuxdeepin/dde-control-center/issues/6>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/fasheng/arch-deepin/issues/122#issuecomment-164386158>.
>

-- 
*石博文*

**Comment by oberon2007** [comment]
Thanks for the info! @felixonmars could you please upd **deepin-account-faces** to (commit 799e6aa)[https://github.com/linuxdeepin/dde-account-faces/commit/799e6aa0605167bab6b283aa1114c8aee555a45f] for a preliminary fix?

**Comment by felixonmars** [comment]
Updated: deepin-account-faces 1.0.9.20151210-1

**Comment by oberon2007** [comment]
Thanks a lot! :) Working as expected.

**Comment by felixonmars** [comment]
Still fallbacks to default in 3.0.1.

**Comment by oberon2007** [comment]
working now :)

**Comment by felixonmars** [comment]
Confirmed, thank you!
