### ISSUE TITLE
Dock panic with error "runtime error: invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by fasheng** [fasheng/arch-deepin#127]
```
panic: runtime error: invalid memory address or nil pointer dereference
```

**Comment by felixonmars** [comment]
Seems like fixed some time ago, closing.

**Comment by DarkSunOne** [comment]
No, fresh installed arch and deepin and it brought me here

**Comment by fasheng** [comment]
@DarkSunOne Could you reproduce it, or it just crash random?

**Comment by DarkSunOne** [comment]
As i said, i installed Arch, and than Deepin, i didn't installed a DM, and tried starting deepin with "startdde" and got exact that error message.

**Comment by fasheng** [comment]
How about launch startdde through **xinit** in tty?

**Comment by le-mon** [comment]
same issue here on arch everytime i try to startdde through xinit. 
with lightdm it's not working either.

**Comment by fasheng** [comment]
@le-mon Please upload `~/.xsession-errors` and the output of `coredumpctl dump /usr/bin/dde-dock`.

**Comment by imAWinner** [comment]
I'm having this issue
