### ISSUE TITLE
Dock prints lots of "firefox overlap dock" errors under "Smart hide" mode

### ISSUE THREAD

**Issue by fasheng** [fasheng/arch-deepin#128]
```
com.deepin.daemon.Dock[5186]:  .:0: firefox overlap dock
```

**Comment by oberon2007** [comment]
Is this really an error message? I get it, too, but only when the dock and ff are indeed overlapping because I invoke the dock while ff is in fullscreen :)

**Comment by jannickfahlbusch** [comment]
I don't know if this is related, but the icon of ff gets cutted of, because it is to low.

The screenshot shows it: 
![bug](https://cloud.githubusercontent.com/assets/8135397/11609365/99b26e74-9b85-11e5-9fee-76381fa633a1.png)

**Comment by felixonmars** [comment]
Also this message:

```
daemon/dock[4192]: .:0: active window is maximized client
```
