### ISSUE TITLE
Trayicons with additional black area and sometimes misplaces 

### ISSUE THREAD

**Issue by oberon2007** [fasheng/arch-deepin#132]
![2015-11-26-133024_107x96_scrot](https://cloud.githubusercontent.com/assets/11800714/11423118/0b5a7440-9442-11e5-8506-f9caeaba4ef5.png)
Also, sometimes Pamac icon is displayed twice with only one of them functional to clicks.
In Deepin 2014 they used to be displayed without the black area around the icons and better centered.

**Comment by fasheng** [comment]
Fixing in upstream and mostly works, just waiting for the code merged.



2015年11月26日 下午8:34, 下午8:34，在 Bernhard Landauer <notifications@github.com> 已写:

**Comment by oberon2007** [comment]
Fixed with latest pkg-update. Thank you!
