### ISSUE TITLE
LunaCalendar detect language settings failed

### ISSUE THREAD

**Issue by oberon2007** [fasheng/arch-deepin#133]
Settings keyboard to German and system language to English in Control Center leaves keyboard at English. Issuing ``setxkbmap de`` from the terminal works temporarily.
In any case the dock calendar looks like this: 
![calendar](https://cloud.githubusercontent.com/assets/11800714/11428838/75bce3bc-9470-11e5-9be7-086a2dd271f0.png) ;)

**Comment by felixonmars** [comment]
Yeah, and it's called LunarCalendar :P

**Comment by fasheng** [comment]
Upstream issue，fixing now...

**Comment by felixonmars** [comment]
Looks like fixed with [community-testing]/deepin-control-center 2.91.2.20151203-1

**Comment by oberon2007** [comment]
Yes, it's fine now, thanks!
