### ISSUE TITLE
cannot add desktop icons

### ISSUE THREAD

**Issue by oberon2007** [fasheng/arch-deepin#134]
Clicking on an app in the launcher and selecting "Send to desktop" does not create a desktop icon.
When switching to efficient or classic mode, only icons for Computer and Trash are visible, but not the added applications.
Right-clicking the same app in the launcher for a second time shows the selection "Remove from desktop".
**edit:** Also a manually created **.desktop** file in **~/Desktop** is not showing up for me.

**Comment by fasheng** [comment]
Should be caused by the thumbnails issue.
https://github.com/fasheng/arch-deepin/issues/126

**Comment by oberon2007** [comment]
Maybe. I'm not sure, though, because not only the icon is missing. There is no text entry, either. But maybe the whole desktop item is not created then...
How do you get these log infos by the way?

**Comment by fasheng** [comment]
you mean the syslog? just using `journalctl -f` :)

**Comment by oberon2007** [comment]
working now :)
