### ISSUE TITLE
Theme list is empty and all settings not works in personalization module

### ISSUE THREAD

**Issue by fasheng** [fasheng/arch-deepin#135]
@oberon2007 Let's discuss it here.
Could d-c-c(deepin-control-center) list your fonts correctly? And what's the output of `fc-list` in your system?

**Comment by oberon2007** [comment]
The entry for fonts in dcc is empty but when I click on the fields they are listed. I can select them but when I close dcc and re-open the fields are empty again.
Output of fc-list is the long list of everything in **/usr/share/fonts/...** as expected ;)

**Comment by oberon2007** [comment]
Do we have any hint on what is causing this? Is personalization working for you, @fasheng , @felixonmars and can I investigate any differences in my setup maybe?
I am blocked until this is solved.

**Comment by felixonmars** [comment]
It works here. Can you try to install `adobe-source-han-sans-otc-fonts` or `adobe-source-han-sans-cn-fonts` and restart to see if it makes any difference?

**Comment by oberon2007** [comment]
Thank you, but no difference... I am still wondering if I am simply missing a crucial package. What I have here is only the two groups on top of a basic manjaro install that would normally work with any common desktop including Gnome and also Deepin 2014.3 It is kind of mysterious.

**Comment by fasheng** [comment]
anyway, the Deepin packages in [comkunity] works for felix and me, and I have asked our developer to help to solve it, maybe he will provide suggestions to us.

**Comment by jouyouyun** [comment]
Please paste the following commands's output.
```shell
$ cat /usr/share/personalization/themes/Deepin/theme.ini
$ ls /usr/share/themes
$ ls /usr/share/icons
$ ls /usr/share/backgrounds
$ fc-list | grep "Source Han Sans"
$ fc-list | grep "Droid" 
$ fc-match sans-serif
$ fc-match monospace
```
Thanks!

**Comment by oberon2007** [comment]
Thank you very much, @jouyouyun !
I think that the output is what should be expected and also mind: The backgrounds, icon-themes and fonts are listed in dde-control-center. But they cannot be applied!
Only "Themes" is empty and as I said ~/.local/share/personalization is never created when you try to change the theming.
I'm still wondering if I am missing a crucial component or package to make the desktop work at all...?
```
$ cat /usr/share/personalization/themes/Deepin/theme.ini
[Theme]
Id=Deepin
Name=Deepin
Name[en_GB]=Deepin
Name[en_US]=Deepin
Name[zh_CN]=Deepin
Name[zh_HK]=Deepin
Name[zh_TW]=Deepin

[Component]
GtkTheme=Deepin
IconTheme=Deepin
CursorTheme=Deepin-Cursor
FontName=sans-serif
FontMono=monospace
FontSize=11
BackgroundFile=file:///usr/share/backgrounds/deepin_default_background.jpg
SoundTheme=deepin
```
```
$ ls /usr/share/themes
Adwaita/       Bright/  Default/  HighContrast/  Simple/
AgingGorilla/  Crux/    Emacs/    Metabox/
Atlanta/       Deepin/  Esco/     Raleigh/
```
```
ls /usr/share/icons
Adwaita/  Deepin/  default/  Flattr/  Flattr Dark/  hicolor/
```
```
ls /usr/share/backgrounds
deepin_default_background.jpg
```
```
fc-list | grep "Source Han Sans"
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Bold.ttc: Source Han Sans HW TC,思源黑體 HW,思源黑體 HW Bold,Source Han Sans HW TC Bold:style=Bold,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Bold.ttc: Source Han Sans SC,思源黑体,Source Han Sans SC Bold,思源黑体 Bold:style=Bold,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Regular.ttc: Source Han Sans HW SC,思源黑体 HW,Source Han Sans HW SC Regular,思源黑体 HW Regular:style=Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Medium.ttc: Source Han Sans K,본고딕,Source Han Sans K Medium,본고딕 Medium:style=Medium,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Normal.ttc: Source Han Sans SC,思源黑体,Source Han Sans SC Normal,思源黑体 Normal:style=Normal,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Normal.ttc: Source Han Sans,源ノ角ゴシック,Source Han Sans Normal,源ノ角ゴシック Normal:style=Normal,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Light.ttc: Source Han Sans,源ノ角ゴシック,Source Han Sans Light,源ノ角ゴシック Light:style=Light,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Heavy.ttc: Source Han Sans,源ノ角ゴシック,Source Han Sans Heavy,源ノ角ゴシック Heavy:style=Heavy,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Normal.ttc: Source Han Sans K,본고딕,Source Han Sans K Normal,본고딕 Normal:style=Normal,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Medium.ttc: Source Han Sans SC,思源黑体,Source Han Sans SC Medium,思源黑体 Medium:style=Medium,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Regular.ttc: Source Han Sans K,본고딕,Source Han Sans K Regular,본고딕 Regular:style=Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Bold.ttc: Source Han Sans HW SC,思源黑体 HW,Source Han Sans HW SC Bold,思源黑体 HW Bold:style=Bold,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-ExtraLight.ttc: Source Han Sans,源ノ角ゴシック,Source Han Sans ExtraLight,源ノ角ゴシック ExtraLight:style=ExtraLight,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Bold.ttc: Source Han Sans K,본고딕,Source Han Sans K Bold,본고딕 Bold:style=Bold,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Bold.ttc: Source Han Sans TC,思源黑體,思源黑體 Bold,Source Han Sans TC Bold:style=Bold,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Regular.ttc: Source Han Sans HW,源ノ角ゴシック HW,Source Han Sans HW Regular,源ノ角ゴシック HW Regular:style=Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Bold.ttc: Source Han Sans,源ノ角ゴシック,Source Han Sans Bold,源ノ角ゴシック Bold:style=Bold,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Regular.ttc: Source Han Sans HW TC,思源黑體 HW,思源黑體 HW Regular,Source Han Sans HW TC Regular:style=Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Bold.ttc: Source Han Sans HW K,본고딕 HW,Source Han Sans HW K Bold,본고딕 HW Bold:style=Bold,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Medium.ttc: Source Han Sans TC,思源黑體,思源黑體 Medium,Source Han Sans TC Medium:style=Medium,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-ExtraLight.ttc: Source Han Sans TC,思源黑體,思源黑體 ExtraLight,Source Han Sans TC ExtraLight:style=ExtraLight,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Regular.ttc: Source Han Sans TC,思源黑體,思源黑體 Regular,Source Han Sans TC Regular:style=Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Light.ttc: Source Han Sans SC,思源黑体,Source Han Sans SC Light,思源黑体 Light:style=Light,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Heavy.ttc: Source Han Sans SC,思源黑体,Source Han Sans SC Heavy,思源黑体 Heavy:style=Heavy,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Regular.ttc: Source Han Sans SC,思源黑体,Source Han Sans SC Regular,思源黑体 Regular:style=Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Light.ttc: Source Han Sans K,본고딕,Source Han Sans K Light,본고딕 Light:style=Light,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Heavy.ttc: Source Han Sans K,본고딕,Source Han Sans K Heavy,본고딕 Heavy:style=Heavy,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Bold.ttc: Source Han Sans HW,源ノ角ゴシック HW,Source Han Sans HW Bold,源ノ角ゴシック HW Bold:style=Bold,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-ExtraLight.ttc: Source Han Sans SC,思源黑体,Source Han Sans SC ExtraLight,思源黑体 ExtraLight:style=ExtraLight,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Medium.ttc: Source Han Sans,源ノ角ゴシック,Source Han Sans Medium,源ノ角ゴシック Medium:style=Medium,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Normal.ttc: Source Han Sans TC,思源黑體,思源黑體 Normal,Source Han Sans TC Normal:style=Normal,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Heavy.ttc: Source Han Sans TC,思源黑體,思源黑體 Heavy,Source Han Sans TC Heavy:style=Heavy,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Light.ttc: Source Han Sans TC,思源黑體,思源黑體 Light,Source Han Sans TC Light:style=Light,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Regular.ttc: Source Han Sans HW K,본고딕 HW,Source Han Sans HW K Regular,본고딕 HW Regular:style=Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Regular.ttc: Source Han Sans,源ノ角ゴシック,Source Han Sans Regular,源ノ角ゴシック Regular:style=Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-ExtraLight.ttc: Source Han Sans K,본고딕,Source Han Sans K ExtraLight,본고딕 ExtraLight:style=ExtraLight,Regular
```
```
$ fc-list | grep "Droid"
/usr/share/fonts/TTF/DroidSansGeorgian.ttf: Droid Sans Georgian:style=Regular
/usr/share/fonts/TTF/DroidSansMono.ttf: Droid Sans Mono:style=Regular
/usr/share/fonts/TTF/DroidSansJapanese.ttf: Droid Sans Japanese:style=Regular
/usr/share/fonts/TTF/DroidSansFallbackLegacy.ttf: Droid Sans Fallback:style=Regular
/usr/share/fonts/TTF/DroidSans.ttf: Droid Sans:style=Regular
/usr/share/fonts/TTF/DroidSerif-Regular.ttf: Droid Serif:style=Regular
/usr/share/fonts/TTF/DroidSans-Bold.ttf: Droid Sans:style=Bold
/usr/share/fonts/TTF/DroidSansHebrew-Bold.ttf: Droid Sans Hebrew:style=Bold
/usr/share/fonts/TTF/DroidSansArabic.ttf: Droid Sans Arabic:style=Regular
/usr/share/fonts/TTF/DroidSerif-BoldItalic.ttf: Droid Serif:style=Bold Italic
/usr/share/fonts/TTF/DroidNaskh-Regular-SystemUI.ttf: Droid Naskh Shift Alt:style=Regular
/usr/share/fonts/TTF/DroidSansTamil-Bold.ttf: Droid Sans Tamil:style=Bold
/usr/share/fonts/TTF/DroidKufi-Regular.ttf: Droid Arabic Kufi:style=Regular
/usr/share/fonts/TTF/DroidNaskh-Bold.ttf: Droid Arabic Naskh:style=Bold
/usr/share/fonts/TTF/DroidSansArmenian.ttf: Droid Sans Armenian:style=Regular
/usr/share/fonts/TTF/DroidSerif-Bold.ttf: Droid Serif:style=Bold
/usr/share/fonts/TTF/DroidSansTamil-Regular.ttf: Droid Sans Tamil:style=Regular
/usr/share/fonts/TTF/DroidNaskh-Regular.ttf: Droid Arabic Naskh:style=Regular
/usr/share/fonts/TTF/DroidSansEthiopic-Bold.ttf: Droid Sans Ethiopic:style=Bold
/usr/share/fonts/TTF/DroidSansHebrew-Regular.ttf: Droid Sans Hebrew:style=Regular
/usr/share/fonts/TTF/DroidSerif-Italic.ttf: Droid Serif:style=Italic
/usr/share/fonts/TTF/DroidSansThai.ttf: Droid Sans Thai:style=Regular
/usr/share/fonts/TTF/DroidKufi-Bold.ttf: Droid Arabic Kufi:style=Bold
/usr/share/fonts/TTF/DroidSansFallbackFull.ttf: Droid Sans Fallback:style=Regular
/usr/share/fonts/TTF/DroidSansFallback.ttf: Droid Sans Fallback:style=Regular
/usr/share/fonts/TTF/DroidSansEthiopic-Regular.ttf: Droid Sans Ethiopic:style=Regular
/usr/share/fonts/TTF/DroidSansDevanagari-Regular.ttf: Droid Sans Devanagari:style=Regular
```
```
$ fc-match sans-serif
DejaVuSans.ttf: "DejaVu Sans" "Book"
```
```
$ fc-match monospace
DejaVuSansMono.ttf: "DejaVu Sans Mono" "Book"
```

**Comment by oberon2007** [comment]
**journalctl** prints:
```
Dec 01 12:02:42 manjaro-deepin service/file-manager-backend[634]: .:0: Get thumbnail for "file:///home/bernhard/Desktop/deepin-terminal.desktop" failed: Cann't find generator for 'application/x-desktop'
Dec 01 12:02:42 manjaro-deepin service/file-manager-backend[634]: .:0: Get thumbnail for "file:///home/bernhard/Desktop/chromium.desktop" failed: Cann't find generator for 'application/x-desktop'
Dec 01 12:02:42 manjaro-deepin service/file-manager-backend[634]: .:0: Get thumbnail for "file:///home/bernhard/Desktop/deepin-terminal.desktop" failed: Cann't find generator for 'application/x-desktop'
```

**Comment by oberon2007** [comment]
This looks a bit similar to the thumbnails issue (https://github.com/fasheng/arch-deepin/issues/126)
But then it's also different in that in my case I get **Cann't find generator for 'application/x-desktop'**

**Comment by jouyouyun** [comment]
@oberon2007 , missing cursor theme: Deepin-Cursor, we has delete deepin-cursor-theme today, and deepin-icon-theme will provide cursor theme 'Deepin', please wait for updates.
Or you can modify the 'CursorTheme' in /usr/share/personalization/themes/Deepin/theme.ini to a existing theme.

**Comment by oberon2007** [comment]
Oh wow! That indeed solves it :D I am impressed that a slightly faulty theme.ini like that breakes personalization so completely, though ;)
Thanks a lot, Wen! Can I ask: Which packages need to be updated now? Just **deepin-icon-theme** ? Or will changes in **deepin-artwork-theme** and the gsettings be necessary, too?

**Comment by fasheng** [comment]
looks like pkg deepin-cursor-theme is missed in your system~



2015年12月1日 下午8:04, 下午8:04，在 Bernhard Landauer <notifications@github.com> 已写:

**Comment by oberon2007** [comment]
Yes. It definitely needs to be a dependency of **deepin-artwork-themes** because its absence breaks theming completely.

**Comment by oberon2007** [comment]
But then, as @jouyouyun says this will be solved by an update of **deepin-icon-theme** anyway ;)

**Comment by fasheng** [comment]
this is another topic, simply, deepin-cursor-theme will be removed and merged to deepin-icon-theme after Deepin beta1 released.

@felixonmars if this issue is caused by the missing deepin-cursor-theme pkg, please add it to group deepin :)



2015年12月2日 下午5:02, 下午5:02，在 Bernhard Landauer <notifications@github.com> 已写:

**Comment by gujralam** [comment]
Hi, 
I have installed arch and deepin desktop. However I do not see anything on the "Personalization" and "Default Applications" pages. These screens are completely blank.

Please find below output of various above commands

[gujralam@dhcppc2 ~]$ cat /usr/share/personalization/themes/Deepin/theme.ini
[Theme]
Id=Deepin
Name=Deepin
Name[en_GB]=Deepin
Name[en_US]=Deepin
Name[zh_CN]=Deepin
Name[zh_HK]=Deepin
Name[zh_TW]=Deepin

[Component]
GtkTheme=Orang
IconTheme=Flattr
CursorTheme=Adwaita
FontName=Source Han Sans SC
FontMono=DejaVu Sans Mono
FontSize=11
BackgroundFile=file:///usr/share/backgrounds/default_background.jpg
SoundTheme=LinuxDeepin

-------------------------------------------------------------------------------------------------------
[gujralam@dhcppc2 ~]$ ls /usr/share/themes
Adwaita       Clearlooks        Emacs         Mist         Redmond
AgingGorilla  Clearlooks-3.4    Esco          Natura       Simple
Artwiz-boxed  Clearlooks-Olive  HighContrast  Onyx         Syscrash
Atlanta       Crux              Industrial    Onyx-Citrus  ThinIce
Bear2         Deepin            Metabox       Orang
Bright        Default           Mikachu       Raleigh

-------------------------------------------------------------------------------------------------------
[gujralam@dhcppc2 ~]$ ls /usr/share/icons
Adwaita  Deepin-2014    default  Flattr Dark  hicolor       oxygen
Deepin   Deepin-Cursor  Flattr   gnome        HighContrast

-------------------------------------------------------------------------------------------------------
[gujralam@dhcppc2 ~]$ ls /usr/share/backgrounds
default_background.jpg  gnome
[gujralam@dhcppc2 ~]$ 
-------------------------------------------------------------------------------------------------------
[gujralam@dhcppc2 ~]$ fc-list | grep "Source Han Sans"
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Bold.ttc: Source Han Sans HW TC,思源黑體 HW,思源黑體 HW Bold,Source Han Sans HW TC Bold:style=Bold,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Bold.ttc: Source Han Sans SC,思源黑体,Source Han Sans SC Bold,思源黑体 Bold:style=Bold,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Regular.ttc: Source Han Sans HW SC,思源黑体 HW,Source Han Sans HW SC Regular,思源黑体 HW Regular:style=Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSansCN-Light.otf: Source Han Sans CN,思源黑体 CN,Source Han Sans CN Light,思源黑体 CN Light:style=Light,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSansCN-Heavy.otf: Source Han Sans CN,思源黑体 CN,Source Han Sans CN Heavy,思源黑体 CN Heavy:style=Heavy,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Medium.ttc: Source Han Sans K,본고딕,Source Han Sans K Medium,본고딕 Medium:style=Medium,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Normal.ttc: Source Han Sans SC,思源黑体,Source Han Sans SC Normal,思源黑体 Normal:style=Normal,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Normal.ttc: Source Han Sans,源ノ角ゴシック,Source Han Sans Normal,源ノ角ゴシック Normal:style=Normal,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Light.ttc: Source Han Sans,源ノ角ゴシック,Source Han Sans Light,源ノ角ゴシック Light:style=Light,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Heavy.ttc: Source Han Sans,源ノ角ゴシック,Source Han Sans Heavy,源ノ角ゴシック Heavy:style=Heavy,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Normal.ttc: Source Han Sans K,본고딕,Source Han Sans K Normal,본고딕 Normal:style=Normal,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Medium.ttc: Source Han Sans SC,思源黑体,Source Han Sans SC Medium,思源黑体 Medium:style=Medium,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Regular.ttc: Source Han Sans K,본고딕,Source Han Sans K Regular,본고딕 Regular:style=Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Bold.ttc: Source Han Sans HW SC,思源黑体 HW,Source Han Sans HW SC Bold,思源黑体 HW Bold:style=Bold,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-ExtraLight.ttc: Source Han Sans,源ノ角ゴシック,Source Han Sans ExtraLight,源ノ角ゴシック ExtraLight:style=ExtraLight,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Bold.ttc: Source Han Sans K,본고딕,Source Han Sans K Bold,본고딕 Bold:style=Bold,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSansCN-Bold.otf: Source Han Sans CN,思源黑体 CN,Source Han Sans CN Bold,思源黑体 CN Bold:style=Bold,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Bold.ttc: Source Han Sans TC,思源黑體,思源黑體 Bold,Source Han Sans TC Bold:style=Bold,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Regular.ttc: Source Han Sans HW,源ノ角ゴシック HW,Source Han Sans HW Regular,源ノ角ゴシック HW Regular:style=Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Bold.ttc: Source Han Sans,源ノ角ゴシック,Source Han Sans Bold,源ノ角ゴシック Bold:style=Bold,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Regular.ttc: Source Han Sans HW TC,思源黑體 HW,思源黑體 HW Regular,Source Han Sans HW TC Regular:style=Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Bold.ttc: Source Han Sans HW K,본고딕 HW,Source Han Sans HW K Bold,본고딕 HW Bold:style=Bold,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Medium.ttc: Source Han Sans TC,思源黑體,思源黑體 Medium,Source Han Sans TC Medium:style=Medium,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-ExtraLight.ttc: Source Han Sans TC,思源黑體,思源黑體 ExtraLight,Source Han Sans TC ExtraLight:style=ExtraLight,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Regular.ttc: Source Han Sans TC,思源黑體,思源黑體 Regular,Source Han Sans TC Regular:style=Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Light.ttc: Source Han Sans SC,思源黑体,Source Han Sans SC Light,思源黑体 Light:style=Light,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Heavy.ttc: Source Han Sans SC,思源黑体,Source Han Sans SC Heavy,思源黑体 Heavy:style=Heavy,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSansCN-ExtraLight.otf: Source Han Sans CN,思源黑体 CN,Source Han Sans CN ExtraLight,思源黑体 CN ExtraLight:style=ExtraLight,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSansCN-Medium.otf: Source Han Sans CN,思源黑体 CN,Source Han Sans CN Medium,思源黑体 CN Medium:style=Medium,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Regular.ttc: Source Han Sans SC,思源黑体,Source Han Sans SC Regular,思源黑体 Regular:style=Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Light.ttc: Source Han Sans K,본고딕,Source Han Sans K Light,본고딕 Light:style=Light,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Heavy.ttc: Source Han Sans K,본고딕,Source Han Sans K Heavy,본고딕 Heavy:style=Heavy,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Bold.ttc: Source Han Sans HW,源ノ角ゴシック HW,Source Han Sans HW Bold,源ノ角ゴシック HW Bold:style=Bold,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSansCN-Regular.otf: Source Han Sans CN,思源黑体 CN,Source Han Sans CN Regular,思源黑体 CN Regular:style=Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-ExtraLight.ttc: Source Han Sans SC,思源黑体,Source Han Sans SC ExtraLight,思源黑体 ExtraLight:style=ExtraLight,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Medium.ttc: Source Han Sans,源ノ角ゴシック,Source Han Sans Medium,源ノ角ゴシック Medium:style=Medium,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Normal.ttc: Source Han Sans TC,思源黑體,思源黑體 Normal,Source Han Sans TC Normal:style=Normal,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Heavy.ttc: Source Han Sans TC,思源黑體,思源黑體 Heavy,Source Han Sans TC Heavy:style=Heavy,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Light.ttc: Source Han Sans TC,思源黑體,思源黑體 Light,Source Han Sans TC Light:style=Light,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Regular.ttc: Source Han Sans HW K,본고딕 HW,Source Han Sans HW K Regular,본고딕 HW Regular:style=Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Regular.ttc: Source Han Sans,源ノ角ゴシック,Source Han Sans Regular,源ノ角ゴシック Regular:style=Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSansCN-Normal.otf: Source Han Sans CN,思源黑体 CN,Source Han Sans CN Normal,思源黑体 CN Normal:style=Normal,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-ExtraLight.ttc: Source Han Sans K,본고딕,Source Han Sans K ExtraLight,본고딕 ExtraLight:style=ExtraLight,Regular

------------------------------------------------------------------------------------------------------------------------
[gujralam@dhcppc2 ~]$ fc-list | grep "Droid" 
/usr/share/fonts/TTF/DroidSansGeorgian.ttf: Droid Sans Georgian:style=Regular
/usr/share/fonts/TTF/DroidSansMono.ttf: Droid Sans Mono:style=Regular
/usr/share/fonts/TTF/DroidSansJapanese.ttf: Droid Sans Japanese:style=Regular
/usr/share/fonts/TTF/DroidSansFallbackLegacy.ttf: Droid Sans Fallback:style=Regular
/usr/share/fonts/TTF/DroidSans.ttf: Droid Sans:style=Regular
/usr/share/fonts/TTF/DroidSerif-Regular.ttf: Droid Serif:style=Regular
/usr/share/fonts/TTF/DroidSans-Bold.ttf: Droid Sans:style=Bold
/usr/share/fonts/TTF/DroidSansHebrew-Bold.ttf: Droid Sans Hebrew:style=Bold
/usr/share/fonts/TTF/DroidSansArabic.ttf: Droid Sans Arabic:style=Regular
/usr/share/fonts/TTF/DroidSerif-BoldItalic.ttf: Droid Serif:style=Bold Italic
/usr/share/fonts/TTF/DroidNaskh-Regular-SystemUI.ttf: Droid Naskh Shift Alt:style=Regular
/usr/share/fonts/TTF/DroidSansTamil-Bold.ttf: Droid Sans Tamil:style=Bold
/usr/share/fonts/TTF/DroidKufi-Regular.ttf: Droid Arabic Kufi:style=Regular
/usr/share/fonts/TTF/DroidNaskh-Bold.ttf: Droid Arabic Naskh:style=Bold
/usr/share/fonts/TTF/DroidSansArmenian.ttf: Droid Sans Armenian:style=Regular
/usr/share/fonts/TTF/DroidSerif-Bold.ttf: Droid Serif:style=Bold
/usr/share/fonts/TTF/DroidSansTamil-Regular.ttf: Droid Sans Tamil:style=Regular
/usr/share/fonts/TTF/DroidNaskh-Regular.ttf: Droid Arabic Naskh:style=Regular
/usr/share/fonts/TTF/DroidSansEthiopic-Bold.ttf: Droid Sans Ethiopic:style=Bold
/usr/share/fonts/TTF/DroidSansHebrew-Regular.ttf: Droid Sans Hebrew:style=Regular
/usr/share/fonts/TTF/DroidSerif-Italic.ttf: Droid Serif:style=Italic
/usr/share/fonts/TTF/DroidSansThai.ttf: Droid Sans Thai:style=Regular
/usr/share/fonts/TTF/DroidKufi-Bold.ttf: Droid Arabic Kufi:style=Bold
/usr/share/fonts/TTF/DroidSansFallbackFull.ttf: Droid Sans Fallback:style=Regular
/usr/share/fonts/TTF/DroidSansFallback.ttf: Droid Sans Fallback:style=Regular
/usr/share/fonts/TTF/DroidSansEthiopic-Regular.ttf: Droid Sans Ethiopic:style=Regular
/usr/share/fonts/TTF/DroidSansDevanagari-Regular.ttf: Droid Sans Devanagari:style=Regular

------------------------------------------------------------------------------------------------------------------------
[gujralam@dhcppc2 ~]$ fc-match sans-serif
DejaVuSans.ttf: "DejaVu Sans" "Book"
------------------------------------------------------------------------------------------------------------------------
[gujralam@dhcppc2 ~]$ fc-match monospace
DejaVuSansMono.ttf: "DejaVu Sans Mono" "Book"

**Comment by gujralam** [comment]
fasheng sir,

any update on this issue.

I just love Deepin Desktop and require your support to resolve it.

Please help me

**Comment by felixonmars** [comment]
@fasheng deepin-icon-theme now includes the cursor theme, and bumped to [community-testing]

**Comment by jouyouyun** [comment]
@gujralam , please paste the following commands's output, thanks!
```shell
$ dbus-send --print-reply --dest=com.deepin.daemon.Appearance /com/deepin/daemon/Appearance com.deepin.daemon.Appearance.List string:"gtk"

$ dbus-send --print-reply --dest=com.deepin.daemon.Appearance /com/deepin/daemon/Appearance com.deepin.daemon.Appearance.List string:"icon"

$ dbus-send --print-reply --dest=com.deepin.daemon.Appearance /com/deepin/daemon/Appearance com.deepin.daemon.Appearance.List string:"cursor"

$ dbus-send --print-reply --dest=com.deepin.daemon.Appearance /com/deepin/daemon/Appearance com.deepin.daemon.Appearance.List string:"standardfont"

$ dbus-send --print-reply --dest=com.deepin.daemon.Appearance /com/deepin/daemon/Appearance com.deepin.daemon.Appearance.List string:"monospacefont"
```

**Comment by fasheng** [comment]
@gujralam Sorry for the trouble of DDE, it's still alpha version now. For the personalization issue, just install `deepin-cursor-theme` manually and then it will works fine. Or as felix said, use [community-testing] instead. Currently, [community-testing] is more stable than [community]. XD

**Comment by gujralam** [comment]
Hello sir,
Here is the output that you requested for. For all the commands we are getting a similar error.
Error org.freedesktop.DBus.Error.ServiceUnknown: The name com.deepin.daemon.Appearance was not provided by any .service files

****
As suggested, i will work on moving to community testing.

I must say I am a very BIG FAN of you for creating this awesome desktop environment. Many thanks and regards for your outstanding work. 
*****

    [gujralam@dhcppc2 ~]$ dbus-send --print-reply --dest=com.deepin.daemon.Appearance /com/deepin/daemon/Appearance com.deepin.daemon.Appearance.List string:"gtk"
    
    Error org.freedesktop.DBus.Error.ServiceUnknown: The name   com.deepin.daemon.Appearance was not provided by any .service files
    
    [gujralam@dhcppc2 ~]$ dbus-send --print-reply --dest=com.deepin.daemon.Appearance /com/deepin/daemon/Appearance com.deepin.daemon.Appearance.List string:"icon"
    
    Error org.freedesktop.DBus.Error.ServiceUnknown: The name com.deepin.daemon.Appearance was not provided by any .service files
    
    [gujralam@dhcppc2 ~]$ dbus-send --print-reply --dest=com.deepin.daemon.Appearance /com/deepin/daemon/Appearance com.deepin.daemon.Appearance.List string:"cursor"
    
    Error org.freedesktop.DBus.Error.ServiceUnknown: The name com.deepin.daemon.Appearance was not provided by any .service files
    
    [gujralam@dhcppc2 ~]$ dbus-send --print-reply --dest=com.deepin.daemon.Appearance /com/deepin/daemon/Appearance com.deepin.daemon.Appearance.List string:"standardfont"
    
    Error org.freedesktop.DBus.Error.ServiceUnknown: The name com.deepin.daemon.Appearance was not provided by any .service files
    
    [gujralam@dhcppc2 ~]$ dbus-send --print-reply --dest=com.deepin.daemon.Appearance /com/deepin/daemon/Appearance com.deepin.daemon.Appearance.List string:"monospacefont"
    
    Error org.freedesktop.DBus.Error.ServiceUnknown: The name com.deepin.daemon.Appearance was not provided by any .service files

**Comment by jouyouyun** [comment]
@fasheng , why?

**Comment by gujralam** [comment]
No luck deepin-icon-theme is already the latest one installed on my system

**Comment by felixonmars** [comment]
@jouyouyun The packages in [community-testing] is at latest git master, with many mentioned bugs fixed.

**Comment by fasheng** [comment]
@gujralam looks your `deepin-artwork-theme` and `deepin-daemon` is out of date, do you installed Deepin packages from [community]?

**Comment by gujralam** [comment]
yes sir. it was installed from the opensuse site

**Comment by fasheng** [comment]
@gujralam 
So that's the point, please remove OBS repository from
`/etc/pacman.conf` and update packages like this:

```sh
sudo pacman -R dde-dock-applets
sudo pacman -Syyuu
```

**Comment by fasheng** [comment]
Closed. For the latest theming issue to see https://github.com/fasheng/arch-deepin/issues/190.
