### ISSUE TITLE
无法设置网络

### ISSUE THREAD

**Issue by zhuzilinuser** [fasheng/arch-deepin#138]
用的是arch源的dde,但是无法设置网络，或者编辑。个性化设置无效。

Linux linuser 4.2.5-1-ARCH #1 SMP PREEMPT Tue Oct 27 08:13:28 CET 2015 x86_64 GNU/Linux

**Comment by fasheng** [comment]
网络功能正在重写，尚无编辑功能，预计两周后的 beta 版会实现该功能。个性化的问题，应该是缺少 deepin-cursor-theme 包导致的～



2015年12月2日 下午3:15, 下午3:15，在 "小竹" <notifications@github.com> 已写:

**Comment by zhuzilinuser** [comment]
了解～   个性化的问题已经解决，辛苦啦！

**Comment by felixonmars** [comment]
Patch merged upstream, should be in tomorrow's package set.

**Comment by felixonmars** [comment]
Should be fixed with community-testing/deepin-control-center 2.91.3-1.

**Comment by fasheng** [comment]
Well, the connection editing page is still in process.. I'm working hard for it those days.

**Comment by fasheng** [comment]
Solved in `deepin-control-center-2.91.6-1`,  `deepin-daemon-2.93.5.20151221-1`.
