### ISSUE TITLE
Can't find generator for 'application/x-desktop'

### ISSUE THREAD

**Issue by oberon2007** [fasheng/arch-deepin#140]
I keep getting this error and the desktop is broken, meaning no background, desktop icons or even window frames somtimes.
What can this mean?

**Comment by jouyouyun** [comment]
Means: cann't found thumbnail generator for 'application/x-desktop', just an error message

**Comment by felixonmars** [comment]
Please test with latest [community-testing] packages. This fixes all the desktop glitches here.

**Comment by oberon2007** [comment]
Thank you. I only realized this morning that you are publishing in -testing now ;)

**Comment by oberon2007** [comment]
Yes. error is gone now.
