### ISSUE TITLE
Is deepin-control-center-2.91.2.20151203-2 broken for anyone else?

### ISSUE THREAD

**Issue by brendengibson** [fasheng/arch-deepin#141]
Fresh install of deepin group from [community] repo has broken control center for me.

It will appear from the right side of the screen approximately 10 seconds after I click the dock icon for the control center, but will not allow me to move from the home screen or change any settings. From there I can sometimes get it to hide, but with the 10 second delay and occasionally artifacts are left on screen.

This is only happening when using lightdm. If I use startx the control center works normally but I lose the desktop background and the control center won't hide after being shown. I also notice that the battery dock applet is present using startx but not when using lightdm.

I proffer lightdm so that I get the greeter on boot.

Has anyone else seen this issue, or know how I can diagnose?

**Comment by oberon2007** [comment]
Is that in a virtual box? If so, see if turning off video-acceleration in the vb-settings helps!

**Comment by brendengibson** [comment]
This is not a virtual machine, but thanks for the suggestion!

**Comment by felixonmars** [comment]
I cannot reproduce here. Any thoughts @fasheng ?

**Comment by fasheng** [comment]
It's fine for me, too.

Could you reproiduce it with `gdm` and `xinit`? And how about the different of output of `killall dde-control-center; dde-control-center --show` with `lightdm`?

**Comment by brendengibson** [comment]
Sorry for the delay - looks like it's specific to LightDM, It works flawlessly with SDDM.

Has the network icon in the dock been removed in the Deepin 2015 packages?

**Comment by felixonmars** [comment]
No, the network icon on the dock works fine here.

**Comment by oberon2007** [comment]
Me neither! I don't get a network icon.

**Comment by felixonmars** [comment]
Hrm weird. Do you have networkmanager installed and running?

**Comment by oberon2007** [comment]
service is running, yes. connection is fine, too. Also everything displayed fine in control center.

**Comment by oberon2007** [comment]
On the official Deepin ISO I don't see an icon either!
![network_icon](https://cloud.githubusercontent.com/assets/11800714/11633308/e6011024-9d0a-11e5-8fa9-d59b55830378.png)

**Comment by fasheng** [comment]
network icon only available for efficient mode and claasic mode in dock..



2015年12月8日 上午12:49, 上午12:49，在 Bernhard Landauer <notifications@github.com> 已写:

**Comment by oberon2007** [comment]
Fixed for me with **deepin-dock 2.90.2-1**

**Comment by felixonmars** [comment]
@brendengibson Is the issue still present for you with version 3.0.1?
