### ISSUE TITLE
dde-lowpower overlay doesn't exit

### ISSUE THREAD

**Issue by felixonmars** [fasheng/arch-deepin#142]
When my battery is really low (4%) I see 8 dde-lowpower processes, and the display is covered by a black screen with a low power icon in the center. I cannot do anything, and the overlay doesn't exit even after I plug in my AC power. I had to switch to another VT and ran `killall dde-lowpower` to get my desktop back to normal.

**Comment by fasheng** [comment]
@jouyouyun Help ;)

**Comment by jouyouyun** [comment]
dde-daemon version? commit id?

**Comment by felixonmars** [comment]
dde-daemon at 107ce2cdb5ada3e5599d2bbe7b9c7f109801b68d
dde-session-ui at aa35bb8d4ddde97d1c39f752ae3c1a154ed2c30e

**Comment by jouyouyun** [comment]
ok, I will follow the bug, hoping to reproduce the problem.

**Comment by jouyouyun** [comment]
Please update dde-session-ui, the problem has been solved.

**Comment by felixonmars** [comment]
Sorry, I didn't get the chance to actually test it. I'm closing the issue now, and will re-open if it's still the same issue.
