### ISSUE TITLE
deepin-session-ui seems to crash on new ISOs

### ISSUE THREAD

**Issue by oberon2007** [fasheng/arch-deepin#144]
On my older install I have successfully updated to the new packages and everything works quite nicely.
But now on a freshly built ISO with simply groups **deepin** and **deepin-extra** installed there are some serious issues, obviously with **deepin-session-ui**:
**lightdm-deepin-greeter** doesn't launch on boot and I have to use startx. Then the desktop looks normal until I open any window. At that moment the background goes black, instead of the tray icons I see little black squares and the control center has a black border on the left side.
Mind: The exactly same behaviour I see when I use the official **Deepin alpha2** ISO and launch a **Deepin 2D** session!
On the Manjaro-ISO however this happens also in the normal Deepin session.
When I log out via control center I am back to tty - no greeter again.

**Nautilus** does not launch from the dock or the launcher. I can start it from the terminal but with errors:
```
$ nautilus
(nautilus:979): GLib-GObject-CRITICAL **: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
(nautilus:979): Gtk-WARNING **: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files
```
Maximize and minimize buttons or resize of windows is not working, only 'close' button is functional.
I would love to post **.xsession-errors**, but the file is not present, neither are xdg-user dirs.

Any ideas where to start? ;)

**Comment by oberon2007** [comment]
Some error messages from the dock:
```
Dec 06 00:52:56 manjaro-deepin com.deepin.daemon.Dock[521]: (dde-preload:1179): Gtk-WARNING **: cannot open display:
Dec 06 00:52:56 manjaro-deepin dbus-daemon[521]: Activated service 'com.deepin.daemon.Dock' failed: Process com.deepin.daemon.Dock exited with status 1
Dec 06 00:52:57 manjaro-deepin dbus-daemon[521]: Activating service name='com.deepin.daemon.Dock'
Dec 06 00:52:57 manjaro-deepin com.deepin.daemon.Dock[521]: Unable to init server: Could not connect: Connection refused
Dec 06 00:52:57 manjaro-deepin com.deepin.daemon.Dock[521]: (dde-preload:1187): Gtk-WARNING **: cannot open display:
Dec 06 00:52:57 manjaro-deepin dbus-daemon[521]: Activated service 'com.deepin.daemon.Dock' failed: Process com.deepin.daemon.Dock exited with status 1
```

**Comment by fasheng** [comment]
does other lightdm greeter works? are deepin daemon (dde-session-daemon) and window manager(deepin-wm or deepin-metacity) running?



2015年12月6日 上午7:55, 上午7:55，在 Bernhard Landauer <notifications@github.com> 已写:

**Comment by oberon2007** [comment]
```
$ deepin-wm

(deepin-wm:1043): GLib-GObject-CRITICAL **: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

** (deepin-wm:1043): ERROR **: Unable to get org.ayatana.bamf matcher: Error calling StartServiceByName for org.ayatana.bamf: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.ayatana.bamf exited with status 1
Trace/breakpoint trap (core dumped)
```

**Comment by oberon2007** [comment]
**deepin-metacity** can be launched and seems to work normally.

**Comment by oberon2007** [comment]
Partly solved by editing **.xinitrc** like here: https://bbs.archlinux.org/viewtopic.php?id=203899
The greeter-issue still persists...

**Comment by fasheng** [comment]
how about launch dde through lightdm-gtk-greeter/gdm/xinit?



2015年12月6日 下午6:59, 下午6:59，在 Bernhard Landauer <notifications@github.com> 已写:

**Comment by oberon2007** [comment]
I just found that lightdm service was not running. Still need to find out why, but obviously the problem seems not to be related to Deepin ;)
