### ISSUE TITLE
expose windows (compiz) still available?

### ISSUE THREAD

**Issue by oberon2007** [fasheng/arch-deepin#145]
Is this cool feature of Deepin 2014 still available in the new desktop?
![Image](https://a.fsdn.com/con/app/proj/manjaro-deepin/screenshots/1512_bl%C3%A4ttern.png)
I can't seem to find it. ... used to be **Super+Tab**

**Comment by felixonmars** [comment]
Compiz was not used in Deepin 2015, so it won't be available as far as I know.

**Comment by oberon2007** [comment]
I see. Maybe it can still be installed? The gsettings for compiz are still present in dde-desktop-schemas... Maybe just a leftover, though ;)

**Comment by felixonmars** [comment]
Yeah maybe, there's still deepin-compiz :)

**Comment by oberon2007** [comment]
I will try ;)
Just the question of dependencies: I'll try replacing **metacity-ubuntu** with **deepin-metacity**.
Is there anything to replace **gnome-settings-daemon**? Maybe covered by the new deepin pkgs anyway?

**Comment by felixonmars** [comment]
There is nothing depending on `gnome-settings-daemon` atm. @fasheng may want to share some light here :)

**Comment by oberon2007** [comment]
hm. yes please, @fasheng ! :)
Building **deepin-compiz** fails with
```
/usr/include/c++/5.2.0/bits/stl_map.h:688:9: note:   template argument deduction/substitution failed:
/build/deepin-compiz/src/compiz-0.9.99/plugins/opengl/src/programcache.cpp:162:70: note:   candidate expects 2 arguments, 1 provided
     cache.insert (std::make_pair (name, std::make_pair (program, it)));
                                                                      ^
plugins/opengl/CMakeFiles/opengl.dir/build.make:107: recipe for target 'plugins/opengl/CMakeFiles/opengl.dir/src/programcache.cpp.o' failed
make[2]: *** [plugins/opengl/CMakeFiles/opengl.dir/src/programcache.cpp.o] Error 1
CMakeFiles/Makefile2:7928: recipe for target 'plugins/opengl/CMakeFiles/opengl.dir/all' failed
make[1]: *** [plugins/opengl/CMakeFiles/opengl.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by fasheng** [comment]
deepin-compiz is out of date and can't build success based on the latest metacity(3.0+), so metacity-ubuntu 2.34.13 is still required for it. Or you could try the original compiz instead, it should works fine for Deepin 2015 packages.
