### ISSUE TITLE
GitHub stopped syncing from cr.deepin.io

### ISSUE THREAD

**Issue by felixonmars** [fasheng/arch-deepin#148]
All repos (except irc logs) are updated 3 days ago. There are more merged commits that are not present here. 

https://github.com/linuxdeepin/

**Comment by fasheng** [comment]
Fixing...

**Comment by felixonmars** [comment]
Would it be possible to fix in another day or two? Or I could switch to use the cr.deepin.io sources.

**Comment by fasheng** [comment]
cr.deepin.io is unstable and low bandwidth, please
just wait one more day to fix this.



2015年12月8日 上午8:56, 上午8:56，在 Felix Yan <notifications@github.com> 已写:

**Comment by felixonmars** [comment]
OK, thanks :)

**Comment by fasheng** [comment]
Fixed now.

**Comment by felixonmars** [comment]
Great, thanks a lot :P
