### ISSUE TITLE
dde-session-daemon  cpu占用一直 25

### ISSUE THREAD

**Issue by zhuzilinuser** [fasheng/arch-deepin#151]
![img_20151207_201806](https://cloud.githubusercontent.com/assets/12298476/11626717/edebbd10-9d1f-11e5-817c-b937eff9480e.jpg)
![img_20151207_201810](https://cloud.githubusercontent.com/assets/12298476/11626718/ee1e5fc2-9d1f-11e5-9646-b0a3f1c67174.jpg)

然后控制中心启动特别卡，无法操作

**Comment by zhuzilinuser** [comment]
还有一个就是控制面板的头像无法显示，但是用户里面可以显示。。

**Comment by fasheng** [comment]
deepin-daemon 和 deepin-control-center 的版本多少？

journalctl -f 有没有打印大量错误？在终端运行 'killall dde-session-daemon;/usr/lib/deepin-daemon/dde-session-daemon' 会不会异常退出？

另外首页用户头像的问题上游正在修复。



2015年12月7日 下午8:19, 下午8:19，在 kirigaya <notifications@github.com> 已写:

**Comment by fasheng** [comment]
如果安装了 deepin-screenshot，可以用快捷键 <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>a</kbd> 进行截图 ;)

**Comment by zhuzilinuser** [comment]
名称　　　： deepin-daemon
版本　　　： 2.93.1.20151202-1

名称　　　： deepin-control-center
版本　　　： 2.91.2.20151203-2

终端运行 'killall dde-session-daemon;/usr/lib/deepin-daemon/dde-session-daemon' 不会异常退出

**Comment by zhuzilinuser** [comment]
http://i5.tietuku.com/d74081a3d54fb82a.png

**Comment by zhuzilinuser** [comment]
今天我进行了plasma和一些字体的安装(https://linux.cn/article-3019-1.html),然后发现控制面板不卡了。感觉是不是字体的问题。

**Comment by fasheng** [comment]
这。。。你把今天 pacman 的 log 贴下吧

**Comment by zhuzilinuser** [comment]
[pacman.log.zip](https://github.com/fasheng/arch-deepin/files/55707/pacman.log.zip)

机房网络不稳定，有重复安装字体的步骤。

**Comment by zhuzilinuser** [comment]
执行了killall dde-session-daemon;/usr/lib/deepin-daemon/dde-session-daemon以后，点击蓝牙和声音都会卡死dde，终端也有错误的产生。安装plasma后不卡，一定是把这两个给补全了，尝试以后，恢复正常。
![deepinscreenshot20151211230942](https://cloud.githubusercontent.com/assets/12298476/11747141/81660e12-a05c-11e5-9114-7aba5e73b1fe.png)
![deepinscreenshot20151211230952](https://cloud.githubusercontent.com/assets/12298476/11747142/8197b6ce-a05c-11e5-9d28-ee4c8365ad8e.png)

**Comment by fasheng** [comment]
好的多谢，回头我到新装个 arch 看能否重现 :)
