### ISSUE TITLE
Latest dde-api installs to /lib

### ISSUE THREAD

**Issue by felixonmars** [fasheng/arch-deepin#153]
The systemd service was installed to `${DESTDIR}${libdir}` instead of `${DESTDIR}${PREFIX}${libdir}`. It would be great if this could be customized.

https://github.com/linuxdeepin/dde-api/commit/d580efb12658de9f734349cd70468130149ec35d#diff-b67911656ef5d18c4ae36cb6741b7965R72

**Comment by fasheng** [comment]
The patch was merged now. :)
https://cr.deepin.io/#/c/9444/

**Comment by felixonmars** [comment]
Implemented in 2.92.3.20151217-1.
