### ISSUE TITLE
dde-launcher eats 100% CPU and gigabytes of memory

### ISSUE THREAD

**Issue by felixonmars** [fasheng/arch-deepin#154]
I have to kill dde-launcher from time to time, as it's taking too much memory and CPU time. As you can see in the following screenshot, it eats 8GiB of ram :/

![2015-12-08-150505-8f56cb](https://cloud.githubusercontent.com/assets/1006477/11649743/2b4593e6-9dbd-11e5-8f02-74be15ed89cc.png)

**Comment by fasheng** [comment]
@dragondjf Help ;)

**Comment by felixonmars** [comment]
Not reproduced for quite some time, should have been fixed upstream.
