### ISSUE TITLE
Bluetooth applet doesn't fit in position when height changed

### ISSUE THREAD

**Issue by felixonmars** [fasheng/arch-deepin#156]
This often happens when there are more bluetooth devices appears (especially when hovered on the first time after startup), and the applet window will be updated in realtime and expanded over the lower boundary of the screen (or the upper boundary of the dock).

**Comment by fasheng** [comment]
Thanks, will report to the developer tomorrow.

**Comment by fasheng** [comment]
Solved now.
https://github.com/linuxdeepin/dde-control-center/commit/0c5221f81c2a25bd20536b9657e47877265088b9

**Comment by felixonmars** [comment]
Thanks a lot :)
