### ISSUE TITLE
deepin-notifications warnings

### ISSUE THREAD

**Issue by felixonmars** [fasheng/arch-deepin#157]
Running latest: https://github.com/linuxdeepin/deepin-notifications/commit/692640abb9bd1c3a74f686abbe2e9163a9e2020d

```
Dec 09 10:35:20 flygon.felixc.at org.freedesktop.Notifications[4122]: Xlib:  extension "NV-GLX" missing on display ":0".
Dec 09 10:35:20 flygon.felixc.at deepin-notifications[22408]: QObject::~QObject: Timers cannot be stopped from another thread
```

This happens 10s after the bubble expired.

**Comment by felixonmars** [comment]
Still present in 2.3.5.

**Comment by fasheng** [comment]
Same pacakge version, but here is fine. I run
```
notify-send -i notification-network-wireless-disconnected Test test
```
And journal got in 60s
```
Dec 30 10:33:55 fa-host deepin-notifications[4662]: Notify "notify-send" "notification-network-wireless-disconnected" "Test" "test" () QMap(("urgency", QVariant(uchar, 1))) -1
Dec 30 10:34:01 fa-host deepin-notifications[4662]: bubbleExpired
```

BTW: Qt is 5.5.1-6

**Comment by felixonmars** [comment]
I saw those two messages too, but the other two msgs in OP shows after 10s of that `bubbleExpired` msg.

**Comment by felixonmars** [comment]
The message `Xlib:  extension "NV-GLX" missing on display ":0".` is no longer displayed now. But the other QObject one is still here.

**Comment by fasheng** [comment]
@hualet Any idae?
