### ISSUE TITLE
daemon/network prints errors about speedStr

### ISSUE THREAD

**Issue by felixonmars** [fasheng/arch-deepin#160]
Disabling these messages would be better, if they do no harm...

```
daemon/network[4379]: .:0: not support to get device speedStr for device type 14
```

**Comment by felixonmars** [comment]
During startup of dde-session-daemon, this message got printed for many times (>50).

**Comment by fasheng** [comment]
Solved now. Try the latest commit for deepin-daemon. ;)

**Comment by felixonmars** [comment]
That's great. Thanks for info!
