### ISSUE TITLE
Possible memory leak in dde-session-daemon

### ISSUE THREAD

**Issue by felixonmars** [fasheng/arch-deepin#162]
It eats only 98M of memory on startup, but now it's 759M.

![2015-12-09-144112-ddc134](https://cloud.githubusercontent.com/assets/1006477/11678438/f8ba8dca-9e82-11e5-94a5-4e2c88725453.png)

**Comment by felixonmars** [comment]
This is after ~20h:
![2015-12-13-134731-315607](https://cloud.githubusercontent.com/assets/1006477/11765747/9b2f6916-a1a0-11e5-934e-cfa4e5ea3447.png)

**Comment by felixonmars** [comment]
Another ~11h later:
![2015-12-14-003835-6ff164](https://cloud.githubusercontent.com/assets/1006477/11768036/49e2ac84-a1fb-11e5-91ec-8c2e404faa5b.png)

**Comment by oberon2007** [comment]
Got something similar here but with **/usr/lib/deepin-daemon/deepin-file-manager-backend**
Happens immediately after startup before I even do anything else. Shortly after I took the screenshot MEM goes to 100% and the system becomes unresponsive and have to hard reset.
![deepinscreenshot20151223145413](https://cloud.githubusercontent.com/assets/11800714/11977759/0777606e-a986-11e5-8678-8d52d1337efa.png)

**Comment by fasheng** [comment]
Hmm, looks there is a correlation between them...

**Comment by oberon2007** [comment]
This problem is still present and quite serious :-/
For me it happens always immediately during login and it's always **/usr/lib/deepin-daemon/deepin-filemanager-backend** like in my screenshot. The system becomes completely overwhelmed. When I kill the first process on the list all is well and works fine again (had to do it from another tty lately because I could not do anything in the graphical session).
To me it looks like somehow related to the initialization of the session - maybe to do with the interaction startdde / deepin-daemon ??

**Comment by oberon2007** [comment]
I think it's interesting that later I never see this process again! Is is maybe just supposed to be killed and that doesn't happen for whatever reason? I guess this is maybe a different issue than the memory leak of the original here ...

**Comment by oberon2007** [comment]
Here is someone having the exact same issue as I experienced with **/usr/lib/deepin-daemon/deepin-file-manager-backend**: https://forum.manjaro.org/index.php?topic=30225.msg250212#msg250212
Any ideas about that meanwhile?

**Comment by fasheng** [comment]
Yes, all the golang daemon memory leak issues only occurred under gccgo. Of course it's the upstream code issue. Looks glibc and dbus go-bindings are highly suspicious objects.

Upstream already aware of the problems, but I'm not sure when to fix them...

**Comment by oberon2007** [comment]
I'm still gettings this behaviour of /usr/lib/deepin-daemon/deepin-file-manager-backend unfortunately with latest **deepin-file-manager 0.1.9-2** :(

**Comment by Notaduck** [comment]
Seeing the same thing here. my system is using 3 GB of ram right now.

**Comment by fasheng** [comment]
@notaduck deepin-daemon 3.0.16-3 has been rebuilt with Go and will fix the memory issue.
