### ISSUE TITLE
replaces / depends suggestions

### ISSUE THREAD

**Issue by oberon2007** [fasheng/arch-deepin#163]
For users updating from 2014 pkgs it appears to be useful to add:
**deepin-dock** replaces dde-dock-applets
and maybe also
**deepin-desktop** depends deepin-launcher (currently not a dependency of any pkg)

**Comment by felixonmars** [comment]
`dde-dock-applets` is already in replaces array of `deepin-control-center`. And I don't think `deepin-launcher` is a hard dependency of anything - but since there's an icon on the dock, maybe it's better to add it there?

**Comment by fasheng** [comment]
About `deepin-desktop`, `deepin-launcher` and other DDE packages, a simple dependency graphic looks like this(<- means depends):

```
startdde
  <- deepin-api
  <- deepin-daemon
  <- deepin-file-manager
  <- deepin-session-ui
  <- deepin-desktop
  <- deepin-dock
  <- deepin-launcher 
  <- deepin-wm-switcher
  
deepin-wm-switcher
  <- deepin-wm
  <- deepin-metacity
  
deepin-desktop, deepin-dock, deepin-launcher , deepin-control-center
  <- deepin-daemon

deepin-daemon
  <- deepin-api
```

Through some package may depends each other, I think keep them simply just is OK.

**Comment by felixonmars** [comment]
Hrm, it looks more like `->` to me :/

**Comment by oberon2007** [comment]
Since the launcher icon is defined in **deepin-desktop-schemas** that's maybe where the dependency should go then?

**Comment by felixonmars** [comment]
Arch has a policy against defining circular dependency, so I will have to look for some other ways...

**Comment by oberon2007** [comment]
not relevant any longer I guess.
