### ISSUE TITLE
Graphics freeze when using deepin-wm with osu! (wine'd)

### ISSUE THREAD

**Issue by felixonmars** [fasheng/arch-deepin#165]
I'm assuming this a problem of deepin-wm, since the same problem doesn't exist with deepin-metacity or mutter alone.

Launching osu! while deepin-wm being the window manager will result in a freezed graphical interface, the mouse cursor can move, but no GUI element will react or update. Killing osu! from another VT is the only way to get it back to normal.

Pkg versions:
community-testing/deepin-wm 0.91.4-1
multilib-testing/wine-staging 1.8rc3-2

**Comment by hexchain** [comment]
I have the same problem.
Syslog relevant lines: http://ix.io/mIM
Switched to tty2 and killed wineserver and osu.exe at around Dec 10 21:06:50.

**Comment by felixonmars** [comment]
Still present in 1.0.1.
