### ISSUE TITLE
No tray icon shown for Dropbox

### ISSUE THREAD

**Issue by felixonmars** [fasheng/arch-deepin#168]
The dropbox client always has an empty tray icon, and clicking works as expected.

community-testing/deepin-dock 2.90.2-1

**Comment by fasheng** [comment]
What's the package name of the dropbox client?

BTW: Thanks for your topics today. And I found it's always a show time for bugs when Deepin want to release a new version...

**Comment by felixonmars** [comment]
It's aur/dropbox 3.10.11-1.

I didn't test it too much for not tagged version, and suppress some bugs that are still under development until the next tagged version (and open them all at once if they are still not fixed at that time). This is why I always want to open many bug reports on new tagged version :P

**Comment by fasheng** [comment]
Thanks, it's just fine ;)

In upstream, the issues even out of control. XD

**Comment by felixonmars** [comment]
Sometimes the Dropbox icon shows after really long time, but I didn't find a stable way for this yet.

**Comment by oberon2007** [comment]
Sounds similar to [#174](https://github.com/fasheng/arch-deepin/issues/174) maybe?

**Comment by felixonmars** [comment]
Could be :P

**Comment by pavlanton** [comment]
Dropbox 3.12.5 work all time

**Comment by felixonmars** [comment]
Still present here with 3.0.1.

**Comment by felixonmars** [comment]
No longer present with 3.0.4. Thank you!
