### ISSUE TITLE
Latest dde-api doesn't build with Go 1.4.x

### ISSUE THREAD

**Issue by felixonmars** [fasheng/arch-deepin#169]
The `signal.Ignore` method was added since Go 1.5.

**Comment by hualet** [comment]
Pathetic...the DDE front end should be compiled with Qt 5.3+, but the Qt version we use is Qt 5.5. Now is the DDE back end :(

**Comment by felixonmars** [comment]
Sorry for the trouble :P

**Comment by felixonmars** [comment]
Fixed.
