### ISSUE TITLE
Latest deepin-desktop-base messed up systeminfo plugin

### ISSUE THREAD

**Issue by felixonmars** [fasheng/arch-deepin#170]
Type was included in Version string since this commit https://github.com/linuxdeepin/deepin-desktop-base/commit/862f3cfcb0f95a2d69567c7cb9ed55b877aa488d

This makes systeminfo plugin display "Desktop" twice:
![2015-12-11-111201-d9dade](https://cloud.githubusercontent.com/assets/1006477/11735062/1258271c-9ff8-11e5-948b-de81b7a15cf0.png)

**Comment by fasheng** [comment]
I'm not sure why they change it now, but we could use the previous commit for the latest background is required...

**Comment by felixonmars** [comment]
background is fine, this is just for the /etc/deepin-version file included in `deepin-daemon` package :)

**Comment by fasheng** [comment]
Well, looks Deepin Beta did not use deepin-desktop-base in github at all.

So we must do some hack for it :/

**Comment by felixonmars** [comment]
Fixed with https://github.com/linuxdeepin/deepin-desktop-base/commit/af086a257aafc81a854dfe7accd9e5600b849960
