### ISSUE TITLE
can't set wallpaper

### ISSUE THREAD

**Issue by zhuzilinuser** [fasheng/arch-deepin#173]
![20151211125026](https://cloud.githubusercontent.com/assets/12298476/11736150/c55db05e-a005-11e5-8c8b-52701c66a1c8.png)
![20151211125101](https://cloud.githubusercontent.com/assets/12298476/11736156/d934d684-a005-11e5-9e56-3307eecec0a5.png)

selete a photo to set wallpaper,but it just copy this file. dde-control-center not this wallpaper.

**Comment by zhuzilinuser** [comment]
![deepinscreenshot20151211232302](https://cloud.githubusercontent.com/assets/12298476/11747434/2d07069e-a05e-11e5-9a21-4468e5fdfcd5.png)

**Comment by pavlanton** [comment]
In Nautilus "Set desctop wallpaper". Not work but after rebooting add picture )))

**Comment by zhuzilinuser** [comment]
can work in the first few weeks, but  can't do it now.
