### ISSUE TITLE
pamac-tray icon not showing with latest pkgs

### ISSUE THREAD

**Issue by oberon2007** [fasheng/arch-deepin#174]
Something seems to have been changed about tray icons... **pamac-tray**, [the manjaro package manager](https://github.com/manjaro/pamac) used to show fine in Deepin tray but since lates pkg-updates the icon is gone.
Do you have any advice for me where to look for the reason?
@philmmanjaro any idea, maybe?

**Comment by philmmanjaro** [comment]
Is the daemon or the tray process running?

**Comment by oberon2007** [comment]
pamac-tray process is running. No daemon. How would I launch that one?
There's more stuff that looks not normal when running pamac-manager (in the live-environment):
When I try to install/uninstall a package from the pkg-manager it gives "Authentication failed".
Clicking on 'Preferences' in the Settings Menu has no effect.
And with pamac-try again:
```
$ pamac-tray --gapplication-service
Failed to register: Unable to acquire bus name 'org.manjaro.pamac.tray'
```

**Comment by philmmanjaro** [comment]
Then some is wrong on your end in regard of authentication. Check if any polkit daemon is running:
```
[phil@manjaro ~]$ ps -ef | grep polkit | grep -v grep
polkitd    506     1  0 10:19 ?        00:00:00 /usr/lib/polkit-1/polkitd --no-debug
phil       919   671  0 10:19 ?        00:00:00 /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
```

**Comment by oberon2007** [comment]
OK. So the authentication-agent was not running because the .desktop file of the authentication-agent in autostart only works after you delete ``OnlyShowIn=GNOME;`` ;)
That solves the issues of pamac-pamager.
Unfotunately no difference for the tray...
How about the daemon? I tried launching it manually with ``sudo pamac-daemon`` but doesn't change anything either.

**Comment by philmmanjaro** [comment]
So what is the actual problem? **pamac-tray** doesn't show in the dock or it doesn't work?

**Comment by oberon2007** [comment]
I get no tray icon and can only launch pamac-manger with the launcher or from terminal. I don't know if the daemon is running. How can I check that or start it?

**Comment by philmmanjaro** [comment]
Please check the **systemd** and **dbus1** service files:
```
pamac /usr/lib/systemd/system/pamac.service
pamac /usr/share/dbus-1/system-services/
pamac /usr/share/dbus-1/system-services/org.manjaro.pamac.service
```

**Comment by oberon2007** [comment]
Icon issue seems solved with latest dock-update. I have opened another issue for the polkit not started.

**Comment by oberon2007** [comment]
Unfortunately the icon disappears again after relogging...

**Comment by oberon2007** [comment]
restarting dde-dock brings the icon back.

**Comment by philmmanjaro** [comment]
Hmm, crazy issue then ...

**Comment by oberon2007** [comment]
It's looking kind of random at the moment and I was not really able to nail down a reproducable situation for the issue. I suspect that when it happens also the notification for available language packs gets "swallowed" - so maybe that means that no icons at all are displayed maybe. In any case it appears to be an issue of **deepin-dock**.

**Comment by pavlanton** [comment]
Dropbox icon and pamac-tray and multitasking view work fine Arch-linux + deepin

**Comment by oberon2007** [comment]
Sometimes, yes. But not reliably! When it doesn't I have to ``pkill dde-dock`` and when it restarts it works again. Sometimes the issue is triggered by relogging.

**Comment by oberon2007** [comment]
This has not happened in a while now. Closing :)
