### ISSUE TITLE
Manual IP  question

### ISSUE THREAD

**Issue by zhuzilinuser** [fasheng/arch-deepin#175]
![deepinscreenshot20151211235248](https://cloud.githubusercontent.com/assets/12298476/11748249/5837d01a-a062-11e5-8f2d-5975d6fe49c6.png)

I set IP 010.010.x.x ,but It not. will change to 100.100.x.x

**Comment by sbwtw** [comment]
maybe your ip is set to  10.10.0.0 ?  its not a valid address

**Comment by fasheng** [comment]
Sorry for the trouble, I think it is caused by the IP widget, will fix it later.



2015年12月11日 下午11:56, 下午11:56，在 kirigaya <notifications@github.com> 已写:

**Comment by felixonmars** [comment]
@sbwtw Actually it _could_ be a valid address. For example, everything between 10.8.0.1 and 10.11.255.254 is a valid address for 10.8.0.0/14.

**Comment by fasheng** [comment]
Solved in `deepin-control-center-2.91.6-1`,  `deepin-daemon-2.93.5.20151221-1`.
