### ISSUE TITLE
polkit-gnome not started

### ISSUE THREAD

**Issue by oberon2007** [fasheng/arch-deepin#176]
I realize that polkit-gnome is not being started any more unless I manually place the .desktop file in autostart. https://github.com/fasheng/arch-deepin/issues/174#issuecomment-163978625
It was not like that until the recent packages.
Is this the way it is intended or is something not working as it should at the moment?

**Comment by felixonmars** [comment]
Fixed with deepin-daemon 2.93.4.20151211-2.

**Comment by felixonmars** [comment]
Hrm, on a second thought, I am re-opening to see if @fasheng has different ideas. Currently I put a Deepin-only desktop file into /etc/xdg/autostart. Would still be great if this could be made a dbus-activation service, though.

**Comment by fasheng** [comment]
@felixonmars 
I agree, it's a good style to launch policykit-gnome through the .desktop file for it do not provide any DBus service.

**Comment by oberon2007** [comment]
Thank you @felixonmars Working as expected now.
