### ISSUE TITLE
Can't switch keyboard layout

### ISSUE THREAD

**Issue by pavlanton** [fasheng/arch-deepin#177]
Cant change language english-russian-hebrew. At the keyboard layout it's chenged but on write not. Thanx.

**Comment by pavlanton** [comment]
16:11:39 arch-anton dde-osd[1729]: Unsupported return type 65 QPixmap in method "grab"

**Comment by fasheng** [comment]
Sorry for the trouble.
So you mean changing keyboard layout to `Russian (Czech, phonetic)` not works. We will debug it soon.

**Comment by fasheng** [comment]
OK, this is caused by the block gsettings signals in gccgo, will be fixed after `go-gir-generator` updated.

**Comment by pavlanton** [comment]
Thank you. Wait )))

**Comment by fasheng** [comment]
We use the latest `go-gir-generator` now, and some related issues were solved. But looks the keybord layout issue still there, so need more debugging later.

**Comment by pavlanton** [comment]
Not work ((

**Comment by adderly** [comment]
Is there a workaround for this problem? A registered a key combination to change the layout, y add them to the list. But when i execute the key combination, the list gets cleared up. It's like it does not persist the changes.

**Comment by fasheng** [comment]
Yes, there is. But sadly, the workaround works not well :(

**Comment by pavlanton** [comment]
After Kill process dde-session-daemon..... Work

**Comment by omninonsense** [comment]
Hello!

Is this related to general keyboard layout switching, or only for certain edge cases? I'm experiencing the same issue with `en_GB` (**English (United Kingdom)**) and `hr_HR` (**Croatian**) layouts, so it might be related to certain languages?

Also, is this an upstream issue or an issue with the package specifically (maybe I can help somehow if it's the latter :smile:)?

**Comment by fasheng** [comment]
It's the gccgo issue for gsettings, it works in upstream for we hacked the go code which is not a general way, and we are searching for a better solution now~

**Comment by fasheng** [comment]
See https://github.com/fasheng/arch-deepin/issues/185
