### ISSUE TITLE
Highlighted item on dock's task bar has a significant delay when switching windows

### ISSUE THREAD

**Issue by felixonmars** [fasheng/arch-deepin#178]
The current active window (group) is shown as highlighted on the dock's task bar. However, when switching windows, it often takes more than 1 second for the new (now active) item to be shown as highlighted and the old one reverted to normal.

**Comment by fasheng** [comment]
Yes, I use the `Efflicient mode`, the highlight item changed is a little delay. And the more the applications opened, the longer the delay time.

**Comment by felixonmars** [comment]
Oh, I forgot to mention that I am also using `Efficient mode`. Same issue for `Classic mode` though.
