### ISSUE TITLE
right-click -> "open with ... Others" on Desktop not working

### ISSUE THREAD

**Issue by oberon2007** [fasheng/arch-deepin#179]

**Comment by felixonmars** [comment]
+1 reproduced here.

**Comment by oberon2007** [comment]
fixed.

**Comment by oberon2007** [comment]
My bad, sorry. Only opening with the listed applications works. 'Others' is still broken.

**Comment by oberon2007** [comment]
fixed with **deepin-nautilus-properties-3.14.3-1**. Thank you!
