### ISSUE TITLE
Disable deepin-menu syslogs when compiling

### ISSUE THREAD

**Issue by fasheng** [fasheng/arch-deepin#180]
Please use `qmake-qt5 DEFINES+=QT_NO_DEBUG_OUTPUT` in deepin-menu/PKGBUILD instead to turn off `qDebug()`.

**Comment by felixonmars** [comment]
Updated with deepin-menu 2.90.2-2.

**Comment by fasheng** [comment]
Thanks. Forgot checking the exsiting issues just now :P
