### ISSUE TITLE
Repeate items for the default timezone

### ISSUE THREAD

**Issue by pavlanton** [fasheng/arch-deepin#183]
![deepinscreenshot20151223214947](https://cloud.githubusercontent.com/assets/3049011/11977642/80930082-a9bf-11e5-9b2c-5f7c5ea9835d.png)

**Comment by pavlanton** [comment]
https://github.com/linuxdeepin/dde-daemon/blob/release/3.0/timedate/deepin_list.go rows 13-14

**Comment by fasheng** [comment]
Looks caused by the gsettings issue, too.

**Comment by fasheng** [comment]
Solved now.

**Comment by fasheng** [comment]
@jouyouyun Help;)
