### ISSUE TITLE
Bug dde-session-daemon CPU and memory

### ISSUE THREAD

**Issue by pavlanton** [fasheng/arch-deepin#184]
Dec 16 23:28:18 arch-anton com.deepin.daemon.helper.Backlight[409]: set_backlight to 0.836713(784) (driver:/sys/devices/pci0000:00/0000:00:02.0/drm/card0/card0-eDP-1/intel_backlight)
Dec 16 23:28:18 arch-anton com.deepin.daemon.helper.Backlight[409]: set_backlight to 0.836713(784) (driver:/sys/devices/pci0000:00/0000:00:02.0/drm/card0/card0-eDP-1/intel_backlight)
Dec 16 23:28:18 arch-anton com.deepin.daemon.helper.Backlight[409]: set_backlight to 0.836713(784) (driver:/sys/devices/pci0000:00/0000:00:02.0/drm/card0/card0-eDP-1/intel_backlight)
Dec 16 23:28:18 arch-anton com.deepin.daemon.helper.Backlight[409]: set_backlight to 0.836713(784) (driver:/sys/devices/pci0000:00/0000:00:02.0/drm/card0/card0-eDP-1/intel_backlight)
Dec 16 23:28:18 arch-anton com.deepin.daemon.helper.Backlight[409]: set_backlight to 0.836713(784) (driver:/sys/devices/pci0000:00/0000:00:02.0/drm/card0/card0-eDP-1/intel_backlight)
Dec 16 23:28:18 arch-anton com.deepin.daemon.helper.Backlight[409]: set_backlight to 0.836713(784) (driver:/sys/devices/pci0000:00/0000:00:02.0/drm/card0/card0-eDP-1/intel_backlight)
Dec 16 23:28:18 arch-anton com.deepin.daemon.helper.Backlight[409]: set_backlight to 0.836713(784) (driver:/sys/devices/pci0000:00/0000:00:02.0/drm/card0/card0-eDP-1/intel_backlight)

And this not end )))) 4 hour of cyclde

**Comment by pavlanton** [comment]
not fixed

**Comment by fasheng** [comment]
Maybe the same with https://github.com/fasheng/arch-deepin/issues/162.
