### ISSUE TITLE
GSettings signal blocked in gccgo under archlinux

### ISSUE THREAD

**Issue by fasheng** [fasheng/arch-deepin#185]
This will caused many setting issues in control center and dock.

Looks [go-gir-generator](https://github.com/linuxdeepin/go-gir-generator) is ready now, let's use it and will fix such issues.

https://github.com/fasheng/arch-deepin/issues/227
https://github.com/fasheng/arch-deepin/issues/177
https://github.com/fasheng/arch-deepin/issues/120

**Comment by felixonmars** [comment]
Updated in today's package set ([community-testing])

**Comment by fasheng** [comment]
A new workaround will coming, let's have a see..

**Comment by fasheng** [comment]
Good news, the patch was merged to gccgo now, let's wait for the new release of gcc :)
https://go-review.googlesource.com/#/c/18883/

**Comment by oberon2007** [comment]
Excuse me, could you explain to me which package(s) exactly will be the crucial update for Deepin? I am preparing another release and would like to time it accordingly ;) **gcc-go**? Or another update of **gcc* (this one just got updated Feb 22, but that was prior to the commit you reference here)...
Thank you! :)

**Comment by fasheng** [comment]
gcc-go just use the same PKGBUILD with gcc, and it will sync the source to gcc regularly. i'm not sure when the patch will be merged to gcc, too :/

**Comment by oberon2007** [comment]
Ok. Now I understand, thank you :)
