### ISSUE TITLE
After update of system launcher dont work

### ISSUE THREAD

**Issue by pavlanton** [fasheng/arch-deepin#186]
Dec 17 10:56:54 arch-anton systemd-coredump[1195]: Process 1183 (dde-launcher) of user 1000 dumped core.
                                                   
                                                   Stack trace of thread 1183:
                                                   #0  0x00007fc2b5965d20 _ZN10QByteArray7replaceEPKciS1_i (libQt5Core.so.5)
                                                   #1  0x000000000042bfcb n/a (dde-launcher)
                                                   #2  0x000000000042c486 n/a (dde-launcher)
                                                   #3  0x000000000042d559 n/a (dde-launcher)
                                                   #4  0x000000000042b65a n/a (dde-launcher)
                                                   #5  0x000000000042788

**Comment by pavlanton** [comment]
DBus.Error.ServiceUnknown:The name com.deepin.store.Api was not provided by any .service files
Dec 17 11:06:29 arch-anton kernel: dde-launcher[1455]: segfault at 7ffc56483ff0 ip 00007f6210a0ad20 sp 00007ffc56483fd0 error 6 in libQt5Core.so.5.5.1[7f621095e000+4c3000DBus.Error.ServiceUnknown:The name com.deepin.store.Api was not provided by any .service files
Dec 17 11:06:29 arch-anton kernel: dde-launcher[1455]: segfault at 7ffc56483ff0 ip 00007f6210a0ad20 sp 00007ffc56483fd0 error 6 in libQt5Core.so.5.5.1[7f621095e000+4c3000

**Comment by pavlanton** [comment]
Time zone not fix. Keyboard layout not fix.

**Comment by fasheng** [comment]
Thanks for the report.

But it works for me. And I test the the latest commit in git repo, it works, too. (I use the [community] but could not upgrade now for the network issue).

@felixonmars, have you encountered such problem?

**Comment by felixonmars** [comment]
No, I never got similar issues here :/

**Comment by pavlanton** [comment]
Ok. Thanks. Not other on this moment. Corner navigation not work after 5-10 minets for control panel. But that was been

**Comment by felixonmars** [comment]
dde-control-panel takes 100% CPU and doesn't react to either mouse action or dbus messages after a certain period of time. This has been a problem here as well since the very beginning of packages in [community].

**Comment by fasheng** [comment]
@pavlanton How about now, does `deepin-launcher 2.90.4.20151221-1` broken again?

**Comment by pavlanton** [comment]
Thanks all work. what about layout??? Thank you for your works. Good system. i like it.
