### ISSUE TITLE
Arch Lnux - gcc/libs confilct with gcc/libs-multilib

### ISSUE THREAD

**Issue by MinaTheLoli** [fasheng/arch-deepin#187]
Actual there are some conflicts with the gcc and gcc multilibs

**Comment by oberon2007** [comment]
You don't need **gcc**.
I have only installed:
```
gcc-go 5.3.0-2
gcc-libs-multilib 5.3.0-2
gcc-multilib 5.3.0-2
```

**Comment by MinaTheLoli** [comment]
thats strange cause pacman wants thet gcc multilib gets replaced with gcc

**Comment by felixonmars** [comment]
Is your mirror up-to-date? There was some inconsistency between the normal and multilib flavor of gcc series, and was fixed after several hours. Please try to upgrade again, or maybe look for a new mirror.

**Comment by felixonmars** [comment]
BTW, if you have [community-testing] enabled, you don't need to have gcc-go installed anymore since libgo has been moved into gcc-libs/gcc-libs-multilib.

**Comment by MinaTheLoli** [comment]
updated my mirrors but its still in conflict

**Comment by oberon2007** [comment]
@MinaTheLoli just confirm the removal of **gcc-libs-multilib** as pacman suggests, then you should be fine.
@felixonmars manjaro repos automatically sync to [community]. I can copy over [community-testing] manually. Are you going to release them in the immediate future?

**Comment by MinaTheLoli** [comment]
i need the multilibs for my gcc multilib for many of my lib32 libs

**Comment by oberon2007** [comment]
Sorry, @MinaTheLoli my other comment was rubbish. I already deleted that...

**Comment by oberon2007** [comment]
@MinaTheLoli I see no deepin packages that would depend on **gcc-libs** here, so I don't see why pacman would want to install that. What is the output of your ``yaourt -S --depends gcc-libs``?

**Comment by MinaTheLoli** [comment]
u want the whole output?

**Comment by oberon2007** [comment]
see above. edited ;)

**Comment by MinaTheLoli** [comment]
nothing..... thats very strange

**Comment by felixonmars** [comment]
@oberon2007 Yes, only waiting for a normal signoff process.

**Comment by MinaTheLoli** [comment]
again, same gcc problem, idk whats the problem

**Comment by MinaTheLoli** [comment]
nvm after an system update teh gcc problem was fixed :)

**Comment by oberon2007** [comment]
I see: The problem **does** exist in [community-testin]: Some new packages depend on **gcc-libs>=5.3.0-3** For example [deepin-api](https://www.archlinux.org/packages/community-testing/x86_64/deepin-api/)

**Comment by oberon2007** [comment]
Maybe this is solved when the whole system is updated to [community-testing]. I cannot verify that, I was just trying to install all the new deepin packages from testing - this doesn't work out obviously ;)

**Comment by felixonmars** [comment]
Yes. The new deepin package set requires new gcc-libs, and I'm going to hold them for a while until their Deepin -> deepin rename settled down.

**Comment by pavlanton** [comment]
https://bbs.archlinux.org/viewtopic.php?id=150344



You're doing it wrong: Once you install ONE of the -multilib compiler packages, you need to use all of them instead of the core packages. Everything else is not supported:

gcc-ada-multilib
gcc-fortran-multilib
gcc-go-multilib
gcc-libs-multilib
gcc-multilib
gcc-objc-multilib
libtool-multilib

**Comment by oberon2007** [comment]
I know. I'm not doing anything wrong, I'm just waiting until all the gcc packages are moved to [community] before that I have to download and install every single package manually ... ;)

**Comment by felixonmars** [comment]
All related packages moved to stable repos.
