### ISSUE TITLE
no sound settings available

### ISSUE THREAD

**Issue by oberon2007** [fasheng/arch-deepin#188]
Sound is working fine on my system and I can adjust the settings without problem with **pavucontrol**.
However the sound tab in my control center is completely empty. The dock has a working volume control but the line for "device" is an empty line.
```
Card: Intel Atom Processor Z36xxx/Z37xxx Series High Definition Audio Controller
driver: snd_hda_intel
```

**Comment by oberon2007** [comment]
Well, for ominous reasons this problem has disappeared ;)
Closing.

**Comment by misterch0c** [comment]
Same for me, it's either empty or the sound tab makes the menu crash

**Comment by fasheng** [comment]
Could you show the snapshot of **Configuration** page in pavcontrol? I remember we fixed a  panic issue for the profile is Off in pulseaudio, maybe that's the point.

**Comment by fasheng** [comment]
@iceyer Help ;)

**Comment by Iceyer** [comment]
@fasheng 
here is some fix about this issue：

https://cr.deepin.io/#/c/9133/

and some task in tower:
https://tower.im/projects/715dbdd34f694ea08f6de7888b7ffd7d/todos/6c9b91a796a04e5281b3d8c249b069a8/
https://tower.im/projects/715dbdd34f694ea08f6de7888b7ffd7d/todos/4df72cff2d5a47ef827bbef5de27f528/
https://tower.im/projects/715dbdd34f694ea08f6de7888b7ffd7d/todos/f455a1712d1a4f68afe72a6e32178933/

in fact, there is some design problem about sound module, it hard to fix before refacter  a new sound module.

**Comment by fasheng** [comment]
Got it, thanks for the hard work~

**Comment by felixonmars** [comment]
No longer reproducible here. @oberon2007 please test again :)

**Comment by oberon2007** [comment]
fixed. Thank you.
