### ISSUE TITLE
Theming broken for upstream changed the name from Deepin to deepin

### ISSUE THREAD

**Issue by oberon2007** [fasheng/arch-deepin#190]
Updating to the latest packages in [community-testing] breaks the theming for me.
I have since removed all custom manjaro packages and replaced by latest arch-deepin pkgs, I've removed the whole folders **/usr/share/glib-2.0/schemas**, **/usr/share/themes**, **/usr/shar/personalization**, **~/.local/share/personalization** and reinstalled all packages owning the contents to no avail.
One bug I have found is in /usr/share/glib-2.0/schemas/com.deepin.dde.appearance.gschemas.xml** the background-image needs to still be changed to the new name **deepin_**default_background.jpg
This should definitely be fixed, @jouyouyun !
But that alone doesn't solve my issue...

**Comment by oberon2007** [comment]
I think I found the reason: deepin-icon-theme obviously still installs the icons to **/usr/share/icons/Deepin** instead of **deepin** which is used in the newest glib-settings!
Renaming the folder seems to solve my problem here.

**Comment by oberon2007** [comment]
Also it looks like in case you have been using the default theme when updating you will need to manually delete **~/.config/dconf/user** - Not sure how to resolve this by package update ...

**Comment by fasheng** [comment]
With the latest packages in [community], we still need do something manually to restore the themes.

`rm -rf ~/.local/share/personalization/`
or
`sed 's/Deepin/deepin/g' ~/.local/share/personalization/themes/Custom/theme.ini`

And re-enter the `Appearance` module, it should works then.

**Comment by oberon2007** [comment]
In certain case it will also be necessary to delete ``~/.config/dconf/user`` ;)
