### ISSUE TITLE
Sound Plugin not handling output profiles.

### ISSUE THREAD

**Issue by beanaroo** [fasheng/arch-deepin#192]
I have a single, enabled sound card so I am not sure but this could be related to issue #158.

On the Analog Stereo Duplex (Pulseaudio default), volume plugin works but does not display other outputs. In my case, I had not Analog plugged in, I have HDMI plugged in:
![deepin-sound-01](https://cloud.githubusercontent.com/assets/1748909/11917623/407a0dd0-a774-11e5-8e69-b4d98c4ba1d5.png)

I have to install and use pavumixer to change from Analog output to HDMI output. Afterwards, the volume plugin, stops working:
![deepin-sound-02](https://cloud.githubusercontent.com/assets/1748909/11917634/79c72442-a774-11e5-8b13-9bad89c4e9c3.png)

Here is a list of profiles offered, all of them break the plugin like above except for Analog Stereo Duplex.
![deepin-sound-03](https://cloud.githubusercontent.com/assets/1748909/11917643/c44f567e-a774-11e5-80c1-c536441d022b.png)

**Comment by fasheng** [comment]
@snyh Help ;)
