### ISSUE TITLE
[deepin-artwork-themes] default background name

### ISSUE THREAD

**Issue by oberon2007** [fasheng/arch-deepin#193]
@felixonmars , the PKGBUILD now installs the default background as **deepin_default_background.jpg** while [theme.ini](https://github.com/linuxdeepin/deepin-artwork-themes/blob/master/themes/deepin/theme.ini#L17) is pointing to **default_background.jpg**

**Comment by fasheng** [comment]
I think it's just OK for we already renamed the background file `/usr/share/backgrounds/deepin_default_background.jpg` ;)

**Comment by oberon2007** [comment]
Yes you did. But as I say: **theme.ini** is pointing to **default_background.jpg** and the installed file is called **deepin_default_background**

**Comment by fasheng** [comment]
I see. Looks we gave a patch to **deepin-artwork-themes/theme.ini** but forgot the **deepin-desktop-schemas/99_deepin-default-gsettings.gschema.override**.

Here is the content in my machine:
```
$ cat /usr/share/personalization/themes/deepin/theme.ini
BackgroundFile=file:///usr/share/backgrounds/deepin_default_background.jpg
```
```
$ cat /usr/share/glib-2.0/schemas/99_deepin-default-gsettings.gschema.override
[org.gnome.desktop.background]
show-desktop-icons=false
picture-uri='file:///usr/share/backgrounds/default_background.jpg'
picture-options='zoom'
```
@felixonmars

**Comment by felixonmars** [comment]
I think I need some more info here.

We have specified the `picture-uri` twice in this file:

```
[org.gnome.desktop.background]
show-desktop-icons=false
picture-uri='file:///usr/share/backgrounds/default_background.jpg'
picture-options='zoom'
```

and 

```
[com.deepin.wrap.gnome.desktop.background]
primary-color='#000000'
secondary-color='#023c88'
picture-uri='file:///usr/share/backgrounds/deepin_default_background.jpg'
```

Are both of them necessary? If I understand it correctly, the default GNOME desktop settings will be overriden if we set it for `org.gnome.desktop.background`, so why we need com.deepin.wrap etc?

**Comment by fasheng** [comment]
@felixonmars 
Well, I grep the wrong `picture-uri` ...

So, yes, for this topic, we already patched all the related packages. And things works fine if don't care the broken `deepin-artwork-themes` which rename `Deepin` to `deepin`.

And for `picture-url` in `org.gnome.desktop.background`.  It's better give it a right value, too(at first I forgot). The origianl gnome-shell/mutter just use them. 

@oberon2007 Maybe the `theme.ini` is wrong in your machine?

**Comment by oberon2007** [comment]
I have no problems here anyway because I use custom packages **deepin-artwork-themes-manjaro** and **deepin-desktop-schemas-manjaro** and I install the default background from a different wallpaper package anyway.
I just wanted to let you know about what looks like a mistake to me when I look at your packages **deepin-artwork-themes** and  **deepin-desktop-schemas** :)

**Comment by fasheng** [comment]
I see. I treat it as an issue at first. :)

Just let @felixonmars dispatch the `picture-url` in `org.gnome.desktop.background` and close it then~

**Comment by felixonmars** [comment]
Ideally we should not touch anything in org.gnome, since we have a "wrap" anyway. How about unset the `picture-uri` in `org.gnome.desktop.background` for now?

**Comment by fasheng** [comment]
No problem~

**Comment by fasheng** [comment]
And I checked the `org.gnome.desktop.override` just now. Most of the settings could be ignored but the following ones if we want :
```
[org.gnome.desktop.interface]
cursor-theme='deepin'
gtk-key-theme='Default'
gtk-theme='deepin'
icon-theme='deepin'
gtk-im-module='fcitx'

[org.gnome.desktop.sound]
theme-name='deepin'
event-sounds=true
```
I will give a pat

**Comment by fasheng** [comment]
Sorry for the wrong operation...
