### ISSUE TITLE
Control-Panel User-account webcam not work (camera not found)

### ISSUE THREAD

**Issue by pavlanton** [fasheng/arch-deepin#195]
Last update Control-Panel User-account webcam not work (camera not found)

**Comment by pavlanton** [comment]
Time zone is open ((

**Comment by fasheng** [comment]
So "Time zon is open" means issue https://github.com/fasheng/arch-deepin/issues/183 is still there?

But I could remove the added timezone normal. Here is my steps, please have a check if something misunderstand:

1. Enter ControCenter/Date and Time module
2. Press the "+" button to add a new timezone
3. Select the "Niue" and press "Add"
4. Now "Niue" was in the list and select it will change the timezone
5. Restore to the previous timezone and press "-" button
6. Press the orange "-" button in front of "Niue" to remove it
7. Press "Confirm" to make it effects

**Comment by oberon2007** [comment]
Working fine for me, too, but I must say that it's really counter-intuitive that you have to select what you want to keep before pressing "-" (5.) Don't you think? ;-)

**Comment by fasheng** [comment]
Well, maybe @pavlanton is misled by the UI ...

**Comment by pavlanton** [comment]
Sorry guys not work... I press add Nuie. and ))) i have two Nuie

**Comment by pavlanton** [comment]
Its not problem... little bug )))

**Comment by fasheng** [comment]
I see, it's the repeated items issue like this, right?
![deepinscreenshot20151223214947](https://cloud.githubusercontent.com/assets/3049011/11977642/80930082-a9bf-11e5-9b2c-5f7c5ea9835d.png)

**Comment by pavlanton** [comment]
Right i have one Nuei, if i want delete him and press Confirme. Not work. If i do add nuie i have Nuie twice.

**Comment by fasheng** [comment]
@pavlanton 
For the webcam issue, firstly it's OK here, so may be caused by the driver problem. Is `/dev/video0` exists in your machine? And what's the output of `v4l2-sysfs-path`?

**Comment by pavlanton** [comment]
[pavlanton@arch_ant ~]$ v4l2-sysfs-path
Video device: video0
Alsa playback device(s): hw:0,3 hw:0,7 hw:0,8 hw:1,0

**Comment by pavlanton** [comment]
In Skype work fine )))

**Comment by fasheng** [comment]
@jouyouyun Have an idea?

**Comment by pavlanton** [comment]
![untitled](https://cloud.githubusercontent.com/assets/16265783/12176721/787d7036-b571-11e5-91af-d4957a3c15df.jpg)

**Comment by jouyouyun** [comment]
Try to install `libqt5multimedia5` and `libqt5multimedia5-plugins`.

**Comment by fasheng** [comment]
The `qt5-multimedia` package should be installed as a dependce of `libdui`.

As jouyouyun said, maybe it's a front-end issue. 
@sbwtw Any idea?

**Comment by jouyouyun** [comment]
Missing dependency

**Comment by sbwtw** [comment]
i think its some dependencies missing, qt multimedia is depends gstreamer: https://bugreports.qt.io/browse/QTBUG-39798

**Comment by sbwtw** [comment]
@pavlanton about time zone, you can try to remove ~/.config/deepin/dde-control-center-datetime.conf

**Comment by fasheng** [comment]
Thanks jouyouyun and sbwtw, looks we lost **gst-plugins-bad** in depends.
@pavlanton Please install it and have a try again.

**Comment by pavlanton** [comment]
Yoann Lopes added a comment - 23/Jun/14 11:09 AM

It looks like some GStreamer plugins are missing. Are all of them installed on your machine? (For GStreamer 0.10) Make sure gst-plugins-good, gst-plugins-ugly and gst-plugins-bad are installed.

Its work... Thanks

**Comment by fasheng** [comment]
@felixonmars OK, let's append **gst-plugins-good**, **gst-plugins-ugly** and **gst-plugins-bad** to the `depends` of `libdui`.

**Comment by felixonmars** [comment]
We often do not want to add hard dependencies this way :(

Since the actual dependency is in `qt5-multimedia`, and the actual functionality is visible in `deepin-control-center`, I would suggest to add optional dependency to these two places. I would still want to figure out if all the three gst components are needed though, since `qt5-multimedia` already has an optional dependency on `gst-plugins-bad` for Qt MediaService.

**Comment by oberon2007** [comment]
Is **gst-plugins-base** also needed?
