### ISSUE TITLE
new gtk-theme

### ISSUE THREAD

**Issue by oberon2007** [fasheng/arch-deepin#198]
I liked the old gtk-theme with the dark grey window borders a lot more than the new one. :(
Now I have tried using the old package but that one seems to not play anymore with latest gtk versions.
I also have problems with any other themes I have tried sofar - either with Deepin or Deepin2D mode ...
Anyone has a suggestion for me how to get similar window borders as with Deepin 2014?

**Comment by fasheng** [comment]
Well, it's the new theme again...

For the old dark theme with 3.18 support, try this commit plese
https://github.com/linuxdeepin/deepin-gtk-theme/commit/320b08ccec72164526dcf0362aaebecdac5e599a

**Comment by oberon2007** [comment]
Hm. Well, not playing so nicely ... I am using **numix-archblue** now instead ;)
