### ISSUE TITLE
launching terminal app from launcher not working

### ISSUE THREAD

**Issue by oberon2007** [fasheng/arch-deepin#199]
When I try to launch for example **htop** from the launcher, nothing happens.

**Comment by hualet** [comment]
oberon2007, what's your default terminal ? is it deepin-terminal ?

**Comment by hualet** [comment]
fasheng, I don't think it's a bug of dde-launcher, it's a bug of deepin-terminal :/

**Comment by oberon2007** [comment]
Yes, deepin-terminal. I haven't changed anything there!

**Comment by oberon2007** [comment]
I don't know if it might be related to [this](https://github.com/linuxdeepin/deepin-terminal/issues/48) issue.
The difference is that with calling **htop** nothing happens, while with ``deepin-terminal -e sudo setup`` I can see the terminal briefly before it quits.

**Comment by hualet** [comment]
what happened if you set your default terminal to another terminal emulator ?

**Comment by fasheng** [comment]
I have not checked the issue in my archlinux, yet. But it works for xfce4-terminal/deepin-terminal and broken for xterm/urxvt/uxterm in the Deepin.

**Comment by oberon2007** [comment]
Here's some interesting information: I have tried with urxvt, xfce4-terminal and deepin-terminal. None of them work. If I set xterm as the default it's ok.
Interesting is the behaviour as soon as I install **gnome-terminal**: This one will not be listed as a choice for default in Control Center **BUT** from now on launching htop from the launcher will always open gnome-terminal, no matter what I select as the default terminal in Control Center.
My theory is that this has something to do with dconf-settings inherited from gnome... ... ;)

**Comment by fasheng** [comment]
I'm not sure, but looks caused by the related default terminal interface in **GIO** which used by the Dock back-end.
```
[org.gnome.desktop.default-applications.terminal]
exec='x-terminal-emulator'
```

**Comment by hualet** [comment]
The problem is the priority of which terminal will be used is hard coded by gio, it's something like xterm > gnome-terminal > "other terminal emulators", we've patched it on deepin.

**Comment by oberon2007** [comment]
This is still not working... :-/

**Comment by fasheng** [comment]
I'm not sure the guys want to solve such issue...
OK, I will move it to the upstream dde-daemon issue list :')
