### ISSUE TITLE
switch layout with <Super>Space ?

### ISSUE THREAD

**Issue by oberon2007** [fasheng/arch-deepin#201]
The Control Center lists a keyboard shortcut: ``Switch Layout - <Super>Space`` which has no effect.
What is it supposed to do?

**Comment by fasheng** [comment]
You should contains at least two layouts or there is no effects any more :P

**Comment by oberon2007** [comment]
Oh, can I ask what a layout is, then? ::)

**Comment by fasheng** [comment]
It's the keybord layout ;)

@hualet @jouyouyun
Looks the **Switch Layout**'s expression is not clear, how about change it to **Switch Keybord Layout** or something else?

**Comment by pavlanton** [comment]
Russian-English-Hebrew is open (((

**Comment by oberon2007** [comment]
Yes, it's not clear ;)
I think it should read keyboard layout. :)
