### ISSUE TITLE
When a character is not a alphabet was used in the keyboard settings, problem occurs in the list

### ISSUE THREAD

**Issue by fu-sen** [fasheng/arch-deepin#202]
I tried Deepin flavor of Manjaro in Japanese.
I looked for "日本語" (Japanese) from the list of "J" in the setting of the keyboard, but it did not exist.
As a result of looking for the list, it had been included in the why "R".
When it is in the language is not in English, it seems to have a problem with the sort of keyboard settings.

![list of "J"](https://cloud.githubusercontent.com/assets/5434159/12005735/5ecbd90c-abf8-11e5-83bf-f1fdf330b6fb.jpg)

![list of "R" 1](https://cloud.githubusercontent.com/assets/5434159/12005736/64a9e21a-abf8-11e5-8498-4d9219e2fac5.jpg)

![list of "R" 2](https://cloud.githubusercontent.com/assets/5434159/12005738/68737aa0-abf8-11e5-8494-8fc8f60818c1.jpg)

**Comment by oberon2007** [comment]
I agree that the sorting of keyboard layouts is messed up:
"German" without any attributes like German (Austrian) should be on top of the German entries and not somewhere way down in the middle of other entries.

**Comment by oberon2007** [comment]
Sometimes it appears to be quite random, too:
![languages](https://cloud.githubusercontent.com/assets/11800714/12005767/be63d168-abb6-11e5-8182-a08db345f669.png)
This is not where it should be in alphabetical order of course, also, the currently selected layout "German" (without any option) is missing from the list completely, while just before when "German (Austrian)" was the selected layout, this one WAS listed...

**Comment by fasheng** [comment]
Sorry for the trouble, report it to upstream now.

@jouyouyun Help :)

**Comment by jouyouyun** [comment]
@fasheng create a tower task, design issues.
