### ISSUE TITLE
What is deepin-social-sharing

### ISSUE THREAD

**Issue by oberon2007** [fasheng/arch-deepin#203]
In the manjaro forum there was this question:
> What is the package "Deepin-social-sharing"? I run it and nothing happened 

I have no answer 8^} @fasheng @felixonmars can you help me out? ;)

**Comment by fasheng** [comment]
it is used by the deepin-screenshot :)



2015年12月27日 下午2:54, 下午2:54，在 Bernhard Landauer <notifications@github.com> 已写:

**Comment by oberon2007** [comment]
Aaaah, thank you :)
