### ISSUE TITLE
OpenRC sound-plugin

### ISSUE THREAD

**Issue by oberon2007** [fasheng/arch-deepin#204]
I am trying to build an OpenRC version of Manjaro Deepin at the moment.
All looking quite good sofar but I don't have sound an no sound-icon in the dock. Clicking the sound-tab in Control Center crashes DCC.
Any idea where to start? ;)

**Comment by oberon2007** [comment]
Ah. I see. The simple reason was that pulseaudio didn't get autostarted ;) How does that normally happen?

**Comment by fasheng** [comment]
There is `/etc/xdg/autostart/pulseaudio.desktop`, so pulseaudio should be started automatically from startdde.

**Comment by oberon2007** [comment]
Right now it is only autostarted under OpenRC when I place **pulseaudio.desktop** in **~/.config/autostart**. The pity is that like that the startup sound is not being played becuase pulse starts too late...
