### ISSUE TITLE
"Uninstall" item in right click menu of launcher not works for other distros like archlinux

### ISSUE THREAD

**Issue by fasheng** [fasheng/arch-deepin#205]
OK, let's just remove the "Uninstall" item from menu which only work in Debian with deepin-store installed.
@oberon2007

**Comment by oberon2007** [comment]
Ok, thanks! Same applies for the 'Update' item in Control Center I'm aftaid ... ;)
For Manjaro we could even think about patching **launcher** and **control center** to use **Pamac** instead... Would you mind pointing me to the respective places in the code?

**Comment by fasheng** [comment]
Here is the code:
https://github.com/linuxdeepin/dde-launcher/blob/master/controller/menucontroller.cpp#L100
https://github.com/linuxdeepin/dde-control-center/blob/dev/2015/modules/system_info/systeminfo.cpp#L171

I'am not familiar with **Pacma**, how about hide such items firstly?

**Comment by felixonmars** [comment]
or maybe even better - use packagekit so it works for much more distros :P

**Comment by fasheng** [comment]
Good idea, report to upstream now.

@snyh Is it possible to support **packagekit** in the following version of Deepin?

**Comment by fasheng** [comment]
Through it comes later, the upstream agree to add support for `PackageKit`, it will solved such issues then :)

**Comment by fasheng** [comment]
See https://github.com/linuxdeepin/developer-center/issues/47
