### ISSUE TITLE
控制中心的系统升级能否让arch自动更新

### ISSUE THREAD

**Issue by zhuzilinuser** [fasheng/arch-deepin#208]
比如自动执行pacman -Syu 或者切换/etc/pacman.d/mirrorlist的顺序。

**Comment by fasheng** [comment]
果然有这种需求吗？刚刚还在讨论 xD
https://github.com/fasheng/arch-deepin/issues/205

**Comment by zhuzilinuser** [comment]
毕竟有这个功能x

**Comment by sbwtw** [comment]
要是有一个类似的daemon的话当然也可以呀 @fasheng

**Comment by sbwtw** [comment]
话说可以添加编译参数不编译 系统更新 功能的

**Comment by felixonmars** [comment]
PackageKit has a dbus service at "/usr/share/dbus-1/system-services/org.freedesktop.PackageKit.service", and it has many frontends already (like gnome-packagekit).

**Comment by fasheng** [comment]
是啊，一开始我想的也是直接隐藏 UPDATE，但一直没管结果被发现了 xx

目测如果单纯给 控制中心/Launcher 添加 PackageKit 接口应该不会太复杂～

**Comment by fasheng** [comment]
See https://github.com/linuxdeepin/developer-center/issues/47
