### ISSUE TITLE
minimized window will not restore 

### ISSUE THREAD

**Issue by oberon2007** [fasheng/arch-deepin#211]
On some occasions when trying to restore a minimized window, it flashes up briefly, then disappears again. Fixed by switching to Metacity and back...

**Comment by oberon2007** [comment]
Well, seems like this happens regularly with **Filezilla**. Once it occurred with *Chromium**.

**Comment by fasheng** [comment]
Ehmm, I just press minimized button and dock icon multiple time, but Filezilla works fine here. Did I forgot something?

BTW: Filezilla is launched from terminal for the Launcher empty item issue

**Comment by sonald** [comment]
turn on debug info logging by exec `qdbus com.deepin.wm /com/deepin/wm com.deepin.wm.ToggleDebug` and show me the log resided in /tmp/mutter-`pidof deepin-wm`-XXXXX , then I may help.

**Comment by oberon2007** [comment]
It has not happened again lately ... ;) Closing for now and will reopen with more information in case it reappears :)
