### ISSUE TITLE
注销并重新startx之后..

### ISSUE THREAD

**Issue by ListenerRi** [fasheng/arch-deepin#215]
注销并重新执行startx之后,概率极高的会出现:
1:点击Launcher无反应
2:控制中心无法调出
其他暂未发现

**Comment by sbwtw** [comment]
但是注销为什么会到“执行startx”这一步呢

**Comment by ListenerRi** [comment]
@sbwtw 登陆到tty,然后执行startx启动的dde,注销之后自然会回到tty界面...

**Comment by fasheng** [comment]
这是上游的一个 bug，不过用 xinit 可避免这种问题～



2016年1月2日 下午1:07, 下午1:07，在 ListenerRi <notifications@github.com> 已写:
