### ISSUE TITLE
'add user' option has disappeared

### ISSUE THREAD

**Issue by oberon2007** [fasheng/arch-deepin#216]
I don't know when or by which pkg upgraded this has happened, but I just realize that in control center 'user accounts' tab the 'add new user' entry has diappeared again.
Downgrading **deepin-control-center** doesn't seem to help, so the problem probably lies somewhere else?

**Comment by fasheng** [comment]
deepin-daemon controls such behavior.
and the '+' button only appear for a sudo user. so do you using a normal user at the moment, or please upload the /etc/sudoer config file which is helps.



2016年1月2日 下午7:46, 下午7:46，在 Bernhard Landauer <notifications@github.com> 已写:

**Comment by oberon2007** [comment]
Thank you. Solved by adding the user to group %wheel :)
