### ISSUE TITLE
关于界面是英文

### ISSUE THREAD

**Issue by ListenerRi** [fasheng/arch-deepin#217]
@fasheng 
额..不好意思的说,这个猜测是我在删掉dde用回xfce的时候发现的
当我startx启动xfce之后,突然发现xfce也成了英文的,我就查看了下LANG变量,很正常,是:zh_CN.UTF-8
但桌面环境却不知为何成了英文,我又检查了下家目录和/etc下的配置文件,也很正常,本想就这样吧,接着就手动rm卸载dde后的遗留文件,过程中发现家目录下有一个".pam_environment"文件,感觉有些奇怪,因为在安装dde之前是没有这个文件的,于是cat了下,发现内容只有一行:LANG=en_US.UTF-8
rm掉这个文件,然后重启xfce,界面就是正常的中文界面了
因为已经没有dde桌面环境了,所以也就无法测试修改.pam_environment这个文件能否对dde有效果了

**Comment by zhuzilinuser** [comment]
改了以后只有应用列表的程序名字更改为中心，而且语言列表依旧为空。

**Comment by fasheng** [comment]
没错，home 下的 pam_environment 是 deepin 创建的，主要是为了实现多用户拥有独立的语言配置。



2016年1月3日 下午5:28, 下午5:28，在 ListenerRi <notifications@github.com> 已写:
