### ISSUE TITLE
Cannot set custom wallpapper

### ISSUE THREAD

**Issue by misterch0c** [fasheng/arch-deepin#218]
The default wallpapper are working fine but if I right click on an image, set is as wallpapper then I get a black screen. Login out or rebooting didn't change anything

Thank you

**Comment by sacatelasganasss** [comment]
install gnome-settings-daemon

**Comment by stevedude** [comment]
I found out there is a set limit to how many wallpapers display in Control Manager. If you hover over some custom wallpapers, you'll get an "X". Click on the X to remove it from the display list. Depending how many times you set different wallpapers eventually if you close enough of them, you'll see you wallpaper shown. I believe you have to click off the Control panel so it disappears then relaunch it and it should be there. I had a couple, for whatever reason, I had to log off then back on again and then they displayed.

**Comment by fasheng** [comment]
@jouyouyun

**Comment by jouyouyun** [comment]
Can exec the following command  before setting wallpaper" Then setting it.

`gsettings monitor org.gnome.desktop.background`
`gsettings monitor com.deepin.wrap.gnome.desktop.background`

Then paste the above commands's output, thanks!
