### ISSUE TITLE
analog clock display oddity

### ISSUE THREAD

**Issue by oberon2007** [fasheng/arch-deepin#219]
This is being displayed at 9.55 ;)
![clock](https://cloud.githubusercontent.com/assets/11800714/12080740/0e63fb16-b265-11e5-9f24-b37db60aab8e.png)
The minute hand jumps to 10 only at the full hour but doesn't move before that. Not good!... 8^}

**Comment by fasheng** [comment]
Will be fixed in deepin-control-center 3.0.6, let's wait for the new tag then.

**Comment by oberon2007** [comment]
fixed, thank you! :)
