### ISSUE TITLE
同样的视频，deepin movie和vlc的对比播放。

### ISSUE THREAD

**Issue by zhuzilinuser** [fasheng/arch-deepin#221]
deepin movie画面颜色不太对，没有进行任何设置，均为默认。
![20160106094521](https://cloud.githubusercontent.com/assets/12298476/12132823/9b21df86-b45a-11e5-9297-1ea66c974b44.png)
![20160106094553](https://cloud.githubusercontent.com/assets/12298476/12132824/9b2414a4-b45a-11e5-9e50-92cc50bf688c.png)
![20160106094559](https://cloud.githubusercontent.com/assets/12298476/12132825/9b54c900-b45a-11e5-8410-3f818e95b907.png)
![20160106094636](https://cloud.githubusercontent.com/assets/12298476/12132826/9b5534f8-b45a-11e5-8631-114d7aa0098b.png)
![20160106094644](https://cloud.githubusercontent.com/assets/12298476/12132827/9b86d6a2-b45a-11e5-8b4b-40d3182db53f.png)

**Comment by fasheng** [comment]
只要上传 linux 下 vlc 和 deepin-movie 同一时间点截图就可以，window 的色彩管理本身就不同。还有第 2/3/4 张分辨不出来到底是那个播放器。。

**Comment by zhuzilinuser** [comment]
环境是kde，只是换了主题。。
deepin movie下截图
![20160106111122](https://cloud.githubusercontent.com/assets/12298476/12134082/be12c9c2-b466-11e5-8922-1df47bcead75.png)

vlc下截图
![20160106111456](https://cloud.githubusercontent.com/assets/12298476/12134095/ce9f26d2-b466-11e5-9ca4-568c18c309ae.png)

**Comment by fasheng** [comment]
嗯，感觉亮度/对比度不太一样，@hualet @wang-bin 怎么看？

**Comment by hualet** [comment]
我在最开始的时候就提到过，忘了当时斌哥怎么说得了。刚好他在，我让他看下。 :smile:

**Comment by felixonmars** [comment]
也可能是默认后期滤镜的区别？

**Comment by wang-bin** [comment]
色彩空间转换时系数有点差别，我可以调整下
