### ISSUE TITLE
scrolling in launcher sorted by category not working

### ISSUE THREAD

**Issue by oberon2007** [fasheng/arch-deepin#223]
The above mentioned doesn't work and closes the launcher.

**Comment by fasheng** [comment]
Got it, will notify the developer tommorow.

**Comment by fasheng** [comment]
@dragondjf Help ;)

**Comment by oberon2007** [comment]
It got worse with update to **deepin-launcher 3.0.2-1**. Now the category view is completely empty ;)

**Comment by fasheng** [comment]
Solved in upstream now. Let's just wait for **dde-launcher 3.0.4** and **dde-daemon 3.0.8** in archlinux~

**Comment by oberon2007** [comment]
Can I ask when the new versions will be released? Would be great to have these bugfixes (also the laguage list thing...)! ;)

**Comment by fasheng** [comment]
well, i'm not sure, maybe one week later for it still holidays current days~



2016年2月8日 18:39, 18:39，在 Bernhard Landauer <notifications@github.com> 已写:

**Comment by fasheng** [comment]
Fixed now in deepin-launcher 3.0.4.
