### ISSUE TITLE
Can't switch keyboard layout

### ISSUE THREAD

**Issue by szdavid92** [fasheng/arch-deepin#224]
Hi,
I'm on an Arch Linux system, with Deepin 15 desktop and switching between keyboard layouts doesn't work for me. Most of the time no matter what I choose, it stays the same as before, other times it switches. I can't figure out why it works randomly. Does anyone have the same problem?

**Comment by fasheng** [comment]
Yes, it's the issue of gsettings that build with gccgo. Same issue is here https://github.com/fasheng/arch-deepin/issues/177
