### ISSUE TITLE
Dual Monitor issue under archlinux

### ISSUE THREAD

**Issue by alexcwyu** [fasheng/arch-deepin#226]
hi,

my PC is using this config:
display card: nvidia 670
monitors: 2 x Dell 2151H, running in displayport 1.2 MST mode (PC connect to first monitor via displayport in, and the first monitor connect to second monitor via display port MST)

My manjaro xfce can utilize 2 monitors correctly.
But when I change to manjaro deepin (clean install in other partition), the second monitor has no signal.
I upgraded kernel to 4.3.3, installed and enabled nvidia proprietary driver. the desktop can be displayed in both monitors but the deepin-dock is "gone"

Also, the screens backout every 1-2 mins and resume in next 1-2 sec. is this display card issue?

Finally, in xfce, the display manager has option to notify user when new monitor is plugged / unplugged. Could this be added to deepin.

Let me know if you need further info.

**Comment by fasheng** [comment]
Could you see the second monitor in deepin-control-center/Dsiplay? Try to setup it to see the result, please.

Does xfce runs with the nvidia proprietary dirver? If is no, and there is no screens bakcout issue under xfce, it should be a graphic driver issue.

Thanks for your advice, reported to upstream now.

**Comment by alexcwyu** [comment]
yes, both xfce and deepin are running the same kernel 4.3.3 and same version of proprietary driver from nvidia

There was other issue in xfce: the 2nd monitor has no singal and go into power saving mode, even the display manager of xfce said both monitors are enable. I followed this thread:
      http://ubuntuforums.org/showthread.php?t=2301503
and fixed my manjaro xfce issue by run this command:
      xset dpms force off; sleep 1;xset dpms force on

In deepin, I already run this command. This bring back my 2nd monitor but the dock is missing.
I can run xrandr and nvidia control panel, both show dual monitor.
Besides, I cannot access the display manager as the side panel (notification panel) cannot be shown in dual monitor setup. (This is another issue beside the missing dock)

**Comment by hualet** [comment]
@alexcwyu do your two monitors share the same resolution ?

Plus, you said:
>Finally, in xfce, the display manager has option to notify user when new monitor is plugged / >unplugged. Could this be added to deepin.

I'm curious, why would we need that at all :smile:

**Comment by alexcwyu** [comment]
@hualet, no necessary.
if there is an option in manjaro to auto-connect to all newly plugged monitor, this would be even better.

**Comment by fasheng** [comment]
>Besides, I cannot access the display manager as the side panel (notification panel) cannot be shown in dual monitor setup. (This is another issue beside the missing dock)

Try `dde-contro-center --show` in terminal.

**Comment by alexcwyu** [comment]
@hualet, same resolution 2560 x 1440 @ 60hz

**Comment by hualet** [comment]
@alexcwyu OK, I see. thx :-)
