### ISSUE TITLE
Configuration go rouge when exec shutdown +time

### ISSUE THREAD

**Issue by adderly** [fasheng/arch-deepin#227]
Hello, 
It has happened couple of times now. Apparently the deepin configuration gets corrupted sometimes with shutting down the system from console. In this case issuing the "shutdown +time" have resulted in missing dock items and reset monitor configuration (dual monitor).

**Comment by fasheng** [comment]
I guess it's caused by the gsetting issue, too :(
https://github.com/fasheng/arch-deepin/issues/185

**Comment by adderly** [comment]
Ok. Hopefully it gets solved.
