### ISSUE TITLE
DDE langpack request and issues with the used language

### ISSUE THREAD

**Issue by sergioad** [fasheng/arch-deepin#228]
Hello friends coud you port the deepin desktop's language packs too? I speak Spanish and DDE does not displays the avaliable languages, also I found that after adding the missing langpack packages and seeing if I can put  DDE in Spanih Iam stuck with the English language, coud you add the packages and check this issue? I really love deepin desktop and I want to see it on Spanish or at least on Spanglish by being able to select the Spanish language

I am using Manjaro deepin

**Comment by fasheng** [comment]
Sorry for the trouble. The languages packs are there, just could not be found by arch-deepin, see this topic please.
https://github.com/fasheng/arch-deepin/issues/212

And a temporary solution is change the language manually and re-login to see the result(please correct the langauge name in the following command) .
> echo 'LANG=es_AR.UTF-8' > .pam_environment

**Comment by sergioad** [comment]
@fasheng could you copy the es_AR locales to the es_MX and es locale folders? that could make it work on any es locale

**Comment by fasheng** [comment]
I see, the latest tag for deepin-control-center(3.0.4)/deepin-dock(3.0.2)/deepin-launcher(3.0.2) already contains such translations, but we didn't install them in arch.

@felixonmars 
Here is the difference for package files between deepin and archlinux.
https://github.com/fasheng/arch-deepin/blob/master/debug/filelist.diff

A strong thing is that I download one PKGBUILD through `yaourt -G  deepin-dock` and build it locally, but the result `deepin-dock-3.0.2-1-x86_64.pkg.tar.xz` contains all the translation files as expected. Any idea?

https://www.archlinux.org/packages/community/x86_64/deepin-dock/files/

**Comment by felixonmars** [comment]
So `qt5-tools` was missing from the `makedepends` array. I'm fixing the mentioned three packages. Any more to fix?

**Comment by fasheng** [comment]
deepin-movie and deepin-session-ui require it, too.

One more thing, there is no `/usr/bin/deepin-open-chooser` in our deepin-nautilus-properties, let's append it and fix https://github.com/fasheng/arch-deepin/issues/179

I will filter useless data in `flielist.diff` later to make it helpful for us. :)

**Comment by felixonmars** [comment]
Just checked that the release/2.3 branch of deepin-movie is still using deepin-gettext-tools.

**Comment by fasheng** [comment]
Got it. And for the missing debian hicolor links in `deepin-icon-theme`, I think upstream should dispatch it in a more general way, just left it there.

**Comment by felixonmars** [comment]
OK, thanks!

**Comment by felixonmars** [comment]
BTW, I did not find `deepin-open-chooser` in `deepin-nautilus-properties`'s source code, anything I'm missing?

**Comment by oberon2007** [comment]
Uhm. https://github.com/fasheng/arch-deepin/issues/179 is fixed for me... :laughing: Maybe because I already rebuilt my deepin-session-ui with qt5-tools? ;)

**Comment by oberon2007** [comment]
Nuh, sorry, not true...

**Comment by fasheng** [comment]
Wait one minute, I will build on deepin to see the reault...

**Comment by fasheng** [comment]
Well, the code in gerrit/github is out of data, I will sync to them soon..

**Comment by sergioad** [comment]
@fasheng @oberon2007 waiting for the fixes for Manjaro Deepin :smile:

**Comment by oberon2007** [comment]
On the way. Some new packages are already in Manjaro unstable... :smiley:

**Comment by sergioad** [comment]
Cool, pleae advice me when the package land to manjaro stabe and them you should (if you can) re-release the  manjaro deepin with the new packages and updates :smile:

**Comment by oberon2007** [comment]
The latest packages will arrive in stable with the next regular update on Monday (normally). We don't release new ISOs every time. You can simply update! :smile:

**Comment by sergioad** [comment]
Ok, thank you very much, I will stay on Kubuntu WIndows 10 and Remix OS (if I manage to get it working) unti the release of the next updates or even the next Manjaro deepin's release :smile:

**Comment by fasheng** [comment]
Upsteam solved it now, see #212 please.
