### ISSUE TITLE
suggestion for system-monitor

### ISSUE THREAD

**Issue by oberon2007** [fasheng/arch-deepin#229]
Even though this is of course an upstream topic I would still like to start this here to be passed on if you don't mind.
If I am not mistaken, Deepin does not offer its own system-monitor atm. For Manjaro I have patched **mate-system-monitor**, which works beautifully of course, just the .desktop file needs to be fixed in order not to be hidden in DEs other than Mate and the icon on the first tab needs to be replaced by something non-Mate ;)
If you want to do it really properly just a little more work will be needed to adjust the name of the application...

**Comment by oberon2007** [comment]
![system-monitor](https://cloud.githubusercontent.com/assets/11800714/12322391/19539200-bab4-11e5-9da8-d16a660f8783.png)
![monitor2](https://cloud.githubusercontent.com/assets/11800714/12322392/195809ac-bab4-11e5-92fe-d0750a467cee.png)
;)

**Comment by fasheng** [comment]
You really did it, amazing :+1:

**Comment by fasheng** [comment]
Thanks~
