### ISSUE TITLE
Move Deepin dock to top/bottom/left/right side

### ISSUE THREAD

**Issue by sacatelasganasss** [fasheng/arch-deepin#230]
deepin dock move???? deepin dock in top???

**Comment by fasheng** [comment]
Ok, looks dock became more unstable now..

Did it occurred for you before? How about 'killall dde-dock; dde-dock' in terminal?



2016年1月15日 07:40, 07:40，在 sacatelasganasss <notifications@github.com> 已写:

**Comment by oberon2007** [comment]
I assume @sacatelasganasss wanted to ask if it is possible to move the dock to the top? ;)

**Comment by fasheng** [comment]
OK, if so, I'm afraid not now. But we already add it as a new feature in plan :)
