### ISSUE TITLE
hiDPI support in Deepin

### ISSUE THREAD

**Issue by alexcwyu** [fasheng/arch-deepin#232]
I successfully installed Manjaro Deepin to my SurfacePro4.
However, the UI is too tiny in the 12 inch screen with 2,736 x 1,824 resolution.

I couldn't find the HiDPI setting for Deeping from wiki:
https://wiki.archlinux.org/index.php/HiDPI

Is there any HiDPI support in Deepin, so that I can set the scaling-factor 2?
If yes, how can i enable it?
If no, any timeline / roadmap?

I have tried other DE, so far Budgie is the best. The screen scale automatically. Gnome is also very good.
It would be great if Deepin support HiDPI like Budgie / Gnome.
I love Manjaro Deepin UI.

Thanks!

**Comment by fasheng** [comment]
Sorry for the trouble, Deepin not support HiDPI yet. And we will work for it as a high priority task later, please wait for some time~

**Comment by alexcwyu** [comment]
Glad to here Deepin dev team will look into this issue as high priority.
thanks @fasheng  & Dev team
