### ISSUE TITLE
NumLock state

### ISSUE THREAD

**Issue by thedeli** [fasheng/arch-deepin#233]
Hi. First of all thanks for your hard work for this beautiful desktop experience :) But I have one minor issue about num lock state. I use deepin de with arch linux. Everytime I start up my computer, I need to open numlock. I don't know if there is a setting for that in Deepin Linux keyboard settings, but with Arch there isn't. Is there a simple way to make my computer remember the num lock state?
Thanks again :)

**Comment by sbwtw** [comment]
numlockx is you need

**Comment by thedeli** [comment]
Thanks for the suggestion :) But I don't know how to autostart numlockx. I used in openbox, there is a autostart file there. Is there a file for dde? :)

**Comment by fasheng** [comment]
Please create a desktop file manually in `/etc/xdg/autostart`~
