### ISSUE TITLE
Problems with xrandr multi-screen configuration

### ISSUE THREAD

**Issue by bierpilot** [fasheng/arch-deepin#234]
Hello fasheng,

I wanted to use deepin on my notebook (Lenovot Thinkpad T400), which I oftenly use on different docking stations with multi-screen support, so the following problem came up: deepin recognizes my second monitor correctly as monitor on the right of my laptop (default?), but the monitor is physically ABOVE my notebook. When I configure it over the settings, it doesn't set up the configuration I want.

I want this configuration:
```
 __________________
 |                |
 |    VGA-0       |     <-- External monitor, NOT primary
 |________________|
 |           |
 |   LVDS    |  <-- Laptop lid, primary
 |___________|
```
When I do it with xrandr, using

    xrandr --output LVDS --auto --primary --output "VGA-0" --auto --above LVDS --noprimary

The configuration seems to be correct, but the dock of deepin remains in the middle of the screen VGA-0 (it looks like a projection of LVDS in VGA-0, but the mouse runs correctly. And there is no way to get the dock out there, except when I configure it to be always hidden, then it shows up in the primary screen (the notebook screen). The screen below also scrolls when I put the cursor to a position near the borders - so this is entirely not working for me. It also doesn't seem that the configuration is stored. After logging out and in again, all is lost and I need to reconfigure it (or call xrandr again - with same result).

Do you have any idea or way to fix this?

**Comment by fasheng** [comment]
As i known, the display module in deepin control center could not work with the xrandr command, so please try it firstly(you could drag the monitors in it to change the offsets).

If not works, i will report to ustream and a temp solution is to disable the deepin display module through the gettings in com.deepin.dde.daemon.display.



2016年1月25日 07:49, 07:49，在 bierpilot <notifications@github.com> 已写:

**Comment by bierpilot** [comment]
Hello,

thank you for your quick reply. Here you can find a screenshot how the 
configuraton looks like when I do it with deepin control center (if it 
works...): http://0wx.org/c6849e290090dc3d4d10b4450cc78d5a.jpg

And trying to do the screen settings configuraton over the deepin 
control center is really awful and does not work nicely. The "Apply" 
button is not displayed in many cases and the dock disappears...as you 
can in this video I recorded (I'm not sure how to describe it better).

This is the video: http://0wx.org/5f7398968e078849f5cd0e3281105c37.mov

Doing the configuration over xrandr would be a better option to me 
because I want to use the laptop on different places with amounts and 
setup of different external monitors - so always having this 
configration problems and hickup would not be an option to me, if an 
xrandr script does the job better.

It would be very nice if you could report this issues to the upstream!

Thank you.

**Comment by fasheng** [comment]
Thanks for such detailed report and sorry for the trouble.

So the problems are:
1. dock offset issue after display settings applied
2. sometimes the **Apply** button not works or disappear in **Display** module of control center

There are all known issues in upstream, right?
@hualet @Match-Yang

**Comment by hualet** [comment]
@fasheng yeah, I've seen both of the issues before.
