### ISSUE TITLE
右键菜单有错位

### ISSUE THREAD

**Issue by zhuzilinuser** [fasheng/arch-deepin#235]
![20160126202658](https://cloud.githubusercontent.com/assets/12298476/12580545/66310ccc-c46b-11e5-8728-8c3dcfb7d418.png)
还有启动器里面的右键。

**Comment by felixonmars** [comment]
这似乎是 Qt5 + 思源黑体的通病，可以试试暂时换用其他字体。

**Comment by sbwtw** [comment]
@hualet

**Comment by felixonmars** [comment]
FYI: https://github.com/adobe-fonts/source-han-sans/issues/114

**Comment by hualet** [comment]
已知的问题，不过也不对呀，我对思源黑体特殊处理了的。

fc-match输出啥？

**Comment by zhuzilinuser** [comment]
@hualet  wqy-zenhei.ttc: "文泉驿正黑" "Regular"

**Comment by zhuzilinuser** [comment]
![20160127202642](https://cloud.githubusercontent.com/assets/12298476/12613383/4a34ba68-c534-11e5-8d68-30b07230dfa8.png)

**Comment by hualet** [comment]
不是思源黑体呀，好吧，我再看看啥问题。

**Comment by ShikiSuen** [comment]
What you guys are talking about is exactly what I am complaining about regarding the font layout engine in at lease GNOME 3 and Cinnamon (I hadn't test other shell desktops yet). Refer to what I said here: https://github.com/adobe-fonts/source-han-sans/issues/114#issuecomment-199514397
