### ISSUE TITLE
which component writes ~/.config/deepin files?

### ISSUE THREAD

**Issue by oberon2007** [fasheng/arch-deepin#237]
I was wondering how and when the config files in **~/.config/deepin** are being created.
Where would be the place to interfere with for example ``clockAnalog=false`` in **dde-dock-datetime-plugin.conf**
```
pacman -Qo .config/deepin
error: No package owns .config/deepin
```
;)

**Comment by mmetak** [comment]
Packages don't own files in .config dir so 'pacman -Qo .config/deepin' will show nothing.
To change default settings you should take a look at those schemas files?
For clock it should be this one: https://github.com/linuxdeepin/deepin-desktop-schemas/blob/master/schemas/com.deepin.dde.dock.gschema.xml

**Comment by oberon2007** [comment]
Oh, sure! Thank you :)

**Comment by fasheng** [comment]
Wow, metak magically appears!
Welcome back :smile:

BTW: I still remember that our configuration files just a bit of confusion and we plan to refactor them after Chinese New Year, and such things will be discussed in the [deepin developer center](https://github.com/linuxdeepin/developer-center/issues)(It's just started, more information will be there :P )

**Comment by oberon2007** [comment]
Well, unfortunately gsettings are not effective as you can see in the scrot. Some other instance obviously writes the default 'clockAnalog=false' to **dde-dock-datetime-plugin.conf**

**Comment by fasheng** [comment]
But the gsettings works for me, try to restart the dde-dock process ;)
```sh
gsettings set com.deepin.dde.dock clock-type 'analog'
killall dde-dock; dde-dock
```

**Comment by oberon2007** [comment]
Yes it works to change it. The problem is with a fresh install that the gsettings default is overwritten by something at userlevel.

**Comment by oberon2007** [comment]
If I would know what process does that I could try to patch it at my end for now, but I was not able to find the responsible instance, yet ;)

**Comment by fasheng** [comment]
Ehmm, let's just ignore the `dde-dock-datetime-plugin.conf`, I don't know why it's there, too :(

How about override the gsettings in **deepin-desktop-schemas** as before
> echo ''clock-type='analog''" >> overrides/com.deepin.dde.dock.override 

And the owners of the config files are:
> dde-daemon/dock: gsettings/com.deepin.dde.dock
> dde-control-center/dock-plugins/dde-dock-datetime-plugin: ~/.config/deepin/dde-dock-datetime-plugin.conf

**Comment by oberon2007** [comment]
override is what I am doing now and the setting is there ;) but when the user gets created obviously **~/.config/deepin/dde-dock-datetime-plugin.conf** is written and respected by the plugin regardless of the gsettings :stuck_out_tongue_winking_eye: I'll have a closer look again at **dde-control-center/dock-plugins/dde-dock-datetime-plugin** I think I was exploring that one already yesterday but didn't find what I was looking for, yet... ;)

**Comment by fasheng** [comment]
@Match-Yang Help ;)

**Comment by Match-Yang** [comment]
All files in ~/.config/deepin/ which name like "dde-dock-*.conf" was created by DDE Dock's plugins.They are nothing to do with gsettings. :-P

**Comment by fasheng** [comment]
So is there a method to setup the clock display mode to **analog** as default currently? Especially for the new created user.

**Comment by Match-Yang** [comment]
Of course.In Fashion-mode,hover the mouse over the date-time-plugin's icon then right click the mouse and switch "Switch display mode".

**Comment by Match-Yang** [comment]
![Switch display mode](https://cloud.githubusercontent.com/assets/5242852/12773747/9ceb97f0-ca79-11e5-9c8b-b51927377669.png)

**Comment by fasheng** [comment]
Well, it should be a bug of dock-applets, we should use the value from gsettings when `~/.config/deepin/dde-dock-datetime-plugin.conf` is missing. Let's wait for some time to fix it~

**Comment by oberon2007** [comment]
@Match-Yang , I know that it can be changed manually :) The aim here is to deliver an ISO with this or that setting by default. Currently it cannot be done because the setting in **/usr/share/glib-2.0/schemas** gets overwritten :)
