### ISSUE TITLE
dde-session-daemon there is  memory leak？

### ISSUE THREAD

**Issue by zhuzilinuser** [fasheng/arch-deepin#240]
![20160206160053](https://cloud.githubusercontent.com/assets/12298476/12865581/2a2251e0-cceb-11e5-8e64-91529870cf0e.png)

login time dde is only 40m+,with the increase of time，memory  is used more and more。

**Comment by zhuzilinuser** [comment]
![Uploading 深度截图20160206161443.png…]()

**Comment by zhuzilinuser** [comment]
![20160206161443](https://cloud.githubusercontent.com/assets/12298476/12865675/f50a5acc-cced-11e5-837f-64fde13db0cc.png)

**Comment by felixonmars** [comment]
See also #162
