### ISSUE TITLE
Deepin Arch (Manjaro) behind proxy

### ISSUE THREAD

**Issue by walkingzen** [fasheng/arch-deepin#241]
Dear All,

I switched from manjaro plasma to deepin manjaro recently. I followed the steps mention in Arch Wiki for setting up the proxy settings in plasma version and it was working fine (i.e set proxy values in /etc/profile.d/proxy.sh and make it executable, add to defaults in sudoers etc.) Deepin provide option to set the proxy using front end and there is not option to take it from system settings as in plasma. Sometimes it is noted that port value become 0 in front end and it blocks all internet activities. then I tried by setting proxy in /etc/environment where we set value for environment variables.

I would really appreciate if you could let me know the right method for setting proxy in deepin manjaro.
If it through GUI please let me know the method to make it permanent (i.e. won't change port or ip automatically )

**Comment by fasheng** [comment]
Sorry for the trouble, it's a known issue in upstream. We will re-implemente the network proxy methods as soon as possible…



2016年2月9日 16:10, 16:10，在 Sreekanth V K <notifications@github.com> 已写:

**Comment by walkingzen** [comment]
Thank you very much

**Comment by fasheng** [comment]
Solved in upstream dde-daemon 3.0.11
https://bugzilla.deepin.io/show_bug.cgi?id=1369

**Comment by sreekanthvk** [comment]
Thank you very much
