### ISSUE TITLE
Deepin Lancher "by category" view is empty

### ISSUE THREAD

**Issue by omninonsense** [fasheng/arch-deepin#242]
Hello!

The Deepin Launcher doesn't seem to populate (or at least display) apps *By Category* (text or icon) in Arch Linux. 

I have checked whether the `.desktop` files have a `Categories` key, and they all do. So, I am not sure how else to debug this. I'll be happy to provide more info if I can! 

Screenshots:
 [![By Category View](http://i.imgur.com/RduxQWRm.png)](http://i.imgur.com/RduxQWR.png)
 [![By Name View](http://i.imgur.com/7tEbeD0m.png)](http://i.imgur.com/7tEbeD0.png)

**Comment by oberon2007** [comment]
The fix seems to be on the way already :) https://github.com/fasheng/arch-deepin/issues/223

**Comment by omninonsense** [comment]
@oberon2007 Ah, good catch! Thanks for pointing it out. I saw that issue, but I missed the your comment about the categories not populating at all, I assumed it was still related to crashing. I'm closing this, then. :+1:
