### ISSUE TITLE
launcher now completely empty

### ISSUE THREAD

**Issue by oberon2007** [fasheng/arch-deepin#243]
With today's upgrade the launcher does now display no icons at all for me, no matter what sorting :stuck_out_tongue_closed_eyes:

**Comment by stobbsm** [comment]
I'm having the same issue. Thought I would give deepin a try, but no applications in launcher means I have to find them in /usr/bin in the file manager, and launch them there.

Logs are not helpful either, as they don't seem to have any information, and I can't find a log for the daemon.

**Comment by oberon2007** [comment]
**deepin-daemon** obviously makes the difference ( @philmmanjaro fyi! ). Downgrading to **3.0.7** at least brings back icons sorted by name ... :grin: @fasheng , @felixonmars , maybe do we need an updated version of **deepin-launcher**? I've just tried simply rebuilding **3.0.3**, that didn't help. Maybe I'll try another build with the latest commits, too. Or do you already have an idea what the problem might be now with latest **deepin-daemon**?

**Comment by oberon2007** [comment]
I just built and installed the latest git snapshot of **dde-launcher** from cr.deepin.io - that's what we need, please! Even category view is working now!!! :tada: :laughing:

**Comment by farukuzun** [comment]
I'm having the same issue. @oberon2007 thanks for the tip, downgrading deepin-daemon solved the problem for me :smile:

**Comment by mattkennedynz** [comment]
^ thanks @oberon2007, that solved the problem for me too!

**Comment by fasheng** [comment]
Fixed in the latest deepin-launcher 3.0.4.
