### ISSUE TITLE
deepin-terminal not displayed in launcher

### ISSUE THREAD

**Issue by oberon2007** [fasheng/arch-deepin#247]
update to **deepin-terminal 1.1.3-1** made it unusable for me:
As usual the updated application disappeared from the dock.
But additionally deepin-terminal is no longer being displayed in the launcher. So I have no way of using it ...

**Comment by felixonmars** [comment]
There seems to be an upstream issue that the installation script no longer makes `/usr/share/deepin-terminal/src/main.py` executable, thus the symlink in `/usr/bin` doesn't work. I am pushing a downstream workaround for this, but it's better to be solved upstream. @fasheng

**Comment by fasheng** [comment]
Solved in tag 1.1.4

**Comment by felixonmars** [comment]
Comfirmed that tag 1.1.4 solved this. @oberon2007 do you still have the problem?

**Comment by oberon2007** [comment]
Fixed, thank you!
