### ISSUE TITLE
Cant change themes, icons and fonts after update

### ISSUE THREAD

**Issue by pavlanton** [fasheng/arch-deepin#248]
![default](https://cloud.githubusercontent.com/assets/16265783/13198042/c9e1deaa-d806-11e5-9acb-2bd865a3f562.jpg)
![2](https://cloud.githubusercontent.com/assets/16265783/13198043/c9e8e5b0-d806-11e5-8f5e-7384938e3e2a.jpg)

**Comment by fasheng** [comment]
How about `rm -rf ~/.local/share/personalization/` and login again?

https://github.com/fasheng/arch-deepin/issues/190

**Comment by pavlanton** [comment]
Sorry, not 8-(

**Comment by fasheng** [comment]
Try ` rm ~/.config/dconf/user` which will remove all user gsettings values. If not works again, please upload your `/usr/share/personalization/themes/deepin/theme.ini`~

**Comment by pavlanton** [comment]
[Theme]
Id=deepin
Name=deepin
Name[en_GB]=deepin
Name[en_US]=deepin
Name[zh_CN]=deepin
Name[zh_HK]=deepin
Name[zh_TW]=deepin

[Component]
GtkTheme=deepin
IconTheme=deepin
CursorTheme=deepin
FontName=sans-serif
FontMono=monospace
FontSize=11
BackgroundFile=file:///usr/share/backgrounds/deepin_default_background.jpg
SoundTheme=deepin

**Comment by pavlanton** [comment]
Cant change nothing in to Personalization

**Comment by jouyouyun** [comment]
Try to exec 'gsettings reset com.deepin.dde.appearance theme', then killall dde-control-center.

**Comment by jouyouyun** [comment]
Try to exec 'killall dde-session-daemon;/usr/lib/deepin-daemon/dde-session-daemon -v  > ~/dde-daemon.log', then open dde control center, click 'Personalization', then upload the log file '~/dde-daemon.log', thanks!

**Comment by pavlanton** [comment]
<info> proc.c:626: There already has a dde daemon running.

**Comment by pavlanton** [comment]
8-) Thats all

**Comment by oberon2007** [comment]
I just realized that there is another dconf blob: **"/run/$UID/dconf/user**
Maybe it would make sense to remove that one aswell?

**Comment by jouyouyun** [comment]
exec 'killall dde-control-center' before 'killall dde-session-daemon;/usr/lib/deepin-daemon/dde-session-daemon -v > ~/dde-daemon.log'

**Comment by pavlanton** [comment]
reinstalled system. all work. thanks
