### ISSUE TITLE
win+s以后，dock出现在窗口预览里面，可关闭。

### ISSUE THREAD

**Issue by zhuzilinuser** [fasheng/arch-deepin#249]
![20160222125150](https://cloud.githubusercontent.com/assets/12298476/13209798/2fd62114-d963-11e5-997f-67bc6b5c0998.png)

被关闭以后，等待数秒再次出现。

**Comment by sbwtw** [comment]
deepin 同样有这样的问题，应该是窗管 bug

**Comment by fasheng** [comment]
我昨天遇到一次, 不过没找到重现步骤, @oberon2007 也提到过
https://github.com/fasheng/arch-deepin/issues/246#issuecomment-186503099

**Comment by oberon2007** [comment]
Hi! :) I made a git bisect about that: https://github.com/fasheng/arch-deepin/issues/246#issuecomment-186608907

**Comment by oberon2007** [comment]
For me the issue was introduced with https://github.com/linuxdeepin/dde-dock/commit/3a38d20b5bb0af4d46dacfcd8f82a6da59daa0e2

**Comment by fasheng** [comment]
Thanks @oberon2007, this helps~

**Comment by sonald** [comment]
:+1: wow, that's a relief

**Comment by fasheng** [comment]
Looks related to https://github.com/linuxdeepin/dde-dock/issues/3.

**Comment by oberon2007** [comment]
Not sure @fasheng . ``_NET_WM_WINDOW_TYPE_DOCK`` looks ok here!
```
_NET_WM_STATE(ATOM) = _NET_WM_STATE_SKIP_PAGER, _NET_WM_STATE_SKIP_TASKBAR
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_WM_DESKTOP(CARDINAL) = 0
_NET_FRAME_EXTENTS(CARDINAL) = 0, 0, 25, 0
_NET_WM_ALLOWED_ACTIONS(ATOM) = _NET_WM_ACTION_CHANGE_DESKTOP, _NET_WM_ACTION_ABOVE, _NET_WM_ACTION_BELOW
_NET_WM_STRUT_PARTIAL(CARDINAL) = 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 279, 1086
XdndAware(ATOM) = BITMAP
WM_NAME(STRING) = 
_NET_WM_NAME(UTF8_STRING) = "Dock"
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x3, 0x3c, 0x7a, 0x0, 0x0
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DOCK
_XEMBED_INFO(_XEMBED_INFO) = 0x0, 0x1
WM_CLIENT_LEADER(WINDOW): window id # 0x2000005
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: False
		Initial state is Normal State.
_NET_WM_PID(CARDINAL) = 1630
WM_CLASS(STRING) = "dde-dock", "dde-dock"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		user specified location: 279, 723
		user specified size: 807 by 70
		program specified minimum size: 807 by 70
		program specified maximum size: 807 by 70
		window gravity: NorthWest
```

**Comment by hualet** [comment]
the original post has stated that the property is OK with xprop, it's all about i3 doesn't work well with dde-dock :joy:  @fasheng @oberon2007

**Comment by hualet** [comment]
@oberon2007 I reviewed the commit you provided, it shouldn't be the one introduced this bug. Would you please re-confirm that ? Thx

**Comment by oberon2007** [comment]
@hualet , you are right, in i3 the initial commit is already bad :laughing: 
But I have just double checked (in deepin :stuck_out_tongue_winking_eye: )
_commit=e7ceb38 # :+1: 
_commit=3a38d20 # :-1:

**Comment by hualet** [comment]
That's weird, @sbwtw and me will look into it. :disappointed:

**Comment by oberon2007** [comment]
Thank you! :smiley:

**Comment by hualet** [comment]
Hi all, @sbwtw the genius :joy: has found out the bad line, and I created a commit. https://cr.deepin.io/#/c/11022/  We tested it and everything seems pretty fine now. :smile:

**Comment by oberon2007** [comment]
Great job! Thank you! Will test it later :smiley:

**Comment by oberon2007** [comment]
Solved for. Well done! Hooray!

**Comment by oberon2007** [comment]
A question for the future: If this is simply related to **deepin-wm**, do you have an idea why this was only an issue for some installs and not for everyone - not even on other arch systems?

**Comment by fasheng** [comment]
Well, maybe dde-dock crash and restart more often in some special environment for it will reproduct the issue all the time...

**Comment by oberon2007** [comment]
It never crashed here. ... Anyway. I am glad that it's solved :smile: :+1:
