### ISSUE TITLE
weird output on deepin terminal when press pageup/down

### ISSUE THREAD

**Issue by femans** [fasheng/arch-deepin#252]
this is what happens when I press pageup or pagedown in the deepin terminal:

![deepinscreenshot20160223172549](https://cloud.githubusercontent.com/assets/625851/13258257/c56f601a-da52-11e5-8888-d7e5c16b4afd.png)

This was in a splitscreen fullscreen terminal. I did it in both sides. It fills up the screen with weird output. After scrolling up, part of it stays visible.

**Comment by fasheng** [comment]
What's the reproduct steps? And which shell do you use? At least both `bash` and `fish` is fine here.

BTW: The deepin-terminal 2.0 will released soon, which rewrite with vala and based on the newer vte component.

**Comment by femans** [comment]
I use bash in deepin terminal. 
reproduction:
* start deepin terminal
* press pageup

however, I have found out, its not related to the deepin terminal, because other terminals it happens as well when I press pageup. I have not tried rebooting. 

In fact it types a 2 screens long command on the command line, which starts with: v^_����^U�f�}^[   �^]j2g�5��:D�i#v�R��2g�5��:D�i#v�R��2g�5��:D�i#v�R�5��:D�i#v�R��2g�5��:D�i#v�R��2g�5��:D�i#v�R��2g�5��:D�i#v�R��2g�5��:D�i#v�R��2g�5��:D�i#v�R��2g�5��:D�i#v�R��2g�5��:D�i#v�R��2g�5��:D�i#v�R��2g�5��:D�i#v�R��2g�5��:D�i#v�R��2g�5��:D�i#v�R��2g�5��:D�i#v�R��2g�5��:D�i#v�R��2g�5��:D�i#v�R��2g�5��:D�i#v�R��2g�5��:D�i#v�R��2g�5��:D�i#v�R��2g

**Comment by femans** [comment]
i switched to a different window manager, cinnamon, and it still happens. My guess at this point is, it is not at all related to deepin. I will close the issue.
