### ISSUE TITLE
dde-launcher Segmentation Fault libQt5Core

### ISSUE THREAD

**Issue by MisterPresident** [fasheng/arch-deepin#253]
Hi,
I am getting a Segfault whenever I launch dde-launcher. It's a fresh installation.

If I check dmesg it says: [time] traps: dde-launcher[process-ID] protection ip:7f6efb908424 sp:7fffc2c3e440 error:0 in libQtCore.so.5.5.1[7f6efb7d1000+4c3000]

Please help me, thank you!

**Comment by fasheng** [comment]
The segmentation error code 0 is strange, which means **a kernel space application read memory failed for the wrong address**. But dde-launcher is just a normal user space application.

Please upload the coredump message:
```
coredumpctl dump /usr/bin/dde-launcher
```

And try to build deepin-launcher locally:
```
yaourt -G deepin-launcher
cd deepin-launcher
makepkg -is
```

**Comment by MisterPresident** [comment]
I attached the 
[Coredump Message](https://github.com/fasheng/arch-deepin/files/144328/Segfault.txt)


Problem solved by building locally. Thank you so much!
