### ISSUE TITLE
Deepin Launcher Does Not Consistently Show Icons

### ISSUE THREAD

**Issue by stevedude** [fasheng/arch-deepin#255]
It appears this issue was recently posted and then closed, however, I still run into issues with the Launcher being blank. If I click on the "Name" filter the icons reappear. I'm running Manjaro Deepin 15.12, 64bit with all of the latest updates.

This issue seems to be sporadic, sometimes when I click on the Launcher, the icons are there, other times, I see a blank blurred screen.

**Comment by oberon2007** [comment]
I was able to reproduce this by leaving the launcher in category view. When it showed up empty once, I switched to 'by name' and back to 'by category' and like that the icons re-appeared...
