### ISSUE TITLE
cant switch off corner navigation

### ISSUE THREAD

**Issue by femans** [fasheng/arch-deepin#256]
reproduce actions: click right on desktop, click corner navigation, in both the upper left and lower left select None. Move to one of the corners;
Expected: no desktop or application panels should appear.
In stead: desktop and application panel still appear 

After trying to switch it off again, it appears that None is already selected.

**Comment by fasheng** [comment]
I'm afraid it's the gccgo gsettings issue, too. And gccgo upstream merged our patch, so let's wait and have a see.
https://github.com/fasheng/arch-deepin/issues/185
