### ISSUE TITLE
rm overrides/{org.compiz,org.gnome.desktop,other}.override

### ISSUE THREAD

**Issue by oberon2007** [fasheng/arch-deepin#257]
Can I ask what was the reason for [this](https://projects.archlinux.org/svntogit/community.git/commit/trunk?h=packages/deepin-desktop-schemas&id=5d10fdbb475fb6429f81d948d6fa3aa8c3c863e8)? Did these overrides create any issues?
I would like to know because Manjaro is using and overlay-package **deepin-desktop-session-manjaro** and I have to decide if or how I adopt this :wink: 
Thank you.

**Comment by oberon2007** [comment]
@felixonmars ?

**Comment by fasheng** [comment]
Yes, someone report it here
https://bugs.archlinux.org/task/47963

And we are trying to resolve it in upstream, too.
https://github.com/linuxdeepin/developer-center/issues/45
