### ISSUE TITLE
Move issues here to upstream

### ISSUE THREAD

**Issue by fasheng** [fasheng/arch-deepin#258]

**Comment by fasheng** [comment]
Hi, I plan to move all issues here to upstream github projects this weekends, so we could discuss problems more convenient there with the developers.

And welcome to our new [developer center](https://github.com/linuxdeepin/developer-center/issues) which actor as wiki, developer forum and even improving task center. Of course you could report issues(if is not single project related) and advice there. Maybe you found a lot of Chinese there, don't worry, the developers glade to see English topics and reply to them, too :)

Thanks all for your support!

@adderly
@alexcwyu
@beanaroo
@bierpilot
@brendengibson
@eloc574
@felixonmars
@femans
@fu-sen
@fusion809
@mmetak
@misterch0c
@MisterPresident
@oberon2007
@pavlanton
@sacatelasganasss
@stevedude
@thedeli
@walkingzen
@xgdgsc
@zhuzilinuser

**Comment by pavlanton** [comment]
Thank you too

**Comment by fasheng** [comment]
Thanks all, this project is no longer being actively developed, more information to see the following links please:
- [deepin developer center](https://github.com/linuxdeepin/developer-center/issues)
- [manjaro-deepin](https://forum.manjaro.org/index.php?board=59.0)
- [archlinux wiki](https://wiki.archlinux.org/index.php/Deepin_Desktop_Environment)
- [archlinux bugs](https://bugs.archlinux.org)

**Comment by femans** [comment]
thanks!
