### ISSUE TITLE
全新安装的arch-deepin，似乎没有打包音频和电源方面的管理。

### ISSUE THREAD

**Issue by zhuzilinuser** [fasheng/arch-deepin#259]
打开控制中心，只有点击音频和电源会卡死，等待数分钟以后，面板切换到音频或电源，里面是空白的。
现在只能先安装其他桌面，才能正常使用deepin。

**Comment by hualet** [comment]
竹基，为啥不直接报到deepin的issue里面呢。。。

**Comment by fasheng** [comment]
包依赖的问题, 不太好分类, 或许和上游没有写全面依赖导致arch上的包依赖丢失有关, 一会先转移到linuxdeepin/developer-center吧, 讨论起来也方便

**Comment by hualet** [comment]
不像是包依赖的问题，如果是控制中心少了一个模块，不会等待会在页面立即显示包依赖缺失的信息，应该是后端挂了怎么滴。

**Comment by fasheng** [comment]
不确定, 也可能是 deepin-daemon 缺少依赖
