### ISSUE TITLE
Desktop wallpaper garbled after resuming from suspend

### ISSUE THREAD

**Issue by ThornedRose** [fasheng/arch-deepin#261]
![deepinscreenshot20160418120809](https://cloud.githubusercontent.com/assets/239386/14591693/a24513d6-0569-11e6-9d63-c2c2e4488ffb.png)

Fresh installation of Deepin on Arch Linux. The only other DE I have is Open Box.

Wallpaper is the default, no custom wallpapers added. Computer is suspended through the Deepin interface. When computer is resumed from suspend (by a keyboard press), the desktop wallpaper looks as per the screenshot.

The wallpaper can be restored by selecting a different wallpaper (which displays fine) and then reselecting the default wallpaper.

 OS: Arch Linux 
 Kernel: x86_64 Linux 4.5.0-1-ARCH
 Uptime: 4h 20m
 Packages: 1250
 Shell: bash 4.3.42
 Resolution: 1920x1200
 WM: Mutter(DeepinGala)
 WM Theme: Adwaita
 GTK Theme: Numix-Frost-Light [GTK2/3]
 Icon Theme: deepin
 Font: DejaVu Sans 10
 CPU: Intel Core2 Quad CPU Q6600 @ 2.4GHz
 GPU: GeForce GTX 650 Ti
 RAM: 2989MiB / 6979MiB

**Comment by fasheng** [comment]
Thanks for the report. I will move this to deepin developer-center to let the developers know it.
