### ISSUE TITLE
Nearly nothing will open, including the terminal

### ISSUE THREAD

**Issue by XC3me** [fasheng/arch-deepin#262]
I installed deepin 15.2 32bit twice but I'm having the same issue where chrome, firefox, the terminal and many other applications won't open, or close just after starting. When I tried running the driver manager, the error message i got was "Unable to copy the user's Xauthorization file."

I can open system settings, Deepin Music, the store and things like that.

Could my computer be just too weak to run deepin?

**Comment by fasheng** [comment]
So you mean you installed the official Deepin 15.2 instead arch-deepin. Please repeat the faild open operation and switch to tty by pressing ctrl-alt-f6 and run "env DISPLAY=:0 deepin-feedback-cli" which will try to collect your system error log. Then upload the log file, please.

2016年6月11日 03:55, 03:55，在 XC3me notifications@github.com 已写:

**Comment by XC3me** [comment]
Yes, I installed the official Deepin 15.2. Sorry, I'm very new to linux. But the prompt It gave me is, "env: DISPLAY=:0: No such file or directory" 
Again, sorry if that's not helping.

**Comment by fasheng** [comment]
OK, that's fine. I guess it caused by the `~/.Xauthority` problem, but don't know why, maybe it's aninstaller issue.
I will transfer this to upstream developer center, so more developers could see it.

**Comment by XC3me** [comment]
Thank you, I really appreciate it.
