### ISSUE TITLE
Possible memory leak in dde-session-daemon

### ISSUE THREAD

**Issue by oussemaAr** [fasheng/arch-deepin#263]
for the last 2 hours
![deepinscreenshot20160614150116](https://cloud.githubusercontent.com/assets/10359905/16043638/e430afe0-3240-11e6-8da0-f7aaca991544.png)

**Comment by fasheng** [comment]
It's gccgo/gir related,  and we place arch-deepin issues to linuxdeepin/developer-center now.
See https://github.com/linuxdeepin/developer-center/issues/100 please.
