### ISSUE TITLE
Multi Monitors second screen doesn't allow maximize to use whole screen

### ISSUE THREAD

**Issue by stobbsm** [fasheng/arch-deepin#30]
I have 2 monitors on my desktop, which was detected perfectly. All hot corners are on first monitor (as expected, for me at least), but when I try to maximize a window on the second display, the space where the bottom bar would be does not get used.

Also just noticed that when dock is set to auto-hide or stay hidden, you still can't maximize windows properly.

**Comment by fasheng** [comment]
Fixed now.
