### ISSUE TITLE
Desktop Computer and Trash icons unremovable

### ISSUE THREAD

**Issue by eloc574** [fasheng/arch-deepin#34]
Both in Efficient mode and Classic mode. 
Trash icon also undockable in Fashion mode.
Was not able to find any way to remove these icons.

**Comment by dopstar** [comment]
You can remove the two icons through `dconf Editor` or by running these `dconf` commands on terminal:
```
dconf write '/com/deepin/dde/desktop/show-trash-icon' false
dconf write '/com/deepin/dde/desktop/show-computer-icon' false
```

**Comment by fasheng** [comment]
Thanks dopstar's advice, it works but icons will come back after reboot...

**Comment by koesherbacon** [comment]
Dopstar:
+1 buddy.  I have yet to restart to see if it goes back, but so far so  good.

**Comment by oberon2007** [comment]
I think this is solved, is it? For me everything works fine now.

**Comment by ghost** [comment]
I used the commands above and it didn't work, any tips ?
