### ISSUE TITLE
Is it possible to split the greeter to an independent package such as lightdm-deepin-greeter?

### ISSUE THREAD

**Issue by jokeryu** [fasheng/arch-deepin#47]
I like the deepin-greeter, but I don't want to install other unnessary files of dde, deepin-workspace depends on too many packages. So I wonder if there is a simple way to make deepin greeter work on Arch.
Thanks.

**Comment by fasheng** [comment]
Thanks @mmetak, package lightdm-deepin-greeter exists now.
