### ISSUE TITLE
Could we change the version string to the format following the VCS PKGBUILD Guidelines?

### ISSUE THREAD

**Issue by Firef0x** [fasheng/arch-deepin#50]
Hello, @fasheng @mmetak ! :smiley: 

I'm so sorry to disturb you! But I wonder that how to define these kinds of version format in the following cases:

* https://bbs.archlinux.org/viewtopic.php?pid=1469337
* http://forums.opensuse.org/showthread.php/501869-How-to-define-these-kinds-of-version-format-in-OpenSUSE-Build-Service?p=2671201
* https://github.com/openSUSE/obs-service-tar_scm/issues/55

In this repo and the [mmetak's](https://build.opensuse.org/project/show/home:metakcahura) repo, all the `versionformat` of the git packages are the following:

```xml
<param name="versionformat">%cd.%h</param>
```

e.g. 
* https://github.com/fasheng/arch-deepin/blob/master/obs/home:metakcahura:arch-deepin/dbus-factory/_service#L6
* https://github.com/fasheng/arch-deepin/blob/master/obs/home:metakcahura:arch-deepin/dbus-generator/_service#L6
* https://github.com/fasheng/arch-deepin/blob/master/obs/home:metakcahura:arch-deepin/dde-api/_service#L6
* https://github.com/fasheng/arch-deepin/blob/master/obs/home:metakcahura:arch-deepin/dde-control-center/_service#L6
* https://github.com/fasheng/arch-deepin/blob/master/obs/home:metakcahura:arch-deepin/dde-daemon/_service#L6
* https://github.com/fasheng/arch-deepin/blob/master/obs/home:metakcahura:arch-deepin/dde-workspace/_service#L6

Could we change to the format following the [VCS PKGBUILD Guidelines](https://wiki.archlinux.org/index.php/VCS_PKGBUILD_Guidelines#Git) ?

Yours sincerely! :bow:

**Comment by fasheng** [comment]
Finally, upstream applied the patch, it a goods news. But we decided to switch package source from git repos to stable tarballs in deepin mirror these days. So I just close this topic now.

And thanks for @Firef0x 's positive focus(至于你提到的第二种需求, 被作者要求去除了, 我也爱莫能助啊).

**Comment by Firef0x** [comment]
Many thanks to @fasheng & @mmetak ! It's good to switch the source to stable tarballs since `Deepin DE` is stable for a period of time. :clap: 

Still long for the second feature. I think they rejected it just because there is a security vulnerability in the implementation of `@SEQUENCE_NUMBER@`, which would cause it to abort. However, if you don't need this feature any more, you are not responsible for implementing it.

**Comment by aspiers** [comment]
We didn't reject due to security concerns (what vulnerability do you mean?) but rather that sequence numbers don't make sense in git because it doesn't usually have linear history.
