### ISSUE TITLE
Upstream issue of Go, dde-daemon build failed for archlinux/go1.4/i686

### ISSUE THREAD

**Issue by fasheng** [fasheng/arch-deepin#55]
Seems like caused by an issue of go1.4, already reported to upstream.

https://github.com/golang/go/issues/9437

**Comment by felixonmars** [comment]
This doesn't seem to be true now, I've removed the patch for deepin-daemon.

**Comment by fasheng** [comment]
Really? I think the patch will works untile go 1.6 released.

**Comment by felixonmars** [comment]
Hrm, maybe I got it wrong - I meant this patch: https://github.com/fasheng/arch-deepin/blob/c9c53b2bb15b78ae3f4890028d02aceb7cbb6ee5/obs/home:metakcahura:arch-deepin:2015/dde-daemon/fix-i686-compile.patch

**Comment by fasheng** [comment]
Yes, it is fix-i686-compile.patch. Could you build deepin-daemon success without it under Archlinux i686?

**Comment by felixonmars** [comment]
Yes, that's why I removed it :)

**Comment by fasheng** [comment]
OK, glade to hear it, close issue now~
