### ISSUE TITLE
Many icons are blank and high cpu loaded when using Numix-Circle icon theme.

### ISSUE THREAD

**Issue by beanaroo** [fasheng/arch-deepin#57]
This happens when applying custom icon sets, specifically Numix family, Moka/Faba and Flattr.
![deepinscreenshot20141227083122](https://cloud.githubusercontent.com/assets/1748909/5560891/afb6303c-8daa-11e4-9bc1-5cc9370f1bf6.png)

**Comment by fasheng** [comment]
Hi, I installed `moka-icon-theme-git` and `faba-icon-theme-git`, but mostly icons is fine, including `CMake` and `7-Zip FM` that lost icons in your screenshot.

Here is my screenshots:

**moka**
![deepinscreenshot20150104182247](https://cloud.githubusercontent.com/assets/3049011/5604523/e37e4718-93fb-11e4-8806-9d7086b9df93.png)


**faba**
![deepinscreenshot20150104182452](https://cloud.githubusercontent.com/assets/3049011/5604530/950a6e26-93fc-11e4-8181-e11c6daf5b29.png)


**flattr**
![deepinscreenshot20150104182540](https://cloud.githubusercontent.com/assets/3049011/5604533/b407182e-93fc-11e4-8549-5d48464cae88.png)

So is something special in your DDE ?

**Comment by fasheng** [comment]
Got it, Numix-Circle icon theme reproduce the problem.

And just like @mmetak said, this also cause high cpu load and log files in /tmp start growing and growing... MB and MB...

    $ ls -lh /tmp/dde*
    -rw-rw-r-- 1 fsh  fsh  2.2K Jan  5 11:00 dde-desktop.log
    -rw-rw-r-- 1 fsh  fsh   72K Jan  5 11:06 dde-dock.log
    -rw-rw-r-- 1 fsh  fsh  1.5G Jan  5 11:09 dde-launcher.log

**dde-launcher.log**
    
    console message: file:///usr/share/dde/resources//launcher/js/launcher.js @3051: set container to grid
    
    console message: file:///usr/share/dde/resources//launcher/js/launcher.js @3051: set container to grid
    
    console message: file:///usr/share/dde/resources//launcher/js/launcher.js @3051: set container to grid
    
    console message: file:///usr/share/dde/resources//launcher/js/launcher.js @3051: set container to grid
    
    ...


Reported to upstream now.

**Comment by beanaroo** [comment]
I think this is a problem with Deepin Launcher not being able to show svg icon sets.

**Comment by fasheng** [comment]
Yes, svg works not well in webkit that launcher build on. The developer fixed this issue but now push to outside repo now.

**Comment by fasheng** [comment]
Please remove OBS repository from `/etc/pacman.conf` and update packages from [community] like this:

```sh
sudo pacman -R dde-dock-applets
sudo pacman -Syyuu
```
It should solved this issue.
