### ISSUE TITLE
unable to right click on desktop in virtualbox

### ISSUE THREAD

**Issue by blaale** [fasheng/arch-deepin#59]
As per title, in a relatively standard archlinux virtualbox setup (with base base-devel, sudo, xorg, virtualbox-guest-utils and deepin). I'm using this environment to test if I want to swap to DDE. Out of the box I am unable to right click the desktop.

EDIT: Just like to mention that I do have Nautilus installed and it is configured to manage the desktop.

**Comment by fasheng** [comment]
As you said, you use Nautilus to manage the desktop, so dde-desktop just be override :-)

**Comment by blaale** [comment]
I was under the impression Nautilus was used the manage the desktop in default DDE, my mistake.
It is worth noting that dde-desktop doesn't seem to manage the desktop on a default install (Ie. before I install nautilus).

**Comment by fasheng** [comment]
I see, please upload the /tmp/dde-desktop.log, and try to restart dde-desktop:

    killall dde-desktop
    dde-desktop -d

**Comment by fasheng** [comment]
Please remove OBS repository from `/etc/pacman.conf` and update packages from [community] like this:

```sh
sudo pacman -R dde-dock-applets
sudo pacman -Syyuu
```
