### ISSUE TITLE
control center->system infomoration takes a long time to load and gives NaN space

### ISSUE THREAD

**Issue by blaale** [fasheng/arch-deepin#60]
![arch dde-sysinfoissue](https://cloud.githubusercontent.com/assets/8383085/6141080/46456d32-b1ec-11e4-9601-f8c5e576c09c.png)
On a virtualbox install, clicking control center-->system information results in the UI hanging briefly before displaying NaN for capacity and such.

EDIT: See attached image for details

**Comment by fasheng** [comment]
Thanks, has reported to upstream.

**Comment by fasheng** [comment]
Fixed now, please run `pacman -Syuu` to update packages and checking the result.

**Comment by fasheng** [comment]
This problem is caused by depends missing in dde-daemon, which are lsb-release and udisks2. Fixed now.
