### ISSUE TITLE
launcher does not update with new applications after installation

### ISSUE THREAD

**Issue by blaale** [fasheng/arch-deepin#61]
After running the command pacman -S firefox (only an example, is the case with all software) the launcher will not include firefox in the list of applications until I perform a reboot or if I relog in/out.

My first thought is that the issue is related to apt in the Deepin Distro vs pacman in Arch.

**Comment by AnderRasoVazquez** [comment]
I can reproduce this bug.

**Comment by fasheng** [comment]
Yes, this is a bug for launcher, wish upstream fix it quickly.
