### ISSUE TITLE
Problems with fresh install : Lib ICU 54 

### ISSUE THREAD

**Issue by redvoodoochild** [fasheng/arch-deepin#64]
Hello.
Excuse my poor english.
After an install of deepin destock, I've just have the control center working.
dde-dock ; dde-desktop, etc.... need the lib icu54 to works, but i've got the icu55 installed.
I've done a "ln -s" to this lib.. and the error disapear
Now, i've got this error :
dde-desktop: symbol lookup error: /usr/lib/libdeepin_webkit-3.0.so.0: undefined symbol: UCNV_FROM_U_CALLBACK_SUBSTITUTE_54

Thanks for your help

**Comment by redvoodoochild** [comment]
I've manualliy compiled the ICU libs V54, and all is working.

**Comment by fasheng** [comment]
Thanks the report. This is caused by the old icu version in OBS, it was fixed now. Run `pacman -Syu` and everything will be fine.

**Comment by redvoodoochild** [comment]
It works. Thanks a lot.
