### ISSUE TITLE
Changelog notification

### ISSUE THREAD

**Issue by fasheng** [fasheng/arch-deepin#67]
Once packages updated, the Changelog will be append here. Anyone want to receive the news of arch-deepin please just subscribe this topic :)

**Comment by fasheng** [comment]
Version 20152927

 - deepin-music-player bump version to 3.0, see more [here](http://planet.linuxdeepin.com/deepin-screenshot-v3-0-released-taking-screenshots-easily/)
 - Fix xpyb and xpybutils depends issue for deepin-music-player in AUR
 - Upload deepin-menu and deepin-qml-widgets to AUR
 - Update dde-control-center to 0.1.20150413164707
 - Update dde-dock-applets to 0.0.4.20150414222121
 - Update dde-workspace to 2.1.20150413170547
 - Update deepin-menu to 1.1.20150415155150
 - Update deepin-movie to 2.2.1.20150424170255
 - Update deepin-music-player to 1.1.20150413165956
 - Update deepin-notifications to 0.3.20150311135741
 - Update deepin-qml-widgets to 0.0.2.20150423102550
 - Update deepin-screenshot to 3.0.20150422133441
 - Update go-dlib to 0.0.4.20150227094412
 - Update qtav to 1.6.0

**Comment by fasheng** [comment]
Version 20154429

 - Update dde-dock-applets to 0.0.4.20150427095046
 - Update deepin-notifications to 0.3.20150427175348
 - Update deepin-screenshot to 3.0.201504271302008

**Comment by fasheng** [comment]
Version 20150510

 - Fix qtav file conflicts issue, rename `/usr/lib/qt/bin/player`
   to `/usr/lib/qt/bin/qtav-player`

**Comment by fasheng** [comment]
Version 20150027

 - Update dde-dock-applets to 0.0.4.20150521130615
 - Update dde-workspace to 2.1.20150521160615
 - Update deepin-movie to 2.2.1.20150512143336
 - Update deepin-screenshot to 3.0.20150508154858

**Comment by fasheng** [comment]
Version 20150614

 - Rename deepin-music-player to deepin-music
 - Migrate deepin packages to aur4
 - Sync obs packages

**Comment by fasheng** [comment]
Version 20150625

 - Update deepin-pygtk, support numeric when compiling, change group
   to `deepin-extra`
 - Update deepin-ui, use `pygtk` instead of `deepin-pygtk` as depends

**Comment by fasheng** [comment]
Version 20150626

 - Fix deepin-compiz build issue
 - Update deepin-screenshot, use `pygtk` instead of `deepin-pygtk` as depends
 - Update deepin-vte, use `pygtk` instead of `deepin-pygtk` as depends
 - Update python2-deepin-utils, use `pygtk` instead of `deepin-pygtk` as depends

**Comment by fasheng** [comment]
Version 20150728

 - Sync obs packages
 - Change mirror site to `http://ftp5.gwdg.de` to make obs works easily
 - Update version format, remove `git` if exists, affected packages
   are `deepin-compiz`, `go-fsnotify`, `go-gettext-go`,
   `go-graphics-go`, `go-jamslam-freetype-go`, `go-sqlite3`, `go-xgb`,
   `go-xgbutil`, `python2-deepin-gsettings`
 - Update deepin-movie to 2.2.2.20150616111111
 - Fix deepin-screenshot version to 3.0.14.12.20150717162046

**Comment by fasheng** [comment]
Version 20150907

 - Fix startdde wallpaper update issue

**Comment by fasheng** [comment]
Version 20150908

 - Fix dde-workspace build issue under go1.5

**Comment by fasheng** [comment]
Version 20150909

 - Fix dde-daemon block issue under go1.5

**Comment by fasheng** [comment]
New tags for Deepin 2015 Beta1

| Project                |  New tag |
|------------------------|---------- |
| deepin-wm-switcher     |    0.0.1 |
| deepin-file-manager    |    0.1.2 |
| dde-account-faces      |    1.0.9 |
| deepin-artwork-themes  |  15.10.2 |
| dde-api                |   2.92.2 |
| deepin-desktop-schemas |   2.91.2 |
| deepin-mutter          | 3.18.1.4 |
| deepin-wm              |   0.91.4 |
| libdui                 |    1.2.2 |
| dbus-factory           |   2.92.2 |
| go-lib                 |    0.4.3 |
| dbus-generator         |    0.6.4 |
| dde-daemon             |   2.93.2 |
| dde-control-center     |   2.91.3 |
| dde-session-ui         |   2.90.3 |
| dde-dock               |   2.90.2 |
| deepin-notifications   |    2.3.4 |
| deepin-menu            |   2.90.2 |
| deepin-feedback        |    0.9.4 |
| deepin-screenshot      |    3.1.4 |
| deepin-icon-theme      |  15.10.4 |
| dde-desktop            |   2.90.3 |
| dde-launcher           |   2.90.2 |
| startdde               |   2.92.2 |
| deepin-terminal        |    1.1.1 |

**Comment by felixonmars** [comment]
Looks like deepin-desktop-base was not updated for Beta1 yet.

**Comment by fasheng** [comment]
Yep, let's wait for a while..

**Comment by felixonmars** [comment]
:/ Looks like deepin-desktop-base's Makefile wants to install deepin-version into /usr/lib/deepin, while other components still read the old path.

**Comment by fasheng** [comment]
I'm not sure, but the previous commit is OK
https://github.com/linuxdeepin/deepin-desktop-base/commit/6834ddd89d5bf8c9b792b6e7b90a7f4f4360dc70

**Comment by felixonmars** [comment]
Oh, I see... Thanks :P

Now the whole package set is available on [community-testing] except deepin-feedback, which I'll need some time to investigate. (We didn't enable similar functionality of e.g. Firefox).

**Comment by fasheng** [comment]
Cool :)

**Comment by fasheng** [comment]
dde-daemon -> 2.93.3

**Comment by fasheng** [comment]
Well, another tags...

dde-daemon 2.93.4
dde-api 2.92.3
deepin-wm-switcher 0.0.2
dde-control-center 2.91.4
dde-dock 2.90.3
dde-launcher 2.90.3
libdui 1.2.3

**Comment by fasheng** [comment]
Release candidates of Deepin 15 RC.

| Project                |    New Tag | Commit                                   |
|------------------------|------------|------------------------------------------  |
| go-gir-generator       |      0.9.1 | 6e53a3b74f2076b2f472920cd2bc1ae4752e0608 |
| deepin-artwork-themes  |    15.12.2 | 6c1c4f5bcbe070337352f634f8473a76e3efe59c |
| deepin-file-manager    |      0.1.4 | e27df5e5756868ae48e4a7f389cf788b544b13c6 |
| deepin-manual          |      1.0.3 | e31227e612a758de95ce3597c79b63314e9cdbac |
| deepin-screenshot      |      3.1.5 | d4df8f706e794e7647e72b7f74d7c086ac87ee41 |
| dde-account-faces      |     1.0.10 | 799e6aa0605167bab6b283aa1114c8aee555a45f |
| deepin-gtk-theme       |    15.12.2 | 29192a492361a46dfc893f5b4fd603f0510d6fa5 |
| deepin-icon-theme      |    15.10.5 | 61dad76298c40f23a625ef51be038482124474cf |
| dde/dde-api            |     2.92.4 | 9d927e1a74a684edea6d7d80bca096952355c75b |
| dde/dde-control-center |     2.91.5 | e5e508e4b4c69b687c28705445d8343ae4925a84 |
| dde/dde-daemon         |     2.93.5 | e321b178ebecba3148425c1ecc6407e1f15940db |
| dde/dde-desktop        |     2.90.4 | 346ec548435aec6f0fcba24dc612dd6bcf6dd77e |
| dde/dde-dock           |     2.90.4 | b741b794f6e9c95d42e7d539d66ee69641fcaf33 |
| dde/dde-launcher       |     2.90.4 | 0aebb088312ab42227610c0f6af5a9369f38c6a9 |
| dde/dde-session-ui     |     2.90.4 | bd11830f3f60d170866b9b245a15e890e0b32b3c |
| deepin-desktop-base    | 2015.12.19 | af086a257aafc81a854dfe7accd9e5600b849960 |
| deepin-desktop-schemas |     2.91.3 | 9f642b875d470a6e6671427b0164e207a322ac40 |
| deepin-metacity        |   3.18.1.2 | e949254c20433ee2d58d03f0b140cccb1ef092a6 |
| deepin-mutter          |   3.18.2.1 | 319cede09f5c969c8fa9bf12d5acc80cb60c1788 |
| deepin-notifications   |      2.3.5 | 2cbf1ede06fc660b5ee6754ded4eb5df9ad30cf0 |
| deepin-wm              |     0.91.6 | f805bcb65bc2325869af708093a1bf4c2d577883 |
| deepin-wm-switcher     |      0.0.4 | d253762b0b8881540ddf8f12458603a4dccf108a |
| dde/libdui             |      1.2.4 | 21b651fef3a2242a98b584fef510a4b6b2e50320 |
| dde/startdde           |     2.92.3 | c1f402970794df59f34211157fdeb465748bf54f |
| dbus-factory           |     2.92.3 | bef8c791e07beb144312b0eee83b00d1c7f68618 |
| deepin-qml-widgets     |      2.3.2 | a98e7a184e3c37b4535e91240b42356eab26c728 |
| go-lib                 |      0.4.4 | c276a48ce147db8cba1951da6164f8979d021cb4 |

**Comment by fasheng** [comment]
```
deepin-icon-theme -> 15.12.21 [latest 78ed4aaca5fd93a756ed461d07ec1bff6d80dc3f]: bugfix: icon cannot be found (4 hours ago) <Hualet Wang>
```

**Comment by fasheng** [comment]
dde-control-center -> 2.91.6
libdui -> 1.2.5

**Comment by fasheng** [comment]
dde-dock 2.90.5

**Comment by felixonmars** [comment]
deepin-wm-switcher -> 0.90.0

**Comment by felixonmars** [comment]
deepin-metacity -> 3.18.1.3

**Comment by felixonmars** [comment]
deepin-mutter -> 3.18.2.2

**Comment by fasheng** [comment]
Deepin 2015 Final tags

| Project                |  New Tag | Commit                                   |
|-------------------------|---------------|------------------------------------|
| deepin-file-manager    |    0.1.5 | ba4fa578eda40c0c9495c40eee71712bb9fbbd7c |
| deepin-manual          |    1.0.4 | e31227e612a758de95ce3597c79b63314e9cdbac |
| deepin-screenshot      |    3.1.6 | 2d196a2f4d5669b7d93343fdfeb799b3784fc937 |
| deepin-terminal        |    1.1.2 | c5cf72a15982ca4819565a1e0e8910c77107a044 |
| deepin-gtk-theme       |  15.12.3 | d3bb68d08019c30fd33c6d34ae6a9b58a13f2521 |
| deepin-icon-theme      | 15.12.22 | 1f65508f0081d3b6010d329203acc48e6d8845f1 |
| dde/dde-api            |    3.0.0 | 6044ee738f07489eb398d0d50482bf7d0a75961b |
| dde/dde-control-center |    3.0.0 | a798fd63c064cc8e844a067aad267e5b3856282c |
| dde/dde-daemon         |    3.0.0 | 98c01be10c3aa1eeae817931b05e1cf14830229c |
| dde/dde-desktop        |    3.0.0 | 0e06b580a24b88a20e48e7c700c51cd99e52687b |
| dde/dde-dock           |    3.0.0 | 08eb82d240ae97f2b9f609f68f11a2b9fbbb6ce7 |
| dde/dde-launcher       |    3.0.0 | 1c21d2928d94a6174823c7dbfdc63d41eba03ce3 |
| dde/dde-session-ui     |    3.0.0 | f903bdb804b42b7992164b7e8426be65c002659d |
| deepin-desktop-schemas |    3.0.0 | ee81cab5fc253c0af9bd5ea3dbcf403110db8776 |
| deepin-menu            |    3.0.0 | 269c33fe1714349930d1b893aa5f3a51a1d3acfa |
| dde/libdui             |    1.2.6 | 4f142b16ed15b4f9137bc2e1c46b0a8351cd64e7 |
| dde/startdde           |    3.0.0 | 172c0d7ccc4ef1012eae51b3a87000c8063cfef6 |
| dbus-factory           |    3.0.0 | 46f48a8721c10f7e0dc38c069af48c47081a91e0 |
| go-lib                 |    0.4.5 | 703997907cf673760fee56a970a29eafb266a5ee |

New commit/tag for `deepin-desktop-base` is in progress...

**Comment by felixonmars** [comment]
These four seems missing:

deepin-metacity 3.18.1.4
deepin-mutter 3.18.2.3
deepin-wm 1.0.0
deepin-wm-switcher 1.0.0

**Comment by fasheng** [comment]
:+1:

**Comment by felixonmars** [comment]
Now I am waiting for the tags being synced to github...

**Comment by felixonmars** [comment]
deepin-wm 1.0.1

**Comment by fasheng** [comment]
deepin-file-manager 0.1.6
dde/dde-api 3.0.1
dde/dde-control-center 3.0.1
dde/dde-daemon 3.0.1
dde/dde-desktop 3.0.1
dde/dde-dock 3.0.1
dde/dde-launcher 3.0.1
dde/dde-session-ui 3.0.1
deepin-desktop-base 2015.12.29
dstore/appstore-webapp 4.0.4
dstore/deepin-appstore 4.0.4
deepin-installer 1.3.18
go-lib 0.4.6
go-gir-generator 0.9.2

**Comment by fasheng** [comment]
deepin-desktop-base 2015.12.30
deepin-feedback 1.0.1
deepin-icon-theme 15.12.23
dde/dde-daemon 3.0.2
dde/startdde 3.0.1

**Comment by fasheng** [comment]
dbus-factory 3.0.1
dde/dde-control-center 3.0.4
dde/dde-daemon 3.0.3
dde/dde-desktop 3.0.3
dde/dde-dock 3.0.2
dde/dde-launcher 3.0.2
dde/dde-session-ui 3.0.4
dde/dde-workspace 2.90.4
dde/libdui 1.2.7
dde/startdde 3.0.2
deepin-file-manager 0.1.8
deepin-gtk-theme 15.12.4
deepin-icon-theme 15.12.24
deepin-menu 3.0.1
deepin-metacity 3.18.1.5
deepin-mutter 3.18.2.4
deepin-wm-switcher 1.0.1

**Comment by fasheng** [comment]
deepin-metacity 3.18.1.6

**Comment by felixonmars** [comment]
deepin-social-sharing 1.1.2

**Comment by fasheng** [comment]
deepin-nautilus-properties 3.14.3

**Comment by trubesv** [comment]
Hi,

Thanks for your great work.
Why the applications disappear from the dock after an upgrade?

Vincent

**Comment by fasheng** [comment]
You mean the upgrade of deepin-dock/deepin-daemon? Maybe is a upstream  issuse, will report it later.



2016年1月15日 01:21, 01:21，在 Vincent <notifications@github.com> 已写:
>Hi,
>
>Thanks for your great work.
>Why the applications disappear from the dock after an upgrade?
>
>Vincent
>

**Comment by trubesv** [comment]
No, everytime I do a package upgrade, let's say chromium for instance.

If it's in the dock, it gets deleted from it after the update, I have to
add it myself again.

I had this issue from the beginning, back when Deepin was on metakcahura
repo. :/

I'm still a great fan of DDE, I am really enjoying it, keep up the awesome
job. <3

Cheers,
Vincent

**Comment by felixonmars** [comment]
@trubesv I believe it's https://github.com/fasheng/arch-deepin/issues/225

**Comment by fasheng** [comment]
deepin-file-manager 0.1.9
deepin-screenshot 3.1.7
deepin-gtk-theme 15.12.5
deepin-icon-theme 15.12.25
dde/dde-api 3.0.3
dde/dde-control-center 3.0.6
dde/dde-daemon 3.0.6
dde/dde-desktop 3.0.4
dde/dde-dock 3.0.3
dde/dde-launcher 3.0.3
dde/dde-session-ui 3.0.5
deepin-menu 3.0.2
deepin-metacity 3.18.1.7
deepin-wm 1.0.2
dde/libdui 1.2.9
dde/startdde 3.0.3
deepin-installer 1.3.20

**Comment by fasheng** [comment]
dde-control-center 3.0.7
dde-session-ui 3.0.6

**Comment by fasheng** [comment]
dde-daemon 3.0.7

**Comment by fasheng** [comment]
dde-api 3.0.4
dde-daemon 3.0.8

**Comment by fasheng** [comment]
dde-launcher 3.0.4

**Comment by fasheng** [comment]
deepin-file-manager 0.1.10
deepin-terminal 1.1.3
deepin-gtk-theme 15.12.6
deepin-icon-theme 15.12.26
depin-api 3.0.5
depin-control-center 3.0.8
depin-daemon 3.0.9
depin-desktop 3.0.5
depin-dock 3.0.4
depin-launcher 3.0.5
depin-session-ui 3.0.7
deepin-desktop-schemas 3.0.2
deepin-metacity 3.18.1.9
deepin-mutter 3.18.2.5
deepin-wm 1.0.3
libdui 1.2.10
dbus-factory 3.0.2
go-lib 0.4.7

**Comment by fasheng** [comment]
deepin-file-manager 0.1.10
deepin-terminal 1.1.3
deepin-gtk-theme 15.12.6
deepin-icon-theme 15.12.26
depin-api 3.0.5
depin-control-center 3.0.8
depin-daemon 3.0.9
depin-desktop 3.0.5
depin-dock 3.0.4
depin-launcher 3.0.5
depin-session-ui 3.0.7
deepin-desktop-schemas 3.0.2
deepin-metacity 3.18.1.10
deepin-mutter 3.18.2.5
deepin-wm 1.0.3
libdui 1.2.10
dbus-factory 3.0.2
go-lib 0.4.7

**Comment by fasheng** [comment]
deepin-terminial 1.1.4

**Comment by fasheng** [comment]
Welcom @oberon2007

**Comment by fasheng** [comment]
dde/dde-control-center 3.0.9
dde/dde-dock 3.0.5
dde/dde-launcher 3.0.6
dde/dde-session-ui 3.0.8
deepin-movie 2.2.3
deepin-wm 1.0.4
dde-daemon 3.0.11
dde/dd-api 3.0.6
go-lib 0.4.8

**Comment by fasheng** [comment]
Let's follow https://github.com/linuxdeepin/developer-center/issues/41 instead~
