### ISSUE TITLE
Don't work the Brightness keys + Power Key

### ISSUE THREAD

**Issue by kiritoxcii** [fasheng/arch-deepin#69]
It only happens to work with Gnome, maybe it's some configuration in the environment.

And the power key does not do what I select in the options, it just shutdown my laptop without any warning.

**Comment by felixonmars** [comment]
It works fine here, maybe something fixed upstream?

**Comment by fasheng** [comment]
Please remove OBS repository from `/etc/pacman.conf` and update packages from [community] like this:

```sh
sudo pacman -R dde-dock-applets
sudo pacman -Syyuu
```
It should solved this issue.
