### ISSUE TITLE
Binary /usr/bin/player conflicts with the same file in genymotion

### ISSUE THREAD

**Issue by FiveYellowMice** [fasheng/arch-deepin#70]
Installing from unofficial repo, however pacman reports file conflict of /usr/bin/player.
A work around may be changing the file name in the package.

**Comment by mmetak** [comment]
I've changed the symlink name from /usr/bin/player to /usr/bin/qtav-player in qtav-1.6.0-3.
Should fix it...

**Comment by fasheng** [comment]
Looks this issue was fixed now, close.
