### ISSUE TITLE
Deepin 'introduction' hangs.

### ISSUE THREAD

**Issue by avidmills** [fasheng/arch-deepin#72]
Going through the introduction, everything works up until "Let's drag the other icon on the first icon to generate 'application group'".  At that point, there is nothing to drag, and nothing to satisfy it to move onto the next step.  I have to force close the introduction and just start using the system.

**Comment by fasheng** [comment]
Thanks or reporting, this is a upstream issue of dde-guide.

**Comment by fasheng** [comment]
We will never see Deepin Guide from now on~
