### ISSUE TITLE
Windows have a blue titlebar

### ISSUE THREAD

**Issue by jannickfahlbusch** [fasheng/arch-deepin#74]
Since the latest update, all of my windows have a bad looking blue title bar.

I think, this comes from the dependency of metacity2 instead of metacity-ubuntu.

Is there a way, to prevent this behaviour? 

Here is a screenshot:
![deepinbildschirmfoto20150712190754](https://cloud.githubusercontent.com/assets/8135397/8638920/9b04c684-28c9-11e5-8479-dbe45969187e.png)

**Comment by mmetak** [comment]
One user on DDE thread on archlinux's forum asked me about 'vanilla' metacity package so I tried to build with it, but it appears there is some issue with it so I've reverted it back to metacity-ubuntu and I've also updated some other packages. Can you please update you packages and report if the issue still persists?

**Comment by jannickfahlbusch** [comment]
Yeah, your update solved my problem.

Thank you and keep on, with this great work!
