### ISSUE TITLE
where is deepin settings?

### ISSUE THREAD

**Issue by antsuke42** [fasheng/arch-deepin#75]
where is the directory where deepin saves its settings? or how does deepin save the settings?

**Comment by mmetak** [comment]
Settings are stored in "~/.config/{dde,deepin,desktop,dock,launcher,...}", and they're just text files.
".dde-dock-applets.ini" hidden file in your user home folder.
And, your custom theme when you change something, is stored in "~/.local/share/personalization/".

I wish they would just put all the configs in one place, like "~/.config/deepin/{dock,desktop,etc.}"

**Comment by fasheng** [comment]
I will advice the programmers to adjust the config path. Besides, about the topic question, many dde related settings stores in gsettings with prefix path `com.deepin`.

**Comment by antsuke42** [comment]
thank you-

**Comment by oberon2007** [comment]
I still could not find, yet where the info of the user icon and the settings for lightdm-deepin-greeter go ... Could you tell me that, too, please?

**Comment by fasheng** [comment]
Have a look at ```/var/lib/AccountsService/``` :)

**Comment by oberon2007** [comment]
Thanks! :)
