### ISSUE TITLE
Right click then left click broken

### ISSUE THREAD

**Issue by avidmills** [fasheng/arch-deepin#76]
When I right click on anything in the dock, or in the applications menu, I am then unable to left click on the drop down menu. I can hover over and highlight the different options, which then allows me to use the enter key and make my selection, but clicking it does not work.

**Comment by fasheng** [comment]
Strange issue, could you reproduce it each time?

**Comment by avidmills** [comment]
Yes, it seems to be any time I open a right click menu, I am unable to left click anywhere, I have to use the keyboard and enter or escape to exit the menu. It could be an arch related problem, but that doesn't seem super likely. Maybe I just have something installed incorrectly for my laptop drivers.

**Comment by mmetak** [comment]
I experienced the same issue the other day. Though I was just trying the -git testing packages.
When I have more time I'll install stable and test it.

**Comment by shakyj** [comment]
I have this same issue then after a while left click anywhere but the dock stopped working and the dock stayed visible even in smart mode.

When you right click and the menu pops up you can chose your setting by hovering over it with the mouse and hitting the enter key on your keyboard so the menu is working, just the click isn't being detected. I have also tried a USB mouse and it still won't recognise the click.

I am on a thinkpad with gnome and i3 installed too and they both work fine so I don't think it's the drivers.

**Comment by fasheng** [comment]
Well, I have the issue after updating full system, too. Everything fine in the upstream, so maybe caused by the different building depends, e.g. qt.

**Comment by thedeli** [comment]
I have same issue. I wrote on arch forum page too..

**Comment by japerfecto** [comment]
I am a new user, I installed Deepin today, and I have this problem.

**Comment by lukadisanto** [comment]
I have the same problem

**Comment by tgharib** [comment]
Same problem. I just installed Deepin today on Arch Linux.

**Comment by fasheng** [comment]
Thanks for the reports. This should be caused by a `QWidget::nativeEvent` issue in Qt 5.5.0, which make `deepin-menu` could not catch mouse event correctly. And we are just searching for solutions now...

**Comment by thedeli** [comment]
Thanks :) :+1:

**Comment by oberon2007** [comment]
Any progress I this? I have that problem, too, and it is quite a showstopper... :-/

**Comment by fasheng** [comment]
Sorry for the long time waiting. This issue could not reproduced in official distro and the developer are working hard for Deepin2015 now, so there is just no enough energy to solve the problem which need rewriting the implementation.

I toke time to build a demo and reported a bug to Qt, hope they will pay attention to it.

https://bugreports.qt.io/browse/QTBUG-48472

**Comment by oberon2007** [comment]
Thank you so much! :)

**Comment by fasheng** [comment]
Thanks to tha Qt developer Gatis Paeglis's tips, this issue is caused by Qt which configured with xinput2. I have wrote a patch to @fellxonmars that tested OK locally. We will receive package update for deepin-menu later :-)

**Comment by oberon2007** [comment]
Great news! :)
