### ISSUE TITLE
Time fonts

### ISSUE THREAD

**Issue by avidmills** [fasheng/arch-deepin#78]
Something screwed up with my clock.  It still functions fine, (aside from an incorrect clock setting, but that isn't related to deepin).  Any idea?

![deepinscreenshot20150805150315](https://cloud.githubusercontent.com/assets/12877032/9099153/acb68f00-3b8b-11e5-8b75-d96a365aff82.png)

**Comment by fasheng** [comment]
Please remove OBS repository from `/etc/pacman.conf` and update packages from [community] like this:

```sh
sudo pacman -R dde-dock-applets
sudo pacman -Syyuu
```
It should solved this issue.
