### ISSUE TITLE
network problem

### ISSUE THREAD

**Issue by lukadisanto** [fasheng/arch-deepin#79]
After last update (yesterday) I can't go on internet with wifi.
When I switch from wifi to lan I go on web but I do not see internal lan client.
I must restart the system with lan cable inserted and the internet works
If I use gnome everything works fine

**Comment by fasheng** [comment]
Upstream issue.

The version of NetworkManager in archlinux(1.0.4) is newer than deepin 2014(0.9.8), and the new network daemon will be released for deepin-2015 to fix the interface compatibility problems.

**Comment by lukadisanto** [comment]
So I simply wait for update, right?
Do you know when the update will released?

**Comment by fasheng** [comment]
About 2 months later.

**Comment by fasheng** [comment]
Solved in `deepin-control-center-2.91.6-1`,  `deepin-daemon-2.93.5.20151221-1`.
