### ISSUE TITLE
Unable to install:download.opensuse.org : Maximum file size exceeded

### ISSUE THREAD

**Issue by MOZGIII** [fasheng/arch-deepin#80]
Have this during installation.
Follows https://wiki.archlinux.org/index.php/Deepin_Desktop_Environment

```
:: Retrieving packages ...
error: failed retrieving file 'dde-workspace-2.1.20150521160615-3-x86_64.pkg.tar.xz' from download.opensuse.org : Maximum file size exceeded
warning: failed to retrieve some files
error: failed retrieving file 'lightdm-deepin-greeter-2.1.20150521160615-3-x86_64.pkg.tar.xz' from download.opensuse.org : Maximum file size exceeded
warning: failed to retrieve some files
error: failed to commit transaction (download library error)
Errors occurred, no packages were upgraded.
```

**Comment by fasheng** [comment]
Please setup `wget` as default download tool by removing comment from line `XferCommand = /usr/bin/wget --passive-ftp -c -O%o %u` in `/etc/pacman.conf`, then try again.

**Comment by MOZGIII** [comment]
I already figured out how to download files from the mirror. However, if you need me to try this to get more info on topic, I still could try doing so.
I'm interested myself in knowing what's going on and what causes the problem. Somehow mirror just works. Is this problem somehow caused by Open Suse's Build Server implementation?

**Comment by fasheng** [comment]
I'm not sure, but using wget will avoid such problems from my experimence.

**Comment by fasheng** [comment]
Well, `wget` not works this time, looks like OBS did not update db file after archlinux packages rebuilded.

**Comment by fasheng** [comment]
Please remove OBS repository from `/etc/pacman.conf` and update packages from [community] like this:

```sh
sudo pacman -R dde-dock-applets
sudo pacman -Syyuu
```
