### ISSUE TITLE
wallpaper not updating

### ISSUE THREAD

**Issue by oberon2007** [fasheng/arch-deepin#81]
First of all, thank you for your amazing work, fasheng! :)
I am running this on a manjaro system now and apart from the right-click/left-click issue that you are already aware of I am having problems with changing the wallpaper:
Clicking a different wallpaper gives a little black frame around the selection and changes the thumbnail under 'Theme Custom' at the top of 'Personalization' but does not actually update the background. It will be applied only at the next login.
When I try to change my selection a second time during the same session I will get neither the black frame around the thumbnail nor a preview at the top. So it seems that the first change somehow is not completed and inhibits a second one.
When I clilck on the magnifying glass in the Custom Theme preview I will see an amplified piece of the desktop with the default blue background.

**Comment by fasheng** [comment]
This is caused by the broken gsettings signal issue since glib2.43. I give a patch for startdde(rel=5) now,, and tested ok locally.

But OBS could not build it with error message `nothing provides zeromq needed by libteam`,  do you have any idea about it, @mmetak ?

**Comment by mmetak** [comment]
With latest update libteam-1.17-1 (networkmanager dependency) needs zeromq which is in community repo. I'll have to import zeromq, libpgm, libsodium and acsiidoc to OBS.

**Comment by oberon2007** [comment]
That sounds like a solution is round the corner :) Thank you!

**Comment by fasheng** [comment]
@mmetak How about move netwokmanager to optional depends to avoid OBS's checking? In fact, dde-daemon could run without it.

**Comment by mmetak** [comment]
@fasheng OK, I've moved it to optdepends.

**Comment by oberon2007** [comment]
fixed for me. thank you!
