### ISSUE TITLE
deepin trademark question

### ISSUE THREAD

**Issue by oberon2007** [fasheng/arch-deepin#82]
Forgive me if this is the wrong place to contact you about this but I could not find an email address...
I am thinking about working on a community release of manjaro with the deepin DE but I am not sure if there are any copyright concerns opposing this plan.
This github page here states that the content is GPL, so I would understand that as favourable for what I would like to da, but what confuses me a little is that I see "deepin TM" on the start screen of lightdm-deepin-greeter (I think that's where it is...)
Could you kindly clarify what the consequences of this trademark status are?
Does that mean a release by another distribution would not be allowed to be called e.g. "Manjaro-deepin"? Or would there be a problem altogether with such a project?
Needless to add of course that Manjaro is a 100% non-profit project.
Thank you.

**Comment by fasheng** [comment]
Yes, their is a registered Deepin trademark logo in left-bottom corner of ligthdm-deepin-greeter.

The GPL is a license that defines the terms of use for the code. A license does not serve the same function as a copyright or trademark and the GPL itself is designed for software not for logos or names[1].

So I'm afraid you could not change the trademark log in greeter to another one only when deepin provide special license for it.

Besides, there is no problem to port DDE to Manjaro or other distros. In fact, we welcome contributors to do such work and glade to provide helps ;-)

[1] http://opensourcematters.org/legal/trademark/trademark-faq.html

**Comment by oberon2007** [comment]
Thank you for the information. This sounds promising! ;)
