### ISSUE TITLE
extrem slowdown after login

### ISSUE THREAD

**Issue by oberon2007** [fasheng/arch-deepin#84]
Since yesterday's package update changing the wallpapers works fine, thank you!
BUT now a different issue has surfaced:
After login with lightdm-deepin-greeter the session takes forever until the dock appears and the session is usable - I am talking about 15-20 minutes!! After that everything seems perfectly normal.
Is there any helpful information I could provide for you?
Nothing helpful in .xsession-errors anyway
This happens equally in a live environment from a USB-stick and in Virtualbox (installed on a virtual hd)

**Comment by jannickfahlbusch** [comment]
Happens for me too. Seems strange as there are no logged errors.

**Comment by oberon2007** [comment]
Seems not related to lightdm. Launching the session with startx has the same result.

**Comment by jannickfahlbusch** [comment]
This is the whole content of my `.xsession-errors`-File:

```
** (pamac-tray:729): WARNING **: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

** (polkit-gnome-authentication-agent-1:739): WARNING **: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

** (zeitgeist-datahub:724): WARNING **: zeitgeist-datahub.vala:209: Error during inserting events: GDBus.Error:org.gnome.zeitgeist.EngineError.InvalidArgument: Incomplete event: interpretation, manifestation and actor are required




** (zeitgeist-datahub:724): WARNING **: zeitgeist-datahub.vala:209: Error during inserting events: GDBus.Error:org.gnome.zeitgeist.EngineError.InvalidArgument: Incomplete event: interpretation, manifestation and actor are required

** (zeitgeist-datahub:724): WARNING **: zeitgeist-datahub.vala:209: Error during inserting events: GDBus.Error:org.gnome.zeitgeist.EngineError.InvalidArgument: Incomplete event: interpretation, manifestation and actor are required
```

The file got created just after the start of X.org and got modified 17 Minutes later: 
```
Zugriff    : 2015-09-08 21:08:57.011367690 +0200
Modifiziert: 2015-09-08 21:25:57.432357883 +0200
Geändert   : 2015-09-08 21:25:57.432357883 +0200
```

**Comment by fasheng** [comment]
Thanks for the detailed report. The problem was soveld in dde-daemon(pkgrel=9) with a patch for go1.5.

**Comment by oberon2007** [comment]
Wonderful. That solves it. Thank you very much for the ultra-fast fix! :)
