### ISSUE TITLE
Moving some deepin software to [community]

### ISSUE THREAD

**Issue by felixonmars** [fasheng/arch-deepin#85]
Hi,

Today I started to add some deepin packages to the [community] repository, and my first goal is deepin-music. I have also updated pygtk with an upstream patch which should eliminate the need for deepin-pygtk.

In case I did anything wrong, I didn't make the first batch too big:
- https://www.archlinux.org/packages/community/x86_64/python2-deepin-utils/
- https://www.archlinux.org/packages/community/x86_64/python2-deepin-gsettings/

Instead of using sources for the deepin package, it would be more "natural" for an Arch package to build from upstream sources instead, so I chose to build from latest git commit at the moment. Please do let me know if you see any problems and/or enhancements.

Thank you very much for packaging Deepin software for Arch, and hopefully we can find a way to work together and target a larger audience by providing the great tools in official repositories.

**Comment by felixonmars** [comment]
Add some links:
- Update to pygtk: https://github.com/felixonmars/packages-mirror/commit/48d0b0c64763db08d11ced15228536fcdc849863
- PKGBUILD for python2-deepin-gsettings: https://github.com/felixonmars/community-mirror/blob/master/python-deepin-gsettings/trunk/PKGBUILD
- PKGBUILD for python2-deepin-utils: https://github.com/felixonmars/community-mirror/blob/master/python-deepin-utils/trunk/PKGBUILD

**Comment by fasheng** [comment]
It's really an amazing news for @metak and I. We planned to contribute Deepin packages to [community] repo about two years ago. And Deepin team managing all projects under github(mirror of cr.deepin.io like gitcafe) with tags, it will be more convenient to do such work now.

But a problem is that Deepin projects are not like Qt or Gnome, I mean they(DDE and deepin apps) always release independently and are not stable enough now, so sometimes the maintainer will have to update the git commit in PKGBUILD more frequently, and the maintainer must distinguish stable, unstable and next-release tags, too. So I using source file from deepin offical debian repos and generate PKGBUILDs from templates automatically to avoid such issues for my less energy ;-)

One tips is that Deepin package team had the same question and they defined a file named `branches.json` in [pkg_debian](https://cr.deepin.io/#/admin/projects/pkg_debian) to help to build packages automatically, but it's still not general now.

Another tips is that @metak maintainer a OBS repo named [arch-deepin-git](https://build.opensuse.org/project/show/home:metakcahura:arch-deepin-git), you could have a look at it.

Thanks for the porting work for Deepin, waiting for your good news later ;-)

**Comment by oberon2007** [comment]
@felixonmars for me, too, this is great news, as I am currently trying to put together a version of manjaro with the deepin-DE. The manjaro-repos are inheriting your new packages as they appear. At the same time I am still using @mmetak 's custom repo.
At the moment the situation is a bit confusing for me, as some packages are available from both sources now, partly in different versions.
What is our perspective now: Is your plan to provide the complete list of the deepin-group?
What will I need to know about dependencies?
One possible solution for us would be to not use @metak 's repo at all but use the new arch packages instead and add missing packages in the manjaro overlay ... ...
Thank you for your work!

**Comment by felixonmars** [comment]
Hi @oberon2007, as discussed with @fasheng, I am going to wait for the next major DDE release to package most of the DDE core components. Currently I am only moving some individual softwares like deepin-screenshot, deepin-music, deepin-movie, etc.

If you are going to package the whole deepin group now, I would suggest you to keep on @mmetak's repo for now, as there may be hidden problem in different versioning of dependencies. You can put @mmetak's repo above the regular Arch/Manjaro repos so the correct packages would be picked up.

**Comment by oberon2007** [comment]
Yes, that sounds great! Thank you for the clarification. :)

**Comment by mmetak** [comment]
Hello everyone. ;-)
Since @felixonmars moved some packages to community repo I've decided to remove those already moved packages from arch-deepin repo in OBS. Already removed:
- deepin-pygtk (not needed anymore, patch merged upstream, replace it with pygtk from arch repos)
- deepin-screenshot *
- deepin-music *
- deepin-menu *
- deepin-qml-widgets *
- python2-deepin-gsettings *
- python2-deepin-ui *
- python2-deepin-utils *
- qtav *
- python2-peewee *

* (replace/reinstall it with package from arch repos)

As packages get imported into community repo, they'll be removed if possible from arch-deepin repo in OBS to reduce unnecessary duplication. If there are any problems with obs packages, please report them here.

**Comment by oberon2007** [comment]
Thank you very much! :)

**Comment by felixonmars** [comment]
Update:

deepin-social-sharing added as optdepend of deepin-screenshot

**Comment by mmetak** [comment]
- deepin-social-sharing *(replace/reinstall it with package from arch repos)
- deepin-dbus-generator *(replace/reinstall it with package from arch repos)

**Comment by fasheng** [comment]
Cool!

**Comment by MetaK** [comment]
@mmetak here is a problem. Un a spanish user from spain, and i have ur account linked to my account. I dont know why its hapenning , and i dont know how erase this problem, i can change ur password account because my email is being used like ur mail dirección, So all the coments and all the posts u do or someone do to u are being sending to my email.

U know something about this? Its a big problem and i dont wanna cause u some trouble by error.

**Comment by MetaK** [comment]
Im A spanish user*  

Contact me @mmetak please

**Comment by felixonmars** [comment]
Update:

deepin-game added to [community] with dependencies python2-deepin-storm and python2-jswebkit.

**Comment by fasheng** [comment]
@MetaK Really sorry for the wrong username in my first post for I always write message in the external editor from Firefox. Please don't mind it...

But really have no idea how you could change @mmetak's account password.

**Comment by MetaK** [comment]
Im getting all emails from mmetak conversations, it includes that i can change the password with my email! Github error?

**Comment by oberon2007** [comment]
This sounds quits concerning actually ... I think you (and/or @mmetak) should definitely open a [vulnerability submission](https://bounty.github.com/submit-a-vulnerability.html) about this with Github!

**Comment by mmetak** [comment]
@MetaK Don't know what exactly is going on, but I've changed my password just in case. If you're receiving those emails then you should definitely report them as @oberon2007 said. I haven't received any warnings nor have I noticed anything weird.

@felixonmars & @oberon2007 Great. deepin-game-center and python2-jswebkit also removed. deepin-gettext-tools won't be published in obs repo any longer, use the one in community repo.

**Comment by oberon2007** [comment]
Great! I will make another ISO test-build with all the new packages in the near future :)

**Comment by mmetak** [comment]
- deepin-terminal and deepin-vte are now removed.
- python2-deepin-vte dependency instead of deepin-vte

replace/reinstall deepin-terminal with package from arch repos

**Comment by felixonmars** [comment]
@mmetak Update: coffee-script has been moved to [community].

**Comment by felixonmars** [comment]
* deepin-movie (2.3 branch) moved to [community]

**Comment by mmetak** [comment]
- coffee-script not published in arch-deepin repo any more, use the package from [community] if needed.
- deepin-movie removed, use the package from [community]... along with it I've also removed its old dependencies python2-ass, python2-pysrt, python2-setproctitle, python2-xpybutil...

(the OBS repo is scheduled for rebuild and changes will apply once it finishes...)

**Comment by oberon2007** [comment]
At the moment dependencies seem to make it impossible to install deepin-movie (arch) and group deepin at the same time: https://github.com/fasheng/arch-deepin/issues/93

**Comment by jannickfahlbusch** [comment]
The installment of deepin and deepin-extra is impossible at the moment.

It is only possible with the `--force`-Flag of pacman.

**Comment by oberon2007** [comment]
Today several packagea seem to have disappeared completely... Are you currently re-structuring all that? So, should I wait a while before I attempt to re-install?

**Comment by mmetak** [comment]
@oberon2007 @jannickfahlbusch 
I've modified most of the pkgbuilds to use git sources and I've also updated most of the packages.
(git sources are disabled by default to work with OBS, but should be easily enabled for those who wish to rebuild packages on their own locally) Also, there's no more dde-qml-dbus-factory package (previously split deepin-dbus-factory) in arch-deepin repo, only deepin-dbus-factory should be pulled from community repo. I've also bundled those source golang packages into one to make it easier to maintain. Many changes... probably still things to fix. @oberon2007 It would be helpful if you could re-install and report errors.

**Comment by oberon2007** [comment]
Great, thanks! I will try later tonight :) I now get only 16 pkgs in group deeping, correct?
```
:: Repository community
   1) deepin-menu  2) deepin-social-sharing  3) python2-deepin-ui
   4) python2-deepin-utils
:: Repository home_metakcahura_arch-deepin_Arch_Extra
   5) dde-account-faces  6) dde-dock-applets  7) dde-workspace
   8) deepin-artwork  9) deepin-artwork-themes  10) deepin-compiz
   11) deepin-default-gsettings  12) deepin-gtk-theme
   13) deepin-icon-theme  14) deepin-notifications  15) libdeepin-webkit
   16) startdde
```
plus these 5 in deepin-extra:
```
   1) deepin-game  2) deepin-movie  3) deepin-music
   4) deepin-screenshot  5) deepin-terminal
```

**Comment by oberon2007** [comment]
Well, installation went without problem (installed complete deepin and deepin-extra group plus dde-control-center and lightdm-deepin-greeter). But when I start the session I get a little popup with "Dock failed to start, because Compiz is not enabled". The desktop icons are there, on an empty black background and after a while I am thrown back the lightdm-deepin-greeter.

**Comment by fasheng** [comment]
Wow, looks I missed interesting news that metak updated DDE packages to 2.90.x :+1: 

@oberon2007  A patch just applyed to startdde to fix `compiz` as the default window manager, it should fix such issue. Please update and try again.

I updated to latest arch-deepin pkgs, just works fine besides the conflicts issue between `dde-qml-dbus-factory`/`dde-go-dbus-factory` and `deepin-dbus-factory`. But it should not be a big problem.

The latest Deepin 2015 packages will be synced to github later, and maybe it's time to port them to Arch now  :)

**Comment by oberon2007** [comment]
Very cool! :) My new build seems to work really well! What surprised me is that there is suddenly an additional user by default of the name "git". Where does this come from? The good news is that I am now able to create a new user! ;)
Properties of Desktop icons can be displayed now, but now right-click > delete function is gone again...
Thank you all for your great work!

**Comment by fasheng** [comment]
Thanks all, most of the Deepin packages exists in [community] now.
