### ISSUE TITLE
double declaration of custom background

### ISSUE THREAD

**Issue by oberon2007** [fasheng/arch-deepin#86]
I am having problems preconfiguring the background for a new user.
The background image seems to be declared in two places:
**/var/lib/AccountsService/users/username** and in **/home/username/.local/share/personalization/themes/Custom/theme.ini** Is that correct?
In any case deepin tends to regress to the default theme until changes are applied again.
So could you point me to where the switch between Deepin theme and Custom theme is stored?
Thank you.

**Comment by fasheng** [comment]
The setting in AccountsService is used to change the login background in lightdm, but still not implemente now. So the right place to store themes are `~.local/share/personalization/themes`.

**Comment by oberon2007** [comment]
Ok, thanks. But then changing the settings in that file alone does not change the theming! The default remains until I open the settings GUI and change something. So my question is still, where is the switch from Deepin to Custom theme? ;)

**Comment by fasheng** [comment]
Just change the gsettings value in `com.deepin.dde.appearance.theme` :)

**Comment by oberon2007** [comment]
Hmm. I can't seem to find a file of that name anywhere! ??

**Comment by fasheng** [comment]
I mean you have to apply Custom theme by changing the gsettings value in shell `gsettings set com.deepin.dde.appearance theme 'Custom'` ;-)

**Comment by oberon2007** [comment]
But where does that setting go? It must be written in a file somewhere, no? Or will I have to run a script for that on the first session?

**Comment by oberon2007** [comment]
ah. i think i got it ;) /usr/share/glib-2.0/schemas :)

**Comment by oberon2007** [comment]
Sorry. Not enough GNOME experience here :blush:

**Comment by fasheng** [comment]
You got it :D

**Comment by oberon2007** [comment]
Well almost ...
```
$ gsettings set com.deepin.dde.appearance theme 'Custom'
No such schema 'com.deepin.dde.appearance'
```
or
```
$ gsettings set com.deepin.dde.appearance.theme 'Custom'
Usage:
  gsettings [--schemadir SCHEMADIR] set SCHEMA[:PATH] KEY VALUE

Set the value of KEY to VALUE

Arguments:
  SCHEMADIR A directory to search for additional schemas
  SCHEMA    The name of the schema
  PATH      The path, for relocatable schemas
  KEY       The key within the schema
  VALUE     The value to set
```
???
The only file that looks actually relevant is ``com.deepin.dde.personalization.gschema.xml``

**Comment by oberon2007** [comment]
When I try to open Desktop Preferences from the Menu I get an Error 'Desktop Manager is not active'. Am I missing a package, maybe? Also when I open Personalization from the Settings palette and change background, xcursor-theme and icons several time, the changes stopp being applied after two or three of those actions and I have to re-log.
The latest setting are not written in .local/share/personalization/themes/Custom but are effective after relogging.
Are there supposed to be local schemas in ~ also?
Sorry for all those questions ... ... ;)

**Comment by oberon2007** [comment]
Interesting! I just found this...
99_deepin-default-gsettings.gschema.override 8-D

**Comment by fasheng** [comment]
I see, the gsetting path I used only exists in Deepin 2015...

**Comment by oberon2007** [comment]
Ok :-) looking forward to that! Would Deepin 2015 somehow be accessible already for experimenting?

**Comment by fasheng** [comment]
Well, Deepin 2015 released alpha1 about two months ago and we plan to port it to archlinux after the stable version out.
