### ISSUE TITLE
User trash dirs not created under manjaro

### ISSUE THREAD

**Issue by oberon2007** [fasheng/arch-deepin#87]
When I right click on a desktop icon selecting 'delete' or 'properties' does nothing while the other entries of the context menu work fine.

**Comment by fasheng** [comment]
The 'delete' action work fine for me, could you debug it by `killall dde-desktop; dde-desktop -f`?

The 'properties' issue is caused by the missing dependency `deepin-nautilus-properties`, I will package it later.

**Comment by oberon2007** [comment]
ok. sorry, it took me a while to get back to this. I get
```
** (dde-desktop:1797): WARNING **: _trash_files_async: Unable to find or create trash directory
```

**Comment by oberon2007** [comment]
I have
```
$ pacman -Qi nautilus
Name           : nautilus
Version        : 3.16.2-1
```
am I missing another package?

**Comment by fasheng** [comment]
I see, looks like you missing the trash folder, try to install `gvfs` package.

If not work, setup the trash folder manually:
```
mkdir ~/.local/share/Trash
mkdir ~/.local/share/Trash/files
mkdir ~/.local/share/Trash/info
chmod -R 700 ~/.local/share/Trash
```

**Comment by oberon2007** [comment]
gvfs was already installed.
Will try the handwork then ... ;)

**Comment by oberon2007** [comment]
Unfortunately that did not help either. Still the same error while
```
[manjaro@manjaro-deepin Trash]$ ls -la
total 0
drwx------ 4 manjaro users  80 Oct  7 17:01 .
drwxr-xr-x 6 manjaro users 120 Oct  7 16:59 ..
drwx------ 2 manjaro users  40 Oct  7 16:59 files
drwx------ 2 manjaro users  40 Oct  7 17:01 info
```

**Comment by oberon2007** [comment]
I have built a new ISO now and interesting, the delete now works suddenly. Properties are still not showing though...
Any additional information I could provide?

**Comment by fasheng** [comment]
`property` not works for that I had not push package `deepin-nautilus-property` to OBS yet.

About the `delete` issue, what you did to fix it, install gvfs or create trash folder manaully?

**Comment by oberon2007** [comment]
I see, thank you. The delete-problem has disappeared on the new ISO, I have no idea why. No manual folder creation anyway. And gvfs had been installed on the old one already, too ... Sorry, no helpful information here ;) but in any case it works now :D

**Comment by fasheng** [comment]
Thanks. I will upload deepin-nautilus-property to OBS after our repo manager sync code to github :)

**Comment by fasheng** [comment]
Hi, @mmetak 
I upload deepin-nautilus-properties, and follow your smart _service style as deepin-dbus-generator, but just build failed, do you have any idea?

btw, I found the arch-deepin:2015 repo in OBS, you have worked hard :+1: 

https://build.opensuse.org/package/show/home:metakcahura:arch-deepin/deepin-nautilus-properties

**Comment by mmetak** [comment]
@fasheng It failed because it was missing libnotify. I added it to makedepends and it builds fine.

**Comment by fasheng** [comment]
Good job ! I just got dizzy by the 'could not cd directory' problem and missed the point.

So people update dde-workspace will install deepin-nautilus-properties and will solve this issue.

**Comment by oberon2007** [comment]
Unfortunately this issue is back now. gvfs is installed and the Trash foldes created manually.
Also selecting an item in Nautilus and hitting Delete gives this error: ``can't be put in the trash. Do you want to delete it immediately?``
In debug mode the attempt to delete a desktop item still gives:
``** (dde-desktop:4018): WARNING **: _trash_files_async: Unable to find or create trash directory``

**Comment by oberon2007** [comment]
A search for "_trash_files_async" lists this page: http://blog.csdn.net/yuanchenglu/article/details/9719415 Maybe some helpful information for you there? ;)

**Comment by fasheng** [comment]
Really surprise! You just show me my colleague's blog, and he just standing behind me when I click it.

I will try to reproduct and report it to the developer  ;)

**Comment by oberon2007** [comment]
Seems I have solved this. The Trash needs to be created at /
Like this:
```
$ sudo mkdir -p /.Trash-1000/{expunged,files,info}
$ sudo chown -R $USER /.Trash-1000
```
I have no idea why this problem occurs now suddenly. It was not an issue one or two weeks ago...
Do you have any idea? It would be great if we find a way for me to not have to create the dirs manually ... ;)

**Comment by oberon2007** [comment]
This seems to be some sort of a mysterious Gnome-based problem. On the latest manjaro Gnome ISOs we find exactly the same behaviour...

**Comment by oberon2007** [comment]
Still investigating the trash issue... Looks like gvfs (gdaemonvfs) is checking for the default trash scheme. So my theory is that when a user account is created the /.Trash-1000 dir is not created, but at the same time gdaemonvfs is informed that this is the scheme to be applied. I think only that explains why all filemangers are expecting /.Trash-1000 and not ~/.local/share/Trash and then fail to move items to the trash because the directories where not actually created.
How are they supposed to be created in the first place??

**Comment by oberon2007** [comment]
This problem is still present.
To make the trash work on a fresh install I still have to run this manually:
```
userid=$(id -u $USER)
sudo mkdir -p /.Trash-$userid/{expunged,files,info}
sudo chown -R $userid /.Trash-$userid
```
8^}

**Comment by oberon2007** [comment]
I still have no idea how the Trash-dirs are supposed to be created automatically... or why it doesn't work in my environment.
