### ISSUE TITLE
cannot add a new user

### ISSUE THREAD

**Issue by oberon2007** [fasheng/arch-deepin#90]
when I click on the +-symbol in the control centre the form opens but when I try to enter the name for a new user, no letters are accepted but a tooltip box shows up saying "Username can not be empty".

**Comment by oberon2007** [comment]
Not sure if this is related, but ... is there a way in lightdm-deepin-greeter to login as root? I can not see a selection like in lightdm-gtk-greeter.

**Comment by fasheng** [comment]
Yes, edit the =/etc/lightdm/lightdm.conf= by your favorite editor and add this line:
```
greeter-show-manual-login=true
```

Then restart ligthdm and input username like root.

**Comment by oberon2007** [comment]
Great, thank you :)

**Comment by oberon2007** [comment]
unfortunately it does not make any difference ...
maybe any additional config needed for pam?

**Comment by fasheng** [comment]
Well, looks like lightdm-deepin-greeter does not support input username manually... Just ignore it.

**Comment by oberon2007** [comment]
so this means there is no way to login as root?

**Comment by fasheng** [comment]
Maybe, unless using `lightdm-gtk-greeter` or xinit.

**Comment by oberon2007** [comment]
ok. thanks.

**Comment by oberon2007** [comment]
Meanwhile the behaviour has changed:
I can enter a new username and the settings, and when I confirm the control center closes.
When I open it again, the new user is listed and it says "Account preparing...". That never changes and when I log out and back in the new user has disappeared again.

**Comment by oberon2007** [comment]
Latest version of control center doesn't appear to have an option "add new user" at all?

**Comment by fasheng** [comment]
Should solved now.
https://github.com/linuxdeepin/dde-daemon/commit/5b03428c7bea68fe09cd14eaddc331dbce1b009b
