### ISSUE TITLE
per user gconf

### ISSUE THREAD

**Issue by oberon2007** [fasheng/arch-deepin#91]
Excuse me, this is probably a quite dumb question... but I can't seem to figure out where the per user gconf settings are stored. For example when the user changes the dock option to "Classic mode".
Thank you for your patience ;)

**Comment by fasheng** [comment]
Do you mean `~/.config/dconf/user`?

**Comment by oberon2007** [comment]
Hm. So this means it will not be human readable?

**Comment by oberon2007** [comment]
So looks llike the way to pre-configure settings manually is via global override  in /usr/share/glib-2.0 right?

**Comment by fasheng** [comment]
yes, just follow the gsettings override files.

**Comment by oberon2007** [comment]
Thanks
