### ISSUE TITLE
Deepin installed, but completely unusable. 

### ISSUE THREAD

**Issue by fusion809** [fasheng/arch-deepin#92]
Hi,

I have installed the `deepin` and `deepin-extra` packages on my Manjaro VirtualBox Machine (VBM). and while I can start the Deepin DE without issue, the desktop background is pitch black and I can't open up any applications (including the Deepin Terminal). What's worse is that I can't open up tty1 with <kbd>Alt</kbd>+<kbd>F1</kbd> (by the way, if you're thinking I should try <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>F1</kbd>, well I can't as I am using Sabayon Linux as my host and that would open up tty1 on my Sabayon host and not the VM) and hence I cannot try to get some debugging information for ya with `journalctl -b | grep -i 'deepin'`. 

![1](http://i.imgur.com/DcWXPpZ.png)

Thanks for your time,
Brenton

**Comment by oberon2007** [comment]
Did you follow [this guide](https://wiki.archlinux.org/index.php/Deepin_Desktop_Environment) ?
For me a while ago it worked like that. At that time I used a basic fluxbox installation as a basis and installed deepin as a second session. Like that you can also check if your base installation is working at all.

**Comment by fusion809** [comment]
Yes I did follow that guide, to the letter. I ran `sudo pacman -S deepin deepin-extra` after adding the deepin repo to `/etc/pacman.conf`. After that I switched my LightDM greeter to Deepin and it made no difference, whenever I logged into Deepin I got this error.

**Comment by fasheng** [comment]
Looks like `/usr/bin/startdde`, `/usr/bin/deepin-compiz` and `/usr/lib/deepin-daeon/dde-session-daemon` did not run well. Could you preview workpace through <kbd>Super</kbd>+<kdb>s</kdb>?

I need more debug log about it. And I remember people should use <kbd>Host</kbd>key (typically the <kbd>Right Ctrl</kbd>) instead of <kbd>Ctrl</kbd>+<kbd>Alt</kbd> to switch tty under VirtualBox.

So please try again to catch the log.

**Comment by fusion809** [comment]
Not sure what <kbd>Super</kbd> is, but I have tried <kbd>Shift</kbd>+<kbd>s</kbd> and <kbd>Space</kbd>+<kbd>s</kbd>, neither of which lead to a preview. As for the tty, <kbd>Right Ctrl</kbd> (which is my host key, I know this as pressing <kbd>Right Ctrl</kbd>+<kbd>F</kbd> causes me to enter full screen within my host machine) + <kbd>F1</kbd> does nothing, as does <kbd>Right Ctrl</kbd> + <kbd>F2</kbd>, <kbd>Right Ctrl</kbd> + <kbd>F3</kbd>, ...

**Comment by fusion809** [comment]
@fasheng Not sure what <kbd>Super</kbd> is, but I have tried <kbd>Shift</kbd>+<kbd>s</kbd> and <kbd>Space</kbd>+<kbd>s</kbd>, neither of which lead to a preview. As for the tty, <kbd>Right Ctrl</kbd> (which is my host key, I know this as pressing <kbd>Right Ctrl</kbd>+<kbd>F</kbd> causes me to enter full screen within my host machine) + <kbd>F1</kbd> does nothing, as does <kbd>Right Ctrl</kbd> + <kbd>F2</kbd>, <kbd>Right Ctrl</kbd> + <kbd>F3</kbd>, ...

**Comment by fasheng** [comment]
Well, I'm afraid you have to reinstall DDE in a new VirtualBox image or do something useful else for we could not change anything even though found the solution...

And please try launch DDE through `xinit` instead of ligthdm next time.
