### ISSUE TITLE
launcher crashes session and nautilus panic

### ISSUE THREAD

**Issue by oberon2007** [fasheng/arch-deepin#94]
When I try to launch any applications from the launcher the session crashes and lightdm-deepin-greeter appears. Sometimes after that even logging back in is not possible.
Did not find I proper way to post the content of .xsession-error.log
Here it is as a screenshot:
part 1: http://imgur.com/DgZqouI.png
part 2: http://imgur.com/5a4BG11.png
part 3: http://imgur.com/heXdwBJ.png
part 4: http://imgur.com/T5hcRv3.png
...
and it goes on several more pages... ;)

**Comment by fasheng** [comment]
Fixed, please try again.

**Comment by oberon2007** [comment]
yes. working now :) But there is a new problem:
```
$ nautilus

(nautilus:1811): Gtk-WARNING **: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files
**
ERROR:nautilus-canvas-container.c:6009:finish_adding_new_icons: assertion failed: (!container->details->auto_layout)
Aborted (core dumped)
```

**Comment by fasheng** [comment]
But the nautilus works fine for me, I updated to the latest packages and launche DDE through xinit.

**Comment by oberon2007** [comment]
It's a bit weird here: Launching "Computer" from the desktop icon opens Nautilus normally, but when I launch Nautilus from the dock or the launcher it opens for a moment and then exits. Launching from the terminal gives the errors I posted...

**Comment by fasheng** [comment]
Well, all is OK for me...

**Comment by oberon2007** [comment]
resolved by removing **~/.config/nautilus**

**Comment by hoahau** [comment]
mmm...but... not for me...
take a look..
-------
➜  ~  nautilus

** (nautilus:29342): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-anfymrnTfT: Conexión rehusada

(nautilus:29342): Gtk-WARNING **: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files

(nautilus:29342): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:225:8: Missing name of pseudo-class

(nautilus:29342): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2350:20: Missing name of pseudo-class

(nautilus:29342): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2391:20: Missing name of pseudo-class

(nautilus:29342): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2570:21: Missing name of pseudo-class
Initializing nautilus-open-terminal extension
sys:1: Warning: invalid cast from 'GtkBox' to 'GtkToolbar'
^C^C^C^C^C^C^C^C







^C^C^C^C^C^C%                                                                                                                                                                                                       ➜  ~  
➜  ~  echo $?
1
➜  ~  rm 
rm: falta un operando
Pruebe 'rm --help' para más información.
➜  ~  rm ~/.config/nautilus
rm: no se puede borrar «/home/miguel/.config/nautilus»: Es un directorio
➜  ~  rm -rf ~/.config/nautilus
➜  ~  nautilus

** (nautilus:24698): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-anfymrnTfT: Conexión rehusada

(nautilus:24698): Gtk-WARNING **: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files

(nautilus:24698): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:225:8: Missing name of pseudo-class

(nautilus:24698): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2350:20: Missing name of pseudo-class

(nautilus:24698): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2391:20: Missing name of pseudo-class

(nautilus:24698): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2570:21: Missing name of pseudo-class
Initializing nautilus-open-terminal extension
sys:1: Warning: invalid cast from 'GtkBox' to 'GtkToolbar'

**Comment by hoahau** [comment]
..mm.. :(...
..in detail... as root...
it look like this...
----
gpartedbin:16640): GLib-CRITICAL **: Source ID 2227 was not found when attempting to remove it

(gpartedbin:16640): GLib-CRITICAL **: Source ID 2231 was not found when attempting to remove it

(gpartedbin:16640): GLib-CRITICAL **: Source ID 2230 was not found when attempting to remove it
root@mikele-pc:~# nautilus

(nautilus:2731): Gtk-WARNING **: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files

(nautilus:2731): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:225:8: Missing name of pseudo-class

(nautilus:2731): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2350:20: Missing name of pseudo-class

(nautilus:2731): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2391:20: Missing name of pseudo-class

(nautilus:2731): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2570:21: Missing name of pseudo-class
Initializing nautilus-open-terminal extension
sys:1: Warning: invalid cast from 'GtkBox' to 'GtkToolbar'



^Cg_dbus_connection_real_closed: Remote peer vanished with error: Underlying GIOStream returned 0 bytes on an async read (g-io-error-quark, 0). Exiting.
Terminado
root@mikele-pc:~# echo $?
143
root@mikele-pc:~#

**Comment by fasheng** [comment]
@hoahau Sorry, I really have no idea for your problem, and looks it is not caused by Deepin packages.

BTW, if you want to experimence the latest Deepin, please remove OBS repository from `/etc/pacman.conf` and update packages from [community] like this:

```sh
sudo pacman -R dde-dock-applets
sudo pacman -Syyuu
```
