### ISSUE TITLE
user "git" ??

### ISSUE THREAD

**Issue by oberon2007** [fasheng/arch-deepin#97]
Since the latest updates, when i create a new install, by default an extra "normal user" named "git" is created. Where might this come from and how can I avoid this?

**Comment by mmetak** [comment]
DDE shouldn't create any "git" account... maybe it's just showing the system git account that's created by the 'git' package?

**Comment by oberon2007** [comment]
hm. I think you are right. i have created another ISO with git not installed and the extra user is gone... still this is not really satisfying and it was not like that a few days ago. Do you have any idea what might be responsible for this new behaviour?

**Comment by oberon2007** [comment]
This issue persists with the newest pkgs.

**Comment by felixonmars** [comment]
Arch defines a system uid/gid range for random system user assignment:

```
$ cat /etc/login.defs | grep SYS_
SYS_UID_MIN               500
SYS_UID_MAX               999
SYS_GID_MIN               500
SYS_GID_MAX               999
```

I have tried some hack to remove this range from d-c-c, but didn't succeed. Any hints? @fasheng

**Comment by fasheng** [comment]
try hack the deepin-daemon/account module

**Comment by felixonmars** [comment]
Review sent :P
https://cr.deepin.io/#/c/9008/
(the jenkins failure looks cryptic to me :/)

And package to test with: (works for me, at least :P)
http://pkgbuild.com/~fyan/staging/deepin-daemon-2.93.1-3-x86_64.pkg.tar.xz

(This is my first Go lines, sorry if it contains anything stupid...)

**Comment by fasheng** [comment]
Great skill!
I fill the testing code and it should pass the checking of jenkins, now just wait for our developer to review it;)
@jouyouyun

**Comment by oberon2007** [comment]
Solved by the new pkg. :) Thanks a lot @felixonmars !
