### ISSUE TITLE
manjaro-deepin

### ISSUE THREAD

**Issue by oberon2007** [fasheng/arch-deepin#98]
@fasheng, @mmetak, @felixonmars I would like to say thank you again for the great effort and the excellent work you have done sofar on making deepin available on Arch and archbased systems.
I am happy to let you all know that I have now managed to put together a really nice version of Deepin based on Manjaro and produced a live environment / install media. If you would like to have a look, here it is: https://sourceforge.net/projects/manjaro-deepin/
The only bug I am facing still is the automatic theme updating when you change wallpapers, icons or xcursor-theme a few times in a row. Then you have to re-log for the changes to apply.
Apart from that everything seems to work really well and I think it shows that the newer more arch-grounded packages are quite a boost in performance. To be able to customize look&feel a bit I had to actually rebuild the majority of the packages because of the interdependencies... ;) In any case I was very keen on keeping the original design and wherever a manjaro-logo appears there is also a deepin-one (plymouth-theme, lightdm-deepin-greeter) next to it. The System Information and Copyright in the Control Center I have left untouched. So I hope that will be ok for everyone like that.
At the moment this ISO is not more than an experiment, but if the development continues like that I will be more than happy to officially anounce a full featured manjaro-deepin release.
best wishes
oberon.

**Comment by fasheng** [comment]
Thanks for your great job, Bernhard. And thanks for metak and felix's enthusiasm maintenance work. :+1:

In fact, Deepin desktop environment and apps are still very unstable now, thanks for your patient. We will try the best to improve them. :)

I just started downloading the iso image and waiting for another surprise. ;)

**Comment by oberon2007** [comment]
:) Thank you. Here's also a little teaser: https://www.youtube.com/watch?v=5TiuI3bsNm4

**Comment by felixonmars** [comment]
Really nice work, thank you :)

**Comment by fasheng** [comment]
Cool, The theme looks really beautiful !

About the logo icon, I thinks it doesn't matter for you just keep Deepin there. I'm not sure, maybe our designer like to draw one specially for you. ;)

**Comment by fasheng** [comment]
We are writing a new community site now, and will describe such porting work there, so manjaro-deepin will not be alone :)

**Comment by oberon2007** [comment]
Do you mean the greeter? Want me to put back the original logo there? The desktop icon for 'Manjaro Welcome' actually comes with the Dalisha icon theme - I was very surprised? ;)

**Comment by fasheng** [comment]
No, in my option, all the logo are OK for that you did not break the Deepin trademark, and just combine it with other harmless icons. :)

**Comment by oberon2007** [comment]
Ok, fine :-) of course I'm not a graphic designer, so if indeed a Deepin specialist would like to volunteer, that would be excellent ;-)

Am 31. Oktober 2015 09:59:21 MEZ, schrieb fasheng <notifications@github.com>:
>No, in my option, all the logo are OK for that you did not break the
>Deepin trademark, and just combine it with other harmless icons. :)
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/fasheng/arch-deepin/issues/98#issuecomment-152716671

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by oberon2007** [comment]
manjaro-deepin-15.12 release candidate 1 is out :)
https://sourceforge.net/projects/manjaro-deepin/files/manjaro-deepin-15.12rc1/

**Comment by fasheng** [comment]
:+1:



2015年12月14日 上午2:21, 上午2:21，在 Bernhard Landauer <notifications@github.com> 已写:

**Comment by oberon2007** [comment]
It's online, the **first stable release of manjaro-deepin-15.12**
I am still waiting a bit with the official announcement until at least a few more people have tested this.
So, it would be great if you'd like to give it a try.
https://sourceforge.net/projects/manjaro-deepin/
Works now pretty smooth even in a virtualbox thanks to the new Deepin2D feature, awesome.
Cheers everyone! :)

**Comment by fasheng** [comment]
Thanks for the great work. Downloading now.
Cheers!

**Comment by oberon2007** [comment]
And thanks to you all! :)
It's official now:
https://manjaro.github.io/Manjaro-Deepin-released/

**Comment by fasheng** [comment]
Wow, amazing news, just like a Christmas present for me  :+1:

**Comment by oberon2007** [comment]
I would like to pass on a report from the manjaro forums here. I think it contains some helpful information:
> Never tested Deepin before, didn't know what to expect.

> I liked the live CD so much I had to install it  8)

> The control center is THE best I've ever encountered, easy to use and understand.
However there are some glitches:
Opening control center and clicking the first time on Window or Wallpaper doesn't open the sub-view with the thumbnails.
Sub sequent tries work.
Also in Home view the Shutdown button is not properly placed.
(is not properly centered with the arc-line, placed left of center...)

> The launcher is good as well, however there is also a glitch:
Right click on an app opens a menu, and at the bottom there is the option Uninstall.
Clicking on it opens a dialog with the question if it really should be uninstalled.
Clicking on Confirm does nothing.

> The panel is not so flexible as it should be.
The height can't be changed, takes too much real estate.
Also the position can't be changed.

> The memory usage is huge.
Starts out with 750 MB and 30 minutes later it's double that, even if all apps have been closed.
There must be a memory leak or something...

> The windows can only be maximized.
If they could be placed to use up 50% of screen estate (left or right) like Gnome, Cinnamon, Budgie...

> All in all it's a nice desktop.
If the Deepin desktop could do tiling as i3 does as well, it could become a winner.
(if the memory usage could be contained)

**Comment by fasheng** [comment]
welcome and thanks for the message, i will split them to issues and advices later



2015年12月27日 下午4:10, 下午4:10，在 Bernhard Landauer <notifications@github.com> 已写:

**Comment by oberon2007** [comment]
Thanks! :) [this one](https://github.com/linuxdeepin/dde-control-center/issues/7) I have already placed upstream a few days ago :)

**Comment by fasheng** [comment]
yes, i saw it. it's sad that no one reply for it yet. we will improve such cases soon and let our developers take more care on issues in github instead bugzilla only . and most of the issues/advices will be moved/linked to the upstream github projects then, that's where they should go ;)



2015年12月27日 下午9:50, 下午9:50，在 Bernhard Landauer <notifications@github.com> 已写:

**Comment by oberon2007** [comment]
Forwarding another post from the manjaro-forums here:
```
I've spent the better part of today trying to get a VNC session going in Manjaro Deepin.  I have multiple Linux machines in the house all with VNC servers running and no issues.
I'm using x11vnc and can indeed connect to a session but it invariably crashes the client or freezes.  I've gone through tons and tons of variables and the same thing happens every time.  
I've used multiple clients as well from various computers.
```

**Comment by oberon2007** [comment]
Here's more info on that from the same user:
>Here's the contents of the script file I wrote which I call from cron (with a 60second delay to allow X to load).
>``x11vnc -display :0 -auth guess -norepeat -rfbauth /home/john/.vnc/passwd -shared -forever``
>The thing that smoothed things out was the addition of the -norepeat flag.  I've never used that before but I noticed in the terminal while the command was running that is said something was competing with no repeat or something like that. Should have copied it. 
>Anyway I've been using it an hour from several sources and it hasn't crashed yet so that -norepeat flag seems to be the workaround for now.

**Comment by oberon2007** [comment]
Here's someone else:
>In my case the deepin control center does not acknoledge the certificate file, even though it's a valid ca.crt file.
>BTW: networkmanager-openvpn is installed.

**Comment by fasheng** [comment]
>deepin control center does not acknoledge the certificate file, even though it's a valid ca.crt file.
It works for me, and I use openvpn all the time in arch-deepin. Could you give me a url of the question?

BTW: I could not access all the topic of manjaro, it report:
>Sorry Guest, you are banned from using this forum!
This ban is not set to expire.

**Comment by oberon2007** [comment]
oh! :D Would you mind setting up an account at the forum?
I'm afraid I don't have more information than I copied here, yet. And I have pointed people here.
We should try keeping the issues in one place anyway ;)
Than you so much for your help!

side note: manjaro-deepin has been downloaded 7.700 times meanwhile :scream:

**Comment by fasheng** [comment]
I want to register an account, but the error still there. Maybe caused by my VPN, but without it the forum is unaccessible for me :(

Really a surprise, can't wait to share it to the official forum :)

**Comment by oberon2007** [comment]
hm. sorry for that! :-/ So were you able to register at all? The forum is a bit outdated and will be renewed in the near future - hopefully ;) Let me know if I can be of any help to let you in there! ... ;) You are more than welcome to join us of course ... ...

**Comment by fasheng** [comment]
thanks, it's doesn't matter, i will try other vpn then~



2015年12月29日 下午6:57, 下午6:57，在 Bernhard Landauer <notifications@github.com> 已写:

**Comment by oberon2007** [comment]
New stable release **Manjaro Deepin 16.03** has been launched :smile: 
https://manjaro.github.io/Manjaro-Deepin-16.03-released/
https://forum.manjaro.org/index.php?topic=31714.msg260349#msg260349

Thank you all for your fantastic work and cooperation! @arch-deepin @linuxdeepin !!

**Comment by hualet** [comment]
@oberon2007 Congratulations! Hope we can still help each other in the future :smile:

**Comment by fasheng** [comment]
:+1: :+1: :+1:
I saw my comment in your post, looks not bad ;)

**Comment by oberon2007** [comment]
:joy:

**Comment by fasheng** [comment]
Welcome to join the the deepin developer center :)
